### ISSUE TITLE
SCL scenario build-all is slow for minicity map

### ISSUE THREAD

**Issue by liu-allan** [huawei-noah/SMARTS#1077]
## **BUG REPORT**

When using scl scenario build-all for multiple scenarios using the minicity map, the time it takes to build is much slower compared to running them each individually. Ex. for two scenarios, individually took ~30s to build each whereas when building together it took ~120s. Performance gets worse the more scenarios are built together.

**Comment by qianyi-sun** [comment]
The reason why this issue happens is that the code in `cli/studio.py` was using `Thread`. Instead, we've used `Process` to replace `Thread` to speed up the `build-all` runtime.

**Comment by saulfield** [comment]
@qianyi-sun I didn't see a PR linked to this, but it sounds like it's been resolved. Please reopen if not.
