### ISSUE TITLE
Traffic Lights

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#1079]
**Is your feature request related to a problem? Please describe.**
Traffic lights and priority are not currently provided in observation.

**Describe the solution you'd like**
Waymo traffic light simulation provided to the observations. 

**Describe alternatives you've considered**
Implemented native traffic light simulation.

**Additional context**
Recent requests for traffic light information. Removed previous traffic light information: #645

**Comment by Gamenot** [comment]
This has to go in 0.6 because it is an interface change.

**Comment by saulfield** [comment]
Addressed by #1529.
