### ISSUE TITLE
the bug when I run examples in readme

### ISSUE THREAD

**Issue by JingyuanHan** [huawei-noah/SMARTS#1130]
## **BUG REPORT**
when I run the code `from smarts.core.agent_interface import AgentInterface, AgentType`
it said that 
File "D:\anaconda\lib\ctypes\__init__.py", line 363, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'NoneType' is not iterable

**Comment by Gamenot** [comment]
@JingyuanHan Thank you for the bug report and sorry for the slow reply.

I do not think we will be easily able to resolve this issue. SMARTS currently supports macos and ubuntu-like linux distributions but does not support Windows OS (although it can work if using Windows Subsystem for Linux or Docker.) We do not currently have plans to add support for Windows OS.

If there is anything else I can help you with, please ask.
