### ISSUE TITLE
Grpc Timeout

### ISSUE THREAD

**Issue by dineshresearch** [huawei-noah/SMARTS#1135]
## **BUG REPORT**
**I am trying to run the marl benchmark example provided and facing the grpc timeout issue. *

**SMARTS version**
0.4.18

**Previous associated issues**
https://github.com/huawei-noah/SMARTS/issues/614

**Steps to reproduce the bug**
Perform the setup steps for smarts MARL Benchmark from readme  and then after installation run the below command

from baselines/marl_benchmark/
python3.7 run.py scenarios/intersections/4lane -f agents/ppo/baseline-lane-control.yaml
$ python3.7 run.py -f <config_file>

**Resulting and expected behaviour**
Should start the training process with out any errors

**Error logs and screenshots**
![image](https://user-images.githubusercontent.com/26215090/142922009-233d795b-ad05-499e-86f8-8f001c34cc8e.png)

 
**System information**
 
- Operating system & Environment [Please note if using Docker]: Ubuntu 18.04
- Number of system cores available
- Python version [Please note if using Jupyter] Python 3.7.7
- Python packages [e.g. from `pip freeze`]  [freeze.txt](https://github.com/huawei-noah/SMARTS/files/7583858/freeze.txt)
- SUMO version  1.10.0
- Date when bug occurred 2021-11-21
 
**Impact [If known]*

*

**Comment by dineshresearch** [comment]
I have tested with master branch and release-4.18 branch as well and leading to the same issue. @Gamenot @Adaickalavan @RutvikGupta can you please kindly help me with the fix.

**Comment by Adaickalavan** [comment]
Use of grpc has been suppressed and should not cause any errors in the latest develop branch. We hope this addresses your question and thus this issue is being closed. Please feel free to reopen this issue if your problem persists or open a new issue for other questions.
