### ISSUE TITLE
error : couldn't find remote ref refs/heads/master when installing on MACOS

### ISSUE THREAD

**Issue by cz0204** [huawei-noah/SMARTS#1147]
## **BUG REPORT**
**High Level Description**
I am trying to install SMARTS on MACOS (Monterey). When i run "bash utils/setup/install_deps.sh", an error occurs as following:

<img width="971" alt="issue" src="https://user-images.githubusercontent.com/84425524/144510974-cc5ca8eb-e85f-41b7-b69c-5653383503bd.png">

**Comment by sah-huawei** [comment]
Maybe `master` has been changed to `main`?

**Comment by sah-huawei** [comment]
> Maybe `master` has been changed to `main`?

Yeah, that seems to be the cause of the problem.  Looks like the [homebrew-sumo repo](https://github.com/DLR-TS/homebrew-sumo) changed from `master` to `main` in August.

Here's an issue a different tool filed with Homebrew about similar problems when they made the change that may contain clues for workarounds:   https://github.com/Homebrew/brew/issues/7746
And a relevant Homebrew discussion:  https://github.com/Homebrew/discussions/discussions/592

**Comment by sah-huawei** [comment]
From skimming those links, one thing to try is to do `brew untap dlr-ts/sumo` from the command line before trying `bash utils/setup/install_deps.sh` again.  I'm not optimistic that will fix it, but it's worth a try first before doing more convoluted things.

**Comment by cz0204** [comment]
Thanks for the feedback. The above solution helps and it works. I guess it might be the reason that I used to install sumo before for some other project. And this might somehow affect the branch. Thanks.
