### ISSUE TITLE
pynput causes exception on WSL2

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#1152]
## **BUG REPORT**
**High Level Description**
Running pip install for SMARTS on WSL2 will cause `evdev` compilation (under pynput) to fail to build.

**SMARTS version**
0.4.18

**Previous associated issues**
N/A

**Steps to reproduce the bug**
```
# WSL2
$ cd $SMARTS_REPO
$ pip install -e .
```

**Resulting and expected behaviour**
Should install SMARTS fully but instead crashes on building `evdev`.

**Error logs and screenshots**
![003f73d0714ec300ab1be15636a31c9](https://user-images.githubusercontent.com/59240680/144888915-df8e46df-b559-4653-89c5-ee67156b8164.png)
 
**System information**
 
- Operating system & Environment [Please note if using Docker]:
WSL2 
- Number of system cores available
4
- Python version [Please note if using Jupyter]
python 3.8
- Python packages [e.g. from `pip freeze`]
- SUMO version
- Date when bug occurred  dd_mm_yyyy
06_12_2021
 
**Impact [If known]**
Unable to install SMARTS on WSL2.

**Comment by qianyi-sun** [comment]
Here's the screenshot:

![003f73d0714ec300ab1be15636a31c9](https://user-images.githubusercontent.com/59240680/144888915-df8e46df-b559-4653-89c5-ee67156b8164.png)

**Comment by RutvikGupta** [comment]
I installed `sudo apt-get install python3.8-dev` the developer version of `python3.8` (same for `python3.7`) for my WSL2 setup and didn't have this issue.

**Comment by Gamenot** [comment]
> I installed `sudo apt-get install python3.8-dev` the developer version of `python3.8` (same for `python3.7`) for my WSL2 setup and didn't have this issue. More about this here: https://stackoverflow.com/questions/26053982/setup-script-exited-with-error-command-x86-64-linux-gnu-gcc-failed-with-exit

I think that is useful but I would prefer that we do not require the developer version of python to run SMARTS.
