### ISSUE TITLE
Error! Vehicle 'car-flow-random-route' is not known.

### ISSUE THREAD

**Issue by Adaickalavan** [huawei-noah/SMARTS#1155]
## **BUG REPORT**
**High Level Description**
SUMO released a new version 1.11.0 on 21 Nov 2021, which throws the following error when running with SMARTS:
`Error! Vehicle 'car-flow-random-route-bc8cc765-7266489842092764092--0-0.0' is not known.`

**SMARTS version**
0.4.18

**Steps to reproduce the bug**
Reproduce error with new sumo==1.11
```bash
$ git clone https://github.com/huawei-noah/SMARTS.git
$ git checkout sumo-version
$ docker build --no-cache --network=host --file=<path>/SMARTS/examples/Dockerfile.111 --tag=sumo_111 <path>/SMARTS
$ docker run --rm -it --network=host sumo_111
(container) $ sumo # Check sumo==1.11
(container) $ scl scenario build-all ./scenarios/loop/
(container) $ python3.7 ./examples/multi_agent.py ./scenarios/loop --headless
```

Compare with old sumo==1.10.0
```bash
$ git clone https://github.com/huawei-noah/SMARTS.git
$ git checkout sumo-version
$ docker build --no-cache --network=host --file=<path>/SMARTS/examples/Dockerfile.110 --tag=sumo_110 <path>/SMARTS
$ docker run --rm -it --network=host sumo_110
(container) $ sumo # Check sumo==1.10
(container) $ scl scenario build-all ./scenarios/loop/
(container) $ python3.7 ./examples/multi_agent.py ./scenarios/loop --headless
```

**Resulting and expected behaviour**
No error messages should be printed.

**System information**
- Operating system: Ubuntu 18.04
- Python version: 3.7
- SUMO version: 1.10 and 1.11
- Date when bug occurred: 7 Dec 2021

**Comment by jieye-ericx** [comment]
hello,may I ask if you have solved this problem, I can only install sumo 1.15 using apt-get on ubuntu.

**Comment by Adaickalavan** [comment]
Hi @jieye-ericx, 
+ sumo is now installed automatically via the `setup.py` file in our `smarts` package while pip installing the `smarts` package.
+ see `setup.py` file here: https://github.com/huawei-noah/SMARTS/blob/13bfeb91be46bebcbd5c832ff55e1bd8b20abeba/setup.py#L28
+ to manually install sumo, do `pip install eclipse-sumo==1.10.0`.
+ for the time being, please continue using `eclipse-sumo==1.10.0` in our `smarts` package, until we verify the newer versions of sumo.
+ please let us know if you have any other problems with using sumo in relation to our `smarts` package.

**Comment by jieye-ericx** [comment]
thanks,I did solve the problem by updating the smarts version
