### ISSUE TITLE
`scl scenario build` throws FILENOTFOUNDERROR

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#1159]
Calling `scl scenario build` with an empty directory (subdirectories within a directory) will cause an exception.

See #1153:
>@qianyi-sun Can u check if you have a `scenarios/behaviour_model` folder in your cloned SMARTS repository? 
Removing that folder will resolve this issue for you. @sah-huawei removed the `map.net.xml` from all behavior model scenarios but since we generate a shifted normalized `map.net.xml` for `SUMO` maps, which are git ignored, they exist as local files on cloned repositories before this change. 
|
Since build-all command in `cli/studio.py` looks for `.net.xml` references in all scenarios folder, it picks up the behavior models but does not find the `map.net.xml` reference and hence throws the `FILENOTFOUNDERROR`.
|
P.S.: I had the same issue. Removing the folder from my local repo resolved the errors..

_Originally posted by @RutvikGupta in https://github.com/huawei-noah/SMARTS/issues/1153#issuecomment-987146360_

**Comment by sah-huawei** [comment]
Looks like `scl scenario build-all missing` doesn't raise, but `scl scenario build missing` does (in both the case where "missing" is an empty folder and a non-existent folder).
I personally think this is "as it should be", with the caveat that the exception that is raised in the latter case should just report that the folder is empty. 
That is,  I don't think we should assume or require that the scenario folder should contain a _SUMO_ map file, per se, as we now support scenarios with alternative map formats as well.
