### ISSUE TITLE
Lane information in rgb image observation

### ISSUE THREAD

**Issue by Adaickalavan** [huawei-noah/SMARTS#1160]
**Is your feature request related to a problem? Please describe.**
Currently our top-down rgb image observation in SMARTS looks like the following. It does not contain any lane information.
<img src="https://user-images.githubusercontent.com/24203326/145252716-f4ea40af-adf2-4c9a-b285-a87eb2ef8319.png" width="300"/>

**Describe the solution you'd like**
It would be helpful, if we could add lane dividers into the top-down rgb image observations. An example image is as follows:
<img src="https://user-images.githubusercontent.com/24203326/145252242-289ab609-6a03-483f-b432-c746e197ef21.png" width="300"/>

**Describe alternatives you've considered**
Without embedded lane information in rgb image observations, users will have to manually combine (i) lane information (i.e., lane index, waypoints, etc.) and (ii) rgb images, to form input to RL training.

**Comment by sah-huawei** [comment]
I fully support this.  Just a few questions (@Adaickalavan):

- Do we need to indicated other semantic aspects as well, such as whether adjacent lanes go in the same direction (white lines) or opposite directions (yellow lines)?
- Are there any requirements (or even "desirable properties") for the lane dividing marks?  For example, can the dashed line in you example be more like a "dotted line"?  How think should this dashed (or dotted) line be? 
- Do we also need to add (presumably-solid)  "road boundary lines" (as in your picture above)?  If so, does it matter whether we have them "crossing through the intersections" (as in your picture above), or should they instead indicate places where vehicles should not normally cross (and so not be drawn in intersections)?

(Note that the quality of what we can do here will heavily depend on other properties of our representation, such as its resolution, and the precision with which the polygons are drawn.  That's something that is probably a good topic for another issue.  I will link that one to here once I've made it.)

**Comment by Adaickalavan** [comment]
We may consider adding the following:
+ Yellow solid/broken lines - separate traffic travelling in opposite directions. https://files.ontario.ca/3-1.jpg
+ White broken lines - separate traffic travelling in the same direction. https://files.ontario.ca/3-1.jpg
+ White broken lines that are wider and closer - lane is ending or exiting. https://files.ontario.ca/3-4.jpg
+ White line painted across the road at an intersection - a stop line. https://files.ontario.ca/3-5.jpg

I guess, the more realistic the road markings are in our RGB image, the better it is.

1) Broken lines can be dashes rather than dots.
2) Not sure of the exact thickness of the dashes. I guess any reasonable thickness with respect to the lane width would be okay.
3) Dashes could be curved if it is easier to draw curved dashes by following the lane curvature. If the dashes are short, then they may not need to curve.
4) Road boundary lines would be nice feature, considering we have `on-shoulder` event. Road boundary lines should not cross intersections. Our current road and off-road are of different colours, hence road boundary lines are not immediately needed if they are difficult to draw properly without crossing through intersections.
