### ISSUE TITLE
Example agent that follows a mission

### ISSUE THREAD

**Issue by saulfield** [huawei-noah/SMARTS#1167]
**Is your feature request related to a problem? Please describe.**
While testing the OpenDrive implementation of waypoints, we noticed there doesn't seem to be an agent in the examples that follows waypoints for a mission. This would be a good example to have for users and for testing.

**Describe the solution you'd like**
An audit of the example agents, and a new agent that fits this role if we don't already have a similar one.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by liu-allan** [comment]
Is there an example scenario in mind to test? By waypoints do you mean something similar to vias?
