### ISSUE TITLE
RuntimeWarning: invalid value encountered in double_scalars 

### ISSUE THREAD

**Issue by Adaickalavan** [huawei-noah/SMARTS#1171]
## **BUG REPORT**
**High Level Description**
While running the scenarios, sometimes the following error is thrown
```
/SMARTS/smarts/core/sumo_road_network.py:331: RuntimeWarning: invalid value encountered in double_scalars
lane_angle = np.dot(my_vect, lv) / (my_norm * np.linalg.norm(lv))
```
This is because the lane vector is zero, i.e., `lv = lane.vector_at_offset(offset) = [0 0 0]` , at line `SMARTS/smarts/core/sumo_road_network.py:331`. A divide by zero occurs, producing a nan and the error message.

**SMARTS version**
Latest `develop` branch

**Previous associated issues**
None

**Steps to reproduce the bug**
```
$ git checkout scenario-error
$ scl scenario build-all ./scenarios/intersections/2lane_test/
$ python3.7 ./examples/single_agent.py ./scenarios/intersections/2lane_test/
```

**Resulting and expected behaviour**
Proper lane vectors should not be zero.

**Error logs and screenshots**
![image](https://user-images.githubusercontent.com/24203326/145624457-eb1c815a-8e3c-4026-87f7-aff755d78453.png)
 
**System information**
 
- Operating system & Environment: Ubuntu 18.04
- Python version: 3.7
- SUMO version: 1.10.0
- Date when bug occurred: 10 Dec 2021

**Comment by sah-huawei** [comment]
@Adaickalavan Could you please fill in the "steps to reproduce this bug" section too?  Thanks.

**Comment by Adaickalavan** [comment]
@sah-huawei 
I have included the steps to reproduce the error message in the issue description.
