### ISSUE TITLE
Sanity-test failed with WSLg

### ISSUE THREAD

**Issue by BravoFr0st** [huawei-noah/SMARTS#1177]
**Sanity-test failed**

**SMARTS version：0.4.18**

**Operating System：Ubuntu 18.04 LTS on WSL2(Windows 11)**
**WSLg has enabled**

**Problems**
After `make sanity-test`, all tests passed EXCEPT `test_smarts_doesnt_leak_tasks_after_reset`
```
 A renderer is required to test smarts_doesnt_leak_tasks_after_reset. You may not have installed the [camera-obs] dependencies required to render the camera sensor observations. Install them first using the command `pip install -e .[camera-obs]` at the source directory.
...
------------------------------------------------------ Captured log call ------------------------------------------------------
WARNING  SMARTS:smarts.py:532 unable to create Renderer:  Exception('No graphics pipe is available!\nYour Config.prc file must name at least one valid panda display\nlibrary via load-display or aux-display.')
------------------------- generated xml file: /home/lzy123/NGSIM_SMARTS/SMARTS/sanity_test_result.xml -------------------------
```

However, my WSL has already enabled WSLg , and other program (such as sumo) can open a GUI.

After that I try to run `scl scenario build --clean scenarios/loop` and `scl run --envision examples/single_agent.py scenarios/loop` and 
no error occurs.

**Comment by Gamenot** [comment]
Hello @BravoFr0st , thank you for reaching out. I believe it is promising that sumo-gui is working so I am going to take a look into WSLg compatibility.

Otherwise, the rest of SMARTS will work even without rendering until you have need to use image based observations. Envision will still work since it is rendered through the browser.

**Comment by BravoFr0st** [comment]
Thanks a lot.

**Comment by Gamenot** [comment]
@BravoFr0st I have put up some improved tests. If you have the time could you do the following:

```
git checkout tucker/bugfix-wslg_rendering_failure
pytest -vv --renderer-debug-mode info smarts/core/tests/test_renderers.py::test_optional_renderer
```

It would help greatly towards solving the issue.

**Comment by Gamenot** [comment]
I have also enabled some rendering fallbacks on the `wslg` bug branch so it is also possible it will pass without problems.

**Comment by nkaslin** [comment]
> @BravoFr0st I have put up some improved tests. If you have the time could you do the following:
> 
> ```
> git checkout tucker/bugfix-wslg_rendering_failure
> scl scneario build --clean scenarios/loop
> pytest -vv --renderer-debug-mode info smarts/core/tests/test_renderers.py::test_optional_renderer
> ```
> 
> It would help greatly towards solving the issue.

Hello, I had the same issue with the sanity-test. Since the other person didn't reply, I'm just letting you know that I ran the commands you listed and the test passed. Hope it helps.
