### ISSUE TITLE
Controller for dynamic model between steps

### ISSUE THREAD

**Issue by CyberSY** [huawei-noah/SMARTS#1191]
**Is your feature request related to a problem? Please describe.**
I'm now trying to learn a model to produce action(a) given the current state(s) and next state(s') between steps without the prior knowledge of the car dynamic model used in SMARTS. I wonder whether it is possible to provide a controller based on the car dynamic model with the same function? That will help me a lot.

**Describe the solution you'd like**
A simple PID controller for example. It would be better if the controller can distinguish the unreachable state. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Adaickalavan** [comment]
Please take a look at the [action spaces](https://smarts.readthedocs.io/en/latest/sim/obs_action_reward.html#action) currently supported by SMARTS. 

If your issue persists or for other questions, consider opening a new issue.
