### ISSUE TITLE
Conform to Gym Spaces at Environment Level

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#1192]
Gym environments should provide the following:

AC:
- [x] The exact `gym.Space` for the observations it returns (`observation_space`)
- [x] The exact `gym.Space` for the actions it accepts (`action_space`)
- [x] Environment `action_space`
- [ ] A way to isolate per-agent `action_space`s

**Comment by Adaickalavan** [comment]
1. A SMARTS environment will have gym-compatible action space attribute when wrapped with the `FormatAction` env wrapper from `SMARTS/smarts/env/wrappers/format_action.py`.

2. What is needed to statisfy the requirement _"A way to isolate per-agent action_spaces"_ ?

**Comment by Adaickalavan** [comment]
Related pull requests:

**Comment by Adaickalavan** [comment]
1. SMARTS does not inherently provide gym compliant or RL-friendly interface.
1. Related pull requests in making inherent changes to SMARTS interface:
    + #691 
    + #712 
1. Alternatively, a SMARTS environment can be made gym-compatible by wrapping it with the `FormatObs` and `FormatAction` env wrappers.
1. What is needed to statisfy the requirement _"A way to isolate per-agent action_spaces"_ ?

**Comment by Adaickalavan** [comment]
Closed by #1793
