### ISSUE TITLE
Observation adapter `gym.Space` utility

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#1193]
The observation adaptor for SMARTS `gym` environments should be paired with the `gym.Space` that it returns.

AC:
- [ ] Observation adapter cannot be submitted to HiWayEnv without `gym.Space`
- [ ] Observation adapter cannot be submitted to RLlibHiWayEnv without `gym.Space`
- [ ] See #1279

**Comment by Adaickalavan** [comment]
Closed by #1779
