### ISSUE TITLE
SB3 Training Example (SB3 integration)

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#1198]
Add a Stable Baselines 3 (`SB3`) training example to show integration with `SB3`.

AC:
- [x] PPO trained example
- [ ] DQN trained example

Blocked by:
- [ ] #1192

**Comment by Adaickalavan** [comment]
An unprotected left-turn intersection at [SMARTS/examples/rl/intersection](https://github.com/huawei-noah/SMARTS/tree/53ff4131d1649ddf05156219d3ab8bee1aa9c4f2/examples/rl/intersection) shows how StableBaselines3 PPO algorithm may be used to develop a reinforcement learning agent to turn left at an unprotected intersection.

**Comment by Adaickalavan** [comment]
A Stable Baselines3 PPO example is available [here](https://smarts.readthedocs.io/en/latest/examples/platoon.html).
