### ISSUE TITLE
Add type annotation test

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#1207]
**Is your feature request related to a problem? Please describe.**
The is based on a need to detect issues with code such as cases where the return type is not as listed or where types are not determined properly.

**Describe the solution you'd like**
Add a `mypy` test to ensure that auto code documentation is consistent with the behaviour of the code. 

**Describe alternatives you've considered**
-Needs investigation

**Additional context**
See: https://mypy.readthedocs.io/en/stable/introduction.html

**Comment by Adaickalavan** [comment]
An alternative type analyzer to consider would be [Pytype](https://google.github.io/pytype/) .

**Comment by Gamenot** [comment]
We should go with Pytype for this test.
