### ISSUE TITLE
Start the controlled vehicle from the middle of the expert trajectory

### ISSUE THREAD

**Issue by zbzhu99** [huawei-noah/SMARTS#1210]
**High Level Description**
Currently we select different expert vehicles as ego agents during imitation learning rollout, and we take control from the *starting point* of the corresponding expert trajectory. However, this may make it difficult to sample data from later sections of the road during the early stages of training. Does SMARTS now support getting control from some middle points of a particular history trajectory?

**Comment by zbzhu99** [comment]
I wrote a relatively crude implementation here, and it seems to work: https://github.com/zbzhu99/NGSIM_SMARTS/commit/02c5cff5dc2d83c2f42901044441c7bf2f517538

**Comment by sah-huawei** [comment]
> I wrote a relatively crude implementation here, and it seems to work: [zbzhu99/NGSIM_SMARTS@02c5cff](https://github.com/zbzhu99/NGSIM_SMARTS/commit/02c5cff5dc2d83c2f42901044441c7bf2f517538)

This seems like a reasonable solution (although note that I did just add a comment on the diff about one thing that looked odd to me).

If it's helpful, we can add something like this to our `history_vehicles_replacement_for_imitation_learning.py` example, as well as add something like your `get_vehicle_start_at_time()` method to our codebase.
