### ISSUE TITLE
Remove deprecated code from `agent.py`

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#1221]
**Is your feature request related to a problem? Please describe.**
Deprecation of `agent_spec` code has been longstanding. We can now remove it.

**Describe the solution you'd like**
Remove `AgentPolicy`, and `policy_builder` + `policy_params` from `AgentSpec`.

**Additional context**
It is also to be considered here to move `AgentSpec` out of `core` and into `Zoo` instead since the `AgentSpec` should never enter the engine.

**Comment by sah-huawei** [comment]
I didn't move `AgentSpec` out of the core, as that would have required changing around 80 files spread throughout the repo, which seemed a bit dangerous this late in the 0.5 release cycle.  I will open a new issue to track that and it can be done in a separate PR if still desired.
