### ISSUE TITLE
Generating continuous loop scenario 

### ISSUE THREAD

**Issue by Rza-A** [huawei-noah/SMARTS#1239]
**High Level Description**
I am new to SMARTS and Sumo. I  am trying to generate a continuous loop scenario. The scenario that I wish to deploy has already been implemented in the Project Flow ([Video for the scenario](https://www.youtube.com/watch?time_continue=1&v=vFJvjPC8eNo&feature=emb_title))

![Scenario Generated](https://i.ibb.co/wBDhV0r/loop2.png)

**Desired SMARTS version**
0.4.18

**Operating System**
Arch Linux

**Problems**
I read the documentation and the example scenarios. However still have problem to tackle the following challenges:

1. The vehicles are generated one by one instead of all together as shown the image below.
2. It seems that the vehicles are vanished after they reach the end of the road/edge. I can see in the [Sumo documentation ](https://sumo.dlr.de/docs/Tutorials/Driving_in_Circles.html) that we need to add rerouters. But,  I am not sure how can we do this using Scenario Studio.
3. How can I add/generate car follow model?

![Scenario Generated](https://i.ibb.co/8XTnPKv/loop.png)

I created the map and my code for generating the scenario is as follows

```from pathlib import Path

from smarts.sstudio import gen_scenario
from smarts.sstudio import types as t
from smarts.sstudio import gen_traffic


traffic = t.Traffic(
    flows=[
        t.Flow(
            route=t.Route(begin=("top", 0, 'random'), end=("bottom", 0, 'max')),
            # route=t.Route(begin=("445633932", 0, 'random'), end=("445633931", 0, 'max')),
            begin=0, end=1 * 60 * 60, rate=0.1,
            actors={t.TrafficActor(name="car"): 1},
        )
        for i in range(20)
    ]
)

# open_agent_actor = t.SocialAgentActor(
#     name="open-agent", agent_locator="zoo.policies:keep-lane-agent-v0"
# )

# laner_actor = t.SocialAgentActor(
#     name="keep-lane-agent",
#     agent_locator="zoo.policies:keep-lane-agent-v0",
# )

gen_scenario(
    t.Scenario(
        traffic={"basic": traffic},
    ),
    output_dir=Path(__file__).parent,
)
```

I would be grateful if you could help me with the above challenges.

Thank you

**Comment by Gamenot** [comment]
Ah, this is something that SMARTS scenario generation does not explicitly support. I am going to see if I can get this working.

**Comment by Gamenot** [comment]
Some support for this with #1431.
