### ISSUE TITLE
Open Drive road map lane indices do not correspond to observation lane indices

### ISSUE THREAD

**Issue by liu-allan** [huawei-noah/SMARTS#1246]
## **BUG REPORT**
**High Level Description**
The lane indices in `obs.ego_vehicle_state` do not match the lane indices in the road map. The lane indices in `obs.ego_vehicle_state` start at 0 in the rightmost lane while in the road map starts at 0 in the leftmost lane. 

**SMARTS version**
[0.5.0]

**Steps to reproduce the bug**
- `print(current_lane)` in `perform_lane_following()` after line 85 smarts/core/controllers/lane_following_controller.py
- `print(obs.ego_vehocle_state.lane_index)` in `act()` in examples/single_agent.py
- `scl run examples/single_agent.py scenarios/od_merge`

**Resulting and expected behaviour**
When the vehicle is near the end of the episode:
![image](https://user-images.githubusercontent.com/44624435/150023376-9fc1f8cd-ca72-418f-bd0a-98583e214bb8.png)

The vehicles current lane according to the observation should be 2 and the current lane according to the road map should be 0.

![image](https://user-images.githubusercontent.com/44624435/150023801-658b0cba-741d-4d47-87b9-5a48079bbab6.png)

In the above image, `from agent curr` means the lane index from the observation, `from controller curr` means the lane index from the road map

**Comment by RutvikGupta** [comment]
Hi @liu-allan. I just checked the lane index returned by `OpendriveRoadNetwork` and I can guarantee that the rightmost lane in this road network start from 0. This is proven by your output above. 
following your instructions above,
`print(obs.ego_vehicle_state.lane_index) in act() in examples/single_agent.py` is the lane index from the road map actually and not the observation which comes out to be 2 which is correct. It is being set in `sensors.py`,
``` python
 closest_lane = sim.road_map.nearest_lane(vehicle.pose.point)
        if closest_lane:
            ego_lane_id = closest_lane.lane_id
            ego_lane_index = closest_lane.index
            ego_road_id = closest_lane.road.road_id
```
This shows that the observation values are set from `road_map.nearest_lane` and hence shows that `OpendriveRoadNetwork` is setting the lane index correctly.

Also what you are assuming to be a lane index by doing the following,
 `print(current_lane) in perform_lane_following() after line 85 smarts/core/controllers/lane_following_controller.py`
is actually index of the path from all waypoint path available at the current vehicle position for which the vehicle is closest to the first waypoint of that path. `current_lane` is not a lane index.

```python
    @staticmethod
    def find_current_lane(wp_paths, vehicle_position):
        relative_distant_lane = [
            np.linalg.norm(wp_paths[idx][0].pos - vehicle_position[0:2])
            for idx in range(len(wp_paths))
        ]
        return np.argmin(relative_distant_lane)
```
0 above is the correct value showing that the path the ego is currently following at lane index 2 is closest.

Also you can confirm that we return the correct lane index in  `OpendriveRoadNetwork`  by checking the road map tests we have in `smarts/core/tests/test_map.py`. You can also use this visualizer to see which lane id refers to which lane.

**Comment by liu-allan** [comment]
> Hi @liu-allan. I just checked the lane index returned by `OpendriveRoadNetwork` and I can guarantee that the rightmost lane in this road network start from 0. This is proven by your output above.
> 
> Following your instructions above, `print(obs.ego_vehicle_state.lane_index) in act() in examples/single_agent.py` is the lane index from the road map actually and not the observation which comes out to be 2 which is correct. It is being set in `sensors.py`,
> 
> ```python
>  closest_lane = sim.road_map.nearest_lane(vehicle.pose.point)
>         if closest_lane:
>             ego_lane_id = closest_lane.lane_id
>             ego_lane_index = closest_lane.index
>             ego_road_id = closest_lane.road.road_id
> ```
> 
> This shows that the observation values are set from `road_map.nearest_lane` and hence shows that `OpendriveRoadNetwork` is setting the lane index correctly.
> 
> Also what you are assuming to be a lane index by doing the following, `print(current_lane) in perform_lane_following() after line 85 smarts/core/controllers/lane_following_controller.py` is actually index of the path from all waypoint path available at the current vehicle position for which the vehicle is closest to the first waypoint of that path. `current_lane` is not a lane index.
> 
> ```python
>     @staticmethod
>     def find_current_lane(wp_paths, vehicle_position):
>         relative_distant_lane = [
>             np.linalg.norm(wp_paths[idx][0].pos - vehicle_position[0:2])
>             for idx in range(len(wp_paths))
>         ]
>         return np.argmin(relative_distant_lane)
> ```
> 
> 0 above is the correct value showing that the path the ego is currently following at lane index 2 is closest.
> 
> Also you can confirm that we return the correct lane index in `OpendriveRoadNetwork` by checking the road map tests we have in `smarts/core/tests/test_map.py`. You can also use this [visualizer ](https://www.sebastian-pagel.net/)to see which lane id refers to which lane.

Ah I see, thank you for the response! This is my bad lol I'll close the issue
