### ISSUE TITLE
Support large agent vehicles controlled by OpEn

### ISSUE THREAD

**Issue by liamchzh** [huawei-noah/SMARTS#126]
Social vehicles can be buses or trucks, likewise, agents can also be specified a vehicle type. 

Maybe starts with discrete action space?

**Comment by Gamenot** [comment]
@iman512003 @davidrusu Pair over it.

**Comment by iman512003** [comment]
1-create a urdf file for large vehicle model.
2-make sure that the controllers works with the new urdf model.
3-extend the result to OpEn.

**Comment by iman512003** [comment]
closed in favor of #198 ,#199, #200 .
