### ISSUE TITLE
Meta file to watch for scenario changes

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#1262]
**Is your feature request related to a problem? Please describe.**
The base issue here is that we currently require `scl scenario --clean` in most cases to rebuild scenarios. This could be greatly sped up by skipping cases where things do not need to be rebuilt.

**Describe the solution you'd like**
I suggest a meta file that would maintain a hash of base scenario resource files:
- Map (e.g. map.xml)
- Scenario (e.g. scenario.py)
- requirements (e.g. requirements.txt)

When such files are noted to have changed it would trigger a rebuild of dependent scenario resources. This would be useful especially for very large maps and complex scenarios that take a long time to build.

**Comment by Adaickalavan** [comment]
Closed by #1764
