### ISSUE TITLE
More information about waypoint_paths in Observations

### ISSUE THREAD

**Issue by zyk516** [huawei-noah/SMARTS#1277]
**High Level Description**
I want to ask a few questions:
1. the distance between every waypoint in one route and how many waypoints are there in one route and if it is a fixed quantity.
2. how far  is the farthest waypoint from ego and if it is fixed.
3. how waypoint_paths is generated
**Desired SMARTS version**
[e.g. 0.4.18]
Thank you very much.

**Comment by Gamenot** [comment]
Hello @zyk516: 

> 1) the distance between every waypoint in one route and how many waypoints are there in one route and if it is a fixed quantity.

- There are two sets of waypoints:
  - `waypoints`->`waypoint_paths`
  - `road_waypoints`

## `waypoints`/`waypoint_paths`
- The distance between each waypoint is roughly 1 meter.
- The waypoints supplied are a fixed distance starting ahead on the route from the vehicle's offset on the route centerline.
- We give a fixed number of waypoints based on the `lookahead` configuration to `AgentInterface.waypoints` as below
```
AgentInterface(
  ...,
  waypoints=agent_interface.Waypoints(lookahead=32)
)
```
- The route does not have any specific number of waypoints but it does have a fixed length
- The distance travelled on the route can be checked in the `Observation.distance_travelled` value
## `road_waypoints`
- The distance is usually 1 meter (with some exceptions)
- The `road_waypoints` will show up from all nearby lanes regardless of route
> 2) how far is the farthest waypoint from ego and if it is fixed.
## `waypoint`/`waypoint_paths`
- The closest distance of a waypoint can be any distance away from the ego
- If directly on route: the furthest waypoint in world coordinate will be as far away or less than the `lookahead`, and `lookahead` distance ahead in the route coordinate.
> 3) how waypoint_paths is generated
- `waypoints` is generated _**at each step**_ by casting the ego vehicle's position onto the route as an offset and then relative to that offset on the route generating the waypoints forward along the route centerlines. All parallel lanes are given.
- `road_waypoints` are generated at reset, sit in fixed locations, and are 1 meter apart on their lanes but can be less than that at the seams between roads (This can be most noticeable in intersections.)

**Comment by Adaickalavan** [comment]
We hope the above addresses your question and thus this issue is being closed. Please feel free to reopen this issue if your problem persists or open a new issue for other questions.
