### ISSUE TITLE
hiway_env close block

### ISSUE THREAD

**Issue by charleschen6** [huawei-noah/SMARTS#128]
use SMARTS master version
in zoo/evaluation direcotry use run_evaluation.py to run multiple scenarios and metrics, but block in first scenario env close.

**Comment by charleschen6** [comment]
debug step:
1. run_evaluation.py: python(command):             stdout=sys.stdout,
2. smarts/env/hiway_env.py: close(self): 
```python
    def close(self):
        print("In %s close" % __file__)
        if self._smarts is not None:
            print("self smarts is not None")
            self._smarts.destroy()
        else:
            print("self smarts is None")
            exit(0)
```
3. smarts/core/smarts.py
```python
    def destroy(self):
        print("self.teardown start")
        self.teardown()
        print("self.teardown end")
        if self._envision:
            print("self._envision start")
            self._envision.teardown()
            print("self._envision end")
        if self._visdom:
            print("self._visdom start")
            self._visdom.teardown()
            print("self._visdom end")
        print("self._agent_manager.destroy() start")
        self._agent_manager.destroy()
        print("self._agent_manager.destroy() end")
        self._bullet_client.disconnect()
        print("super().destroy() start")
        print("super().destroy() end")
        super().destroy()
```
4. execute log:
─┬────────────────────╮
│            Episode │     Sim T / Wall T │        Total Steps │        Steps / Sec │       Scenario Map │    Scenario Routes │     Mission (Hash) │             Scores │
├────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┤
 scenario find routes: ['ego.rou.xml']
pybullet build time: Oct  8 2020 00:10:46
 Retrying in 0.05 seconds
pybullet build time: Oct  8 2020 00:10:46
│                0/1 │               6.82 │                500 │              68.23 │ straight_change-la │        ego.rou.xml │ 284442438557984830 │                    │
╰────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────╯
In /home/chendong/codes/github/SMARTS/smarts/env/hiway_env.py close
self smarts is not None
self.teardown start
self.teardown end
self._envision start
WARNING:Client:Unable to connect to Envision   [wait for one minute and display this line, then block several minutes]

**Comment by charleschen6** [comment]
resolve: modify zoo/evaluation/egoless_example.py  set headless as True will clos env success!
```python
env = gym.make(
        "smarts.env:hiway-v0",
        scenarios=args.scenarios,
        agent_specs={},
        headless=True,
        visdom=False,
        timestep_sec=0.1,
        endless_traffic=False,
        sumo_headless=False,
        envision_record_data_replay_path=data_replay_path,
    )
```

**Comment by charleschen6** [comment]
finally resolve:
modify envision/client.py
```python    
  def teardown(self):
        self._state_queue.put(Client.QueueDone())
        self._logging_queue.put(Client.QueueDone())
        if self._thread:
            print("in client.py, before self._thread.join()")
            self._thread.join(timeout=1)       #with timeout
            self._thread = None
```

**Comment by Gamenot** [comment]
@liamchzh It looks like we should at least put a `log.debug()` in the `on_error()` because the message there is potentially misleading.
