### ISSUE TITLE
genarate traffic

### ISSUE THREAD

**Issue by zyk516** [huawei-noah/SMARTS#1282]
## **BUG REPORT**
**High Level Description**
I created a two-way road.When I generated traffic, vehicles was generated only in one way.
The code to generate traffic:
`import random
from pathlib import Path
from smarts.sstudio import gen_scenario
from smarts.sstudio import types as t
import random
from pathlib import Path
from smarts.sstudio import gen_scenario
from smarts.sstudio import types as t
impatient_car = t.TrafficActor(
    name="car",
    speed=t.Distribution(sigma=0.2, mean=1.0),
    lane_changing_model=t.LaneChangingModel(impatience=1, cooperative=0.25),
    junction_model=t.JunctionModel(
        drive_after_red_time=1.5, drive_after_yellow_time=1.0, impatience=1.0
    ),
)
traffic = t.Traffic(
    flows=[
        t.Flow(
            route=t.RandomRoute(),
            begin=0,
            end=2 * 24 * 60 * 60,
            rate=600,
            # rate=1200,
            # actors={t.TrafficActor(name="car", vehicle_type='passenger'): 1},
            actors={impatient_car: 1}
        )
        for i in range(5)
        #  ("passenger", "bus", "coach", "truck", "trailer")"""
    ]
)

missions = [
    t.Mission(t.Route(begin=("gneE19", 0, 5), end=("gneE19", 1, 'random')))
]
gen_scenario(
    t.Scenario(
        traffic={"basic": traffic},
        ego_missions=missions
    ),
    output_dir=Path(__file__).parent,
)`
One part of the final route file:
<vehicle id="car-flow-random-route-25317a9f-4004238474360101266--0-0.0" type="actor-car-3649280275030852550" depart="0.00" departLane="2" departPos="78.92" departSpeed="max" arrivalLane="0" arrivalPos="8.08">
        <route edges="-gneE7 -gneE8 -gneE12 -gneE14 -gneE19 -gneE18 -gneE17 -gneE1 -gneE2 -gneE3"/>
    </vehicle>
    <vehicle id="car-flow-random-route-7523676d-4004238474360101266--4-0.0" type="actor-car-3649280275030852550" depart="0.00" departLane="0" departPos="28.08" departSpeed="max" arrivalLane="2" arrivalPos="4.70">
        <route edges="-gneE4 -gneE5 -gneE6 -gneE7 -gneE8 -gneE12 -gneE14 -gneE19 -gneE18 -gneE17"/>
    </vehicle>
    <vehicle id="car-flow-random-route-a476ea89-4004238474360101266--3-0.0" type="actor-car-3649280275030852550" depart="0.00" departLane="1" departPos="52.00" departSpeed="max" arrivalLane="1" arrivalPos="1.92">
        <route edges="-gneE7 -gneE8 -gneE12 -gneE14 -gneE19 -gneE18 -gneE17 -gneE1 -gneE2 -gneE3"/>
    </vehicle>
    <vehicle id="car-flow-random-route-c3dc3dfe-4004238474360101266--1-0.0" type="actor-car-3649280275030852550" depart="0.00" departLane="2" departPos="16.23" departSpeed="max" arrivalLane="2" arrivalPos="74.66">
        <route edges="-gneE8 -gneE12 -gneE14 -gneE19 -gneE18 -gneE17 -gneE1 -gneE2 -gneE3 -gneE4"/>
    </vehicle>
The edge in edges both had a '-', means they were in same way.

**SMARTS version**
[e.g. 0.4.18]
**System information**
 
- Operating system & Environment [Please note if using Docker]:ubuntu
- SUMO version:1.5.0

**Comment by Adaickalavan** [comment]
Closed due to stale issue. Please create a new issue if problem persists or for other questions.
