### ISSUE TITLE
`ULTRA` feature highlighting examples

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#1284]
## Description of the Issue
ULTRA will need a clear demonstration of why is it useful as a baseline.

## Proposed Solution
Create an ULTRA specific example that can function as a minimal baseline to demonstrate an initial solution. This should be coupled with a description of how it implements the features of its paper.

**Comment by Adaickalavan** [comment]
ULTRA is currently out of maintenance.
