### ISSUE TITLE
Divide examples into `gym`, `rllib.MultiAgentEnv`, and `SMARTS`

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#1286]
## Description of the Issue
There is no clear deliminator line between the different example issues.

## Proposed Solution
Split the examples into clearly defined groups `gym` and `SMARTS`.

**Comment by Adaickalavan** [comment]
Contents of our current `examples` folder may be categorised as follows:
Please fill in the blanks (i.e., `?`)

| Content | Classification |
| --------- | -------------- |
| driving_in_traffic | Reinforcement Learning - model based |
| replay | ? |
| rllib | RLLib |
| tests | Test |
| tools | Utility |
| __init__.py | Utility |
| argument_parser.py | Utility |
| dynamic_history_vehicles_replacement.py | ? |
| ego_open_agent.py | ? |
| | |
| | |
| | |
| | |

**Comment by Adaickalavan** [comment]
Examples have since been reorganised.
