### ISSUE TITLE
Encapsulate scenario build for GYM environment examples

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#1291]
## Description of the issue
Scenario generation is a potential point of fault with a standard use of the gym interface. `gym` related environments are expected to return a functioning episode on reset. 

## Proposed solution
Automatically build the necessary scenario before run when using a GYM environment.

**Comment by Adaickalavan** [comment]
Scenario builds are automatic and inbuilt in all gymnasium environments such as `driving-smarts-v2022`, `driving-smarts-v2023`, and `platoon-v0`, except the base environment of `hiway-v1`.
