### ISSUE TITLE
Make `scikit` Optional

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#1305]
**Description of the Problem**
`scipy` packages `scikit-learn` and `scikit-image` are large packages.

**Proposed solution**
Remove the need for these dependencies.

**Comment by RutvikGupta** [comment]
Something I came across which can be a nice replacement for the `sklearn.neighbors.KDTree` usage in `smarts/core/lanepoints.py`.: https://pypi.org/project/kdtree/.
Its a very light package and has no dependencies:
![image](https://user-images.githubusercontent.com/47334253/156819586-ce0b514a-a932-4a14-b006-dbf7cf7dc614.png)

Much better than writing our own KD Tree. Its implementation: https://github.com/stefankoegl/kdtree/blob/master/kdtree.py
