### ISSUE TITLE
Make SUMO Optional

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#1308]
**Description of the Problem**
SUMO is a major sized dependency that can complicate installation.

**Proposed Solution**
Move this dependency to an optional `[sumo]` extra. This is blocked on scenario studio revamp and having an alternative traffic simulation.

**Comment by saulfield** [comment]
This will be a part of #1981. The alternative traffic simulation has been implemented already -- now we just need to make a `[sumo]` extra.
