### ISSUE TITLE
Does Tensorflow 2.4.0 can't install properly?

### ISSUE THREAD

**Issue by NOTGOOOOD** [huawei-noah/SMARTS#1314]
I have installed all the required pkg respectively,then I use the command 'make test',but it doesn't work.It says, 'Command not found:make:scl'
![图片](https://user-images.githubusercontent.com/30164440/156573195-fdec5e42-6d22-478a-bdc4-c4e85d9a0bf2.png)

And I use 'pip install -e .[train]' for a check, I find a tip of error in the end. 
![图片](https://user-images.githubusercontent.com/30164440/156572988-51fd60bb-73bd-40f5-8c0f-8c3dc35eb43d.png)

**Comment by Gamenot** [comment]
Hello @Aflexiblebox, thank you for your questions.

It looks like:
1. SMARTS somehow did not install correctly.
  - The command `which scl` should give a file location in your virtual environment directory.
  - `pip freeze | grep smarts` should give the following if it was installed with `-e`:
    - `-e git+https://github.com/huawei-noah/SMARTS.git@f345c718f8f0256046c89b49f9ff8288e4aa0de8#egg=smarts`
2. There are two likely issues here:
  - The `pip` version is too old and you may want to run `pip install --update pip`
  - Your internet connection is limited so it was not able to download and install `tensorflow` before timeout. You can get around this by using `pip install` with `--default-timeout=1000`. If that is not enough you will want to cache or manually manage large dependencies.
    - Additional information about pip cache: https://pip.pypa.io/en/stable/topics/caching/
    - Additional information on managing local packages: https://pip.pypa.io/en/stable/user_guide/#installing-from-local-packages

**Comment by Aflexiblebox** [comment]
> Hello @Aflexiblebox, thank you for your questions.
> 
> It looks like:
> 
>     1. SMARTS somehow did not install correctly.
> 
> 
>     * The command `which scl` should give a file location in your virtual environment directory.
> 
>     * `pip freeze | grep smarts` should give the following if it was installed with `-e`:
>       
>       * `-e git+https://github.com/huawei-noah/SMARTS.git@f345c718f8f0256046c89b49f9ff8288e4aa0de8#egg=smarts`
> 
> 
>     2. There are two likely issues here:
> 
> 
>     * The `pip` version is too old and you may want to run `pip install --update pip`
> 
>     * Your internet connection is limited so it was not able to download and install `tensorflow` before timeout. You can get around this by using `pip install` with `--default-timeout=1000`. If that is not enough you will want to cache or manually manage large dependencies.
>       
>       * Additional information about pip cache: https://pip.pypa.io/en/stable/topics/caching/
>       * Additional information on managing local packages: https://pip.pypa.io/en/stable/user_guide/#installing-from-local-packages

> 
Thank you very much for your answer! 
As you saying that, I can't install SMARTS correctly because my internet is very slow so that I can't  run this command `pip install -e '.[train]'`,and I use the domestic mirrors by the `pip install -i` command to install the package respectively.Actually,I am a studens study in Chinese, and don't have the VPN,sometimes even I can't connect to the github.
I really appreciate your answer, I will try it again.

**Comment by Gamenot** [comment]
@Aflexiblebox, Sorry for the late reply, it would appear like the directory you are attempting to build needs to have its permissions changed.

`smarts.egg-info` would be built in the `SMARTS` directory. 

I could suggest something like `sudo chmod 777 ~/repo/SMARTS`.
