### ISSUE TITLE
Failed to run rllib training

### ISSUE THREAD

**Issue by KID0031** [huawei-noah/SMARTS#1320]
## **BUG REPORT**
**High Level Description**
I tried to run rllib training using command `python examples/rllib/rllib.py scenario/loop` but it occurs error and I didn't modify related files. Is there any misoperation?
**SMARTS version**
[0.5.1]
**Error logs and screenshots**
[Text or screenshots (preferably text)]
![image](https://user-images.githubusercontent.com/51467434/156972598-e019aa15-dc4a-4378-835a-360604dd3efb.png)

**Comment by Gamenot** [comment]
Hello @KID0031, thank you for the report. Sorry for the late reply.

I am unable to diagnose what is wrong here without more information. I would need at least the version of `python` and some information about the currently installed `pip` packages (i.e. `pip freeze`).
