### ISSUE TITLE
Can I add new vehicle models to the visualization web page?

### ISSUE THREAD

**Issue by Sud0x67** [huawei-noah/SMARTS#1329]
Hi, guys, I am working with SMARTS and studying in RL. I want to add some new vehicle models to the visualization page. I have a ".glb" format file. However , when I add it to the project, it didn't move on the page. So, are there any directions for me to add new vehicle models?

**Comment by Gamenot** [comment]
Hello @Sud0x67, thank you for asking the question. I do not think I fully I understand your intention here:

Are you trying to replace currently existing models with new models or create entirely new vehicle models?

**Comment by Sud0x67** [comment]
Dear @Gamenot, thanks for your reply. I repaced the "muscle_car.glb" by my own vehicle model and named my model with the same name initially, but my model doesn't move on the scene.  Then I used another model with a component using id "body". it seems to work now. I guess that the first model I added is too complex so that "babylonjs" hasn't loaded it correctly.
