### ISSUE TITLE
Add S-L coordinates support

### ISSUE THREAD

**Issue by qianyi-sun** [huawei-noah/SMARTS#1364]
Currently, SMARTS only supports x,y coordinate system. The requirements are the following:
1) Add a feature for converting the x,y coordinate system to ego-centric coordinate system in the current state representation. #1378
2) Convert the existing state representation into the S-L coordinates, or provide an API for reading the information of waypoints (the centerline of each lane).

Question(s) to be discussed:

- For the API in 2, should it be an open-source API, or a private API?
- Priority and timeline?

**Comment by Gamenot** [comment]
It is possible to add Frenet coordinates to ego observations. But, I am not confident that it will be enough to suit the requirements if we cannot directly query the underlying road-network that the coordinate system references.

With that said, we already have the underlying representation we would need to expose this information.

**Comment by qianyi-sun** [comment]
Just confirmed with Wang, 
- The priority of request 1 is higher than 2, since seems like 1 is relatively easier to do. 
- For 2, if there is too much work to do, we might just do the 'or' part first.
- We can evaluate the need for open-sourcing the API, we do it if it's worth doing.

**Comment by Gamenot** [comment]
@qianyi-sun OK, we can do the first part. Please spin out a new issue for it and we can assign it immediately.

**Comment by sah-huawei** [comment]
PR #1411 has now been merged into `develop`.  I think that covers everything here that _isn't_ part of issue #1378, so we can close this one.
