### ISSUE TITLE
Inconsistency in Nearest Waypoint Heading

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#137]
The first waypoint on the observation's `waypoint_paths` has a 50/50 chance to be a waypoint behind the vehicle which means some noise in relying on the nearest waypoint for future heading.

**Comment by liamchzh** [comment]
#143 might solve this issue.

**Comment by iman512003** [comment]
> #143 might solve this issue.

Thanks, #143 smooth the waypoints from the first one, i.e. it does not modify the position of the first waypoint.
