### ISSUE TITLE
Unclosed socket (SUMO)

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#1373]
## **BUG REPORT**
**High Level Description**
A line in the `traci` utilities outputs a resource warning about an unclosed socket causing it to appear in the notebook test diff.

**SMARTS version**
v0.6.0

**Previous associated issues**
N/A

**Steps to reproduce the bug**
This is hard to reproduce. However, it shows up in the CI often.

**Resulting and expected behaviour**
The warning should not be printed to stderr. The test should pass.

**Error logs and screenshots**
[Error logs](https://github.com/huawei-noah/SMARTS/runs/5854500836?check_suite_focus=true#step:5:329)
Potential fix of root issue: https://github.com/Gamenot/sumo/commit/bc6af8ff497413d2252795b2a9483db63c6a5fcf

**System information**
 
- Operating system & Environment [Please note if using Docker]:
Github actions
 
**Impact [If known]**
Causes CI to fail intermittently.

**Comment by Lenakeiz** [comment]
Hi @Gamenot I have the same exact problem as yours. Using Traci and getting the same output for unclosed connection in CI when performing even simple tests (opening sumo, checking sumo is active process and closing).

Can you please describe how you solved it?

**Comment by Gamenot** [comment]
Hello @Lenakeiz. There is no outside fix currently. We suppress error output using a context manager that suppresses output by swapping out `stderr` and/or `stdout` into `/dev/null`:

https://github.com/huawei-noah/SMARTS/blob/b01547c0135b42aa3d3c1f83247f8bf1641a14f3/smarts/core/utils/logging.py#L75-L94

I also did some investigation and found [the source of the problem](https://github.com/Gamenot/sumo/commit/bc6af8ff497413d2252795b2a9483db63c6a5fcf). It cannot be handled because it is an unclosed `socket` object in the `Connection` initializer that escapes if it throws an exception. When I have the chance I will open a merge request against the SUMO repository.

**Comment by Lenakeiz** [comment]
@Gamenot thank you very much for your explanation. It is a really nice solution. I was thinking to handle manually traci connection retries by setting the `numretries = 0` and just discard any error that is not a socket error, but yours seems a much more refined solution. Thanks for pointing that out (and thank for submitting a potential fix to SUMO as well)

**Comment by Gamenot** [comment]
Resolved: https://github.com/eclipse/sumo/pull/10670
