### ISSUE TITLE
get a acyclic scenario iterator

### ISSUE THREAD

**Issue by YuechengLiu** [huawei-noah/SMARTS#1381]
### Feature request

we want to get a acyclic scenario iterator, just like this:

smarts.core.scenario.Scenario()
```python
@staticmethod
def scenario_variations(
    scenarios_or_scenarios_dirs: Sequence[str],
    agents_to_be_briefed: Sequence[str],
    shuffle_scenarios: bool=True,
    circular=True,
):
    scenario_roots = Scenario.get_scenario_list(scenarios_or_scenarios_dirs)
    
    if shuffle_scenarios:
        np.random.shuffle(scenario_roots)
    if circular:
        scenario_roots = cycle(scenario_roots)
    return Scenario.variations_for_all_scenario_roots(
        scenario_roots, agents_to_be_briefed, shuffle_scenarios
    )
```
The above changes have no impact on existing code logic.

**Comment by Gamenot** [comment]
@YuechengLiu Hello, thank you for the request. This should be quick for us to add. I have assigned it and it should be in the next version we put out Friday.

**Comment by Adaickalavan** [comment]
The recommended changes have been merged into the `develop` branch and it will be merged into the `master` branch in the next release.
