### ISSUE TITLE
Create competition environment for RL 

### ISSUE THREAD

**Issue by cz0204** [huawei-noah/SMARTS#1382]
Create environment that takes dx and dy (change of displacement in x and y coordinate) as action and generate ego-centric birds eye view image for observation.

**Comment by Gamenot** [comment]
@cz0204 I have added a base environment interface: https://github.com/huawei-noah/SMARTS/tree/tucker/comp_environment I will start filling it out tomorrow but it would be good to have input on it.

**Comment by Adaickalavan** [comment]
+ This can be achieved with the current NeurIPS2022 competition environment.
+ The env can be instantiated as `env=gym.make("smarts.env:multi-scenario-v0")` from the `comp-1` branch.
