### ISSUE TITLE
Fail to visualize the lanes of NGSIM-US101 using Envision

### ISSUE THREAD

**Issue by YuechengLiu** [huawei-noah/SMARTS#1397]
## **BUG REPORT**
**Fail to visualize the lanes of NGSIM-US101 using envsion**

**SMARTS version**
[e.g. 0.6.1rc1]

**Steps to reproduce the bug**
1. modify `<PATH_OF_NGSIM_US101_SCENARIO>` in the following python script.
2. run the script.
3. open `localhost:8081` on browser.
```python
import os
import sys
import inspect
import signal
from subprocess import Popen

currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parentdir = os.path.dirname(currentdir)
sys.path.insert(0, parentdir)
print(sys.path)

from smarts.core.smarts import SMARTS
from smarts.core.scenario import Scenario
from envision.client import Client as Envision


def experiment(scenario_path):
    traffic_name = "us101_0750-0805"
    scenario_name = "ngsim_us101"

    scenario_iterator = Scenario.scenario_variations(
        [scenario_path], list([]), shuffle_scenarios=False, circular=False
    )  # scenarios with different traffic histories.
    scenario = None
    for _scenario in scenario_iterator:
        if _scenario._traffic_history.name == traffic_name:
            scenario = _scenario
            break
    assert scenario is not None

    envision_client = Envision(
        sim_name=f"{scenario_name}_{traffic_name}",
        output_dir="record_data_replay_path",
        headless=False,
    )
    smarts = SMARTS(
        agent_interfaces={},
        traffic_sim=None,
        envision=envision_client,
    )
    smarts.reset(scenario)
    smarts.step({})
    while True:
        smarts.step({})
        current_vehicles = smarts.vehicle_index.social_vehicle_ids()
        if len(current_vehicles) == 0:
            break


if __name__ == "__main__":
    scenario_path = <PATH_OF_NGSIM_US101_SCENARIO>
    # Arguments
    envision_proc = Popen(
        f"scl envision start -s {scenario_path} -p 8081",
        shell=True,
        preexec_fn=os.setsid,
    )

    try:
        experiment(scenario_path)
    except Exception as e:
        os.killpg(os.getpgid(envision_proc.pid), signal.SIGTERM)
        envision_proc.wait()
        raise e

    os.killpg(os.getpgid(envision_proc.pid), signal.SIGTERM)
    envision_proc.wait()
```

**Error logs and screenshots**
 
![image](https://user-images.githubusercontent.com/52879090/163911288-8ba1794f-e2bf-46b3-8e9e-fec1c7bb2ae2.png)
Lane lines are not displayed

**System information**
 
- Operating system & Environment [Please note if using Docker]: ubuntu16.04
- Number of system cores available: 16
- Python version [Please note if using Jupyter] 3.7
- Python packages [e.g. from `pip freeze`]
- SUMO version
- Date when bug occurred
 
**Impact [If known]**

**Comment by Gamenot** [comment]
@qianyi-sun and I looked at this. We found that the envision server requires a list of directories, as was done here. 

```python
# e.g. `scl envision start --scenarios "./scenarios` --envision_port 8081
envision_proc = Popen(
    f"scl envision start -s {scenario_path} -p 8081",
    shell=True,
    preexec_fn=os.setsid,
)
```

@RutvikGupta Please check if this works when targeting a specific scenario, and an absolute path, rather than a relative directory of scenarios (e.g., `/usr/foo/repos/SMARTS/scenarios/loop`.)

**Comment by RutvikGupta** [comment]
> ```python
> scl envision start -s {scenario_path} -p 8081
> ```

So I tried this with a specific scenario, and an absolute path, and in both the cases it works.

Only case when this doesn't work when the `scenario_path` folder you mention when running `envision` server does not have the scenario you are running the example with. Eg: If i pass `scenarios/intersection` in `scl envision start -s {scenario_path} -p 8081` and run the command, `python examples/single_agent.py scenarios/loop`, I won't see any map in envision which make sense.

**Comment by RutvikGupta** [comment]
Also if you are trying to use the `scl run` command with --envision option, then you need to have the scenario you are running in `./scenarios` folder since its envision `-s` option defaults to that folder.

**Comment by RutvikGupta** [comment]
Also from the script snippet above, the user doesn't seem to be building the scenario `ngsim/us101`. So it could be possible that they never created the `.glb` file for the scenario and envision is not able to find that in the scenario path.
@YuechengLiu, can u please make sure to run `scl scenario build --clean <PATH/TO/NGSIM/US101>` command at your source level  before running the above script?

**Comment by YuechengLiu** [comment]
> Also from the script snippet above, the user doesn't seem to be building the scenario `ngsim/us101`. So it could be possible that they never created the `.glb` file for the scenario and envision is not able to find that in the scenario path. @YuechengLiu, can u please make sure to run `scl scenario build --clean <PATH/TO/NGSIM/US101>` command at your source level before running the above script?

@RutvikGupta 

Thanks for your time! I find that my `map.glb` file is missing. And now it works!
