### ISSUE TITLE
There is no map.glb in benchmark/scenarios folder

### ISSUE THREAD

**Issue by rsuwa** [huawei-noah/SMARTS#140]
When I run `python run.py scenarios/intersections/4lane -f agents/maddpg/baseline-lane-control.yaml`, I got the following error.

```bash
OSError: Could not load model file(s): ['/path/to/SMARTS/benchmark/scenarios/intersections/4lane/map.glb']
```
I suspect this error is due to the fact that the map.glb does not exist in the following folder.
https://github.com/huawei-noah/SMARTS/tree/master/benchmark/scenarios/intersections/4lane

**Comment by davidrusu** [comment]
Hi @rsuwa, You'll need to build the scenario before using it.

You can use `scl scenario build-all ./scenarios/` to build all scenarios under the `scenarios/` directory. Or if you'd like to just build a single scenario:

```
scl scenario build ./scenarios/intersections/4lane
```

**Comment by rsuwa** [comment]
Since I have already run `make test`, I should have built the scenario already.
Just to be sure, I run `scl scenario build-all ./scenarios` again and same error occurs.

**Comment by davidrusu** [comment]
No problem :+1:
