### ISSUE TITLE
Missing/skipping data during conversion for ngsim us101

### ISSUE THREAD

**Issue by qianyi-sun** [huawei-noah/SMARTS#1402]
## **BUG REPORT**
**High Level Description**
When using SMARTS to convert NGSIM raw data (.txt files) to .shf files, for some `vehicle_id`s, corresponding `sim_time`s get skipped or missed, which leads to vehicles teleport in the visualization. 

Also, there is a total row number difference between the raw data and the `.shf` files.

**SMARTS version**
0.6.1 rc1

**Steps to reproduce the bug**
`scl scenario build --clean --allow-offset-map scenario/NGSIM/us101`

**Resulting and expected behaviour**
The `sim_time` for all vehicles should be continuous and the row number of data before/after the conversion should be the same. 

**Error logs and screenshots**
For example, the `vehicle_id=1936` in `us101_0820-0835.shf`, the `sim_time` jumps from 913.7 to 917.2 (see the line 14,15 in screenshot below).
![image](https://user-images.githubusercontent.com/59240680/164753490-ad564848-f92d-454e-971e-3a551eecad34.png)

Also with same `vehicle_id=1936`, the total row number of it in `us101_0820-0835.shf` is 520, given that in the raw data, the row number of it is 789.

**Comment by qianyi-sun** [comment]
@YuechengLiu We use this issue to record the bug that you reported to us. Please feel free to edit the description for improvement if necessary. Thanks!

**Comment by turix2** [comment]
In general, "gaps" in a vehicle's trajectory can occur if it drives off of the mapped area for some reason.  However, that's not occurring in this case, so this was a bug.  I have a PR that I'm just wrapping up that fixes this.

**Comment by sah-huawei** [comment]
I think this is fixed by PR #1403.  Please reopen this issue if it re-occurs though.
