### ISSUE TITLE
make the competition environment a package

### ISSUE THREAD

**Issue by cz0204** [huawei-noah/SMARTS#1420]
make the competition environment a package

**Comment by Adaickalavan** [comment]
If @qianyi-sun implements the scenarios in #1418 by following the `examples/multi_intersection.py` example in commit `b3098027e5d7fd04c12dd8d51fab4a6c9fc24a5a`, then the users can simply install the SMARTS package and instantiate the competition environment, for example `env = gym.make("smarts.env:merge-v0")`.

**Comment by Adaickalavan** [comment]
+ We can install SMARTS package as 
    ```bash
    $ pip install "smarts[camera-obs] @ git+https://github.com/huawei-noah/SMARTS.git@comp-1"
    ```
+ The NeurIPS2022 competition environment can be instantiated as `env=gym.make("smarts.env:multi-scenario-v0")` from the `comp-1` branch.
