### ISSUE TITLE
Record Competition environment Obsevation&Reward&Score

### ISSUE THREAD

**Issue by cz0204** [huawei-noah/SMARTS#1421]
add in new feature in the competition environment such that we can record information from single agent.

**Comment by cz0204** [comment]
Add in the functionality that can record observation/reward/score with specific vehicle ID.

**Comment by cz0204** [comment]
The idea for this is to do offline learning with data provided from smarts. So the reward may not be included in the record, the contestants has to calculate reward w.r.t observation. For example, we construct a traffic following scenarios in SMARTS (using sumo traffic following model) with vehicle 1 (in front) and vehicle 2 (follow from behind). Then this functionality can provide observation for both vehicles. The contestant will design their own reward based on the observations and design a dataset and train an agent using offline RL.

**Comment by Adaickalavan** [comment]
To create offline datasets from Waymo scenarios, use https://github.com/huawei-noah/SMARTS/tree/comp-1/smarts/waymo  .
