### ISSUE TITLE
make sanity-test

### ISSUE THREAD

**Issue by unssww** [huawei-noah/SMARTS#1438]
when make sanity-test, the error is  scl: No such file or directory.

`(.venv) (base) songsong@songsongdeMacBook-Pro SMARTS % make sanity-test
scl scenario build-all scenarios
make: scl: No such file or directory
make: *** [build-all-scenarios] Error 1
(.venv) (base) songsong@songsongdeMacBook-Pro SMARTS % 
'

**Comment by Adaickalavan** [comment]
Hi @unssww,

The `make sanity-test` following these commands appear to run fine now.
```bash
$ cd <path>/SMARTS
$ git checkout develop
# For NeurIPS2022 Driving SMARTS competition, checkout the comp-1 branch instead.
# $ git checkout comp-1
$ git pull
$ python3.8 -m venv ./.venv
$ source ./.venv/bin/activate
$ pip install --upgrade pip
$ pip install -e .[camera-obs,test]
$ make sanity-test
```

We hope the above addresses your question and thus this issue is being closed. Please feel free to reopen this issue if your problem persists or open a new issue for other questions.
