### ISSUE TITLE
`ModuleNotFoundError("No module named 'waymo_open_dataset'")` when building NGSIM data replay scenarios

### ISSUE THREAD

**Issue by qianyi-sun** [huawei-noah/SMARTS#1449]
When running `scl scenario build --clean <path/to/scenario>` (e.g., `scl scenario build --clean scenarios/NGSIM/us101`), a traceback occurs as follow:
![image](https://user-images.githubusercontent.com/59240680/171044669-e2f2ff73-f040-4da3-a2aa-bf7771407658.png)

This traceback doesn't block the building process (i.e., the `.shf` file can be successfully made and works just fine), it's just annoying that a waymo-related traceback appears in a NGSIM-related work.

To reproduce this, please check `scenarios/NGSIM/README.md`, or ask @qianyi-sun

**Comment by saulfield** [comment]
This should not be an issue anymore since we've eliminated the `waymo_open_dataset` package as a dependency.
