### ISSUE TITLE
Ego-centric information from all sumo vehicles

### ISSUE THREAD

**Issue by qianyi-sun** [huawei-noah/SMARTS#1452]
Possible solution could be putting sensors on sumo vehicles and record the observations of them (according to Tucker). 

We can provide one example that records ego-centric information from only one sumo vehicle for @YuechengLiu first, then maybe we record all of them later.

**Comment by YuechengLiu** [comment]
I realize that in this example https://github.com/huawei-noah/SMARTS/blob/master/examples/observation_collection_for_imitation_learning.py, it has been able to get observations for the `sumo-controlled` vehicles. Thanks!

**Comment by qianyi-sun** [comment]
Confirmed with @YuechengLiu , the current `observation_collection_for_imitation_learning.py` has already satisfied their use case, closing this issue now
