### ISSUE TITLE
`Warning: vehicle out of lane` when vehicles are visually on-road in ngsim lankershim simulation

### ISSUE THREAD

**Issue by qianyi-sun** [huawei-noah/SMARTS#1456]
when headlessly testing the map for lankershim data reply, there are several warnings saying `history-vehicle-<id>, skipped attaching sensors`.

 In `lankershim_0830am-0845am`, there are 3 vehicles which are 659, 1287 and 1349 and in `lankershim_0830am-0845am`, they are 39, 248, 364, 960, 1121 and 1151. I've checked all 9 vehicles visually and by querying the coordinates of those vehicles using SQL, they show up in the _intersections_ (around the blue dots in the screenshot), which should be on the map without warnings. 
<img width="679" alt="lanker" src="https://user-images.githubusercontent.com/59240680/171667028-c3fca8b6-12f7-49f6-bbc2-3bbc34b9a77c.png">

Please find attached zip file for the map and the shf files which only contain the related 9 vehicles. Also the sumo version I'm using is 1.13.0. Thanks! 
[lanker.zip](https://github.com/huawei-noah/SMARTS/files/8825348/lanker.zip)

**Comment by sah-huawei** [comment]
This was due to the sumo map files not including the internal links (connections) within the junctions.  We enabled them via selecting "Processing" -> "Options", then choosing the "Junctions" section, and then unchecking the "no-internal-links" checkbox.
