### ISSUE TITLE
No module named smarts.zoo.agent_spec

### ISSUE THREAD

**Issue by hoaklee** [huawei-noah/SMARTS#1463]
Hi, I have successfully installed smarts and ultra, when I am running ultra experiments using the following code:

python ultra/scenarios/interface.py generate --task 1 --level easy

It returns the error like below:

pybullet build time: Oct  8 2020 00:10:46
Traceback (most recent call last):
  File "ultra/scenarios/interface.py", line 36, in <module>
    from smarts.zoo.agent_spec import AgentSpec
ModuleNotFoundError: No module named 'smarts.zoo.agent_spec'

Do you have any idea what should I do with this error?(I can import smarts.zoo.manager and other script in the same folder)

**Comment by sah-huawei** [comment]
Hello @hoaklee.  Could you please let us know what versions of Ultra and Smarts you have installed?  Thanks!

**Comment by Adaickalavan** [comment]
Closed due to stale issue.
