### ISSUE TITLE
Failures on benchmarks

### ISSUE THREAD

**Issue by rsuwa** [huawei-noah/SMARTS#151]
The following error occurs.

```bash
ValueError: ('Observation outside expected value range', Dict(distance_to_center:Box(1,), goal_relative_pos:Box(2,), heading_errors:Box(20,), neighbor:Box(40,), speed:Box(1,), steering:Box(1,)), {'distance_to_center': array([-1892.29332304]), 'goal_relative_pos': array([ 15.80750083, -15.13691376]), 'heading_errors': array([0.04683615, 0.04683615, 0.04683615, 0.04683615, 0.04683615,
       0.04683615, 0.04683615, 0.04683615, 0.04683615, 0.04683615,
       0.04683615, 0.04683615, 0.04683615, 0.04683615, 0.04683615,
       0.04683615, 0.04683615, 0.04683615, 0.04683615, 0.04683615]), 'neighbor': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.]), 'speed': array([11.20682789]), 'steering': array([-0.45977011])})
```

**Command**
`python run.py scenarios/intersections/4lane -f agents/maddpg/baseline-lane-control.yaml`

**Environment**
OS: Ubuntu 18.04.5 LTS
CPU: Ryzen 5 3600x
GPU: GeForce RTX 2070

Python 3.7.5
CUDA 10.0

pip list
```bash
tensorflow-estimator              1.15.1
tensorflow-gpu                    1.15.0
tensorflow-probability            0.8.0
ray                               1.0.0
```

**Comment by rsuwa** [comment]
I've tried it without a GPU and I get the same problem, so it may be a bug caused by a recent change.

**Comment by rsuwa** [comment]
I tried to rebuild it and got the same error.

**Comment by davidrusu** [comment]
Hi Ryota, I've asked @KornbergFresnel and @mg2015started to take a look, hopefully they can resolve the issue.

**Comment by KornbergFresnel** [comment]
I've tried this execution with the same python environment as @rsuwa mentioned, but cannot produce such an error. How about your results? @mg2015started

**Comment by rsuwa** [comment]
I tried again and for some reason the above error no longer occurs.
Thank you for your response.
