### ISSUE TITLE
Offroad event is not triggered for ego and social agents

### ISSUE THREAD

**Issue by aurorahcx** [huawei-noah/SMARTS#153]
![rQFuRW0E77](https://user-images.githubusercontent.com/57057376/98746347-4d547280-2383-11eb-875e-0564e08ea6d3.gif)
![Screenshot from 2020-11-10 18-46-08](https://user-images.githubusercontent.com/57057376/98747425-76760280-2385-11eb-9df5-41bcc43d29b8.png)

**Comment by liamchzh** [comment]
https://github.com/huawei-noah/SMARTS/commit/7fbbdb200d6a94a1b5b2c4879c020dac98ec9742#r44060735

**Comment by aurorahcx** [comment]
> We may introduced this issue in [7fbbdb2#r44060735](https://github.com/huawei-noah/SMARTS/commit/7fbbdb200d6a94a1b5b2c4879c020dac98ec9742#r44060735)

Actually, it occurs on this commit: https://github.com/huawei-noah/SMARTS/commit/75cb7be91e019547d680284cef669ff756a69923
