### ISSUE TITLE
Ensure competition environment integrity.

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#1540]
Ensure that SMARTS `Observation` class does not throw a recursion error on `copy.deepcopy(..)`.

## Context
`deepcopy` was used to prevent external users from modifying some of the `infos` objects later using additional env wrappers.   

How does `RecursionError` occur and would a shallow copy be a sufficient tamper protection here?

_Originally posted by @Adaickalavan in https://github.com/huawei-noah/SMARTS/pull/1537#discussion_r934061725_

**Comment by Adaickalavan** [comment]
Metrics module has been revamped and this issue is not applicable anymore.
