### ISSUE TITLE
Former HistroyTrafficProvider remains in next smarts env

### ISSUE THREAD

**Issue by CyberSY** [huawei-noah/SMARTS#1542]
## **BUG REPORT**
**High Level Description**
When I try to initialize second smarts env in one process, the HistoryTrafficProvider from the first smarts env is not removed (even with smarts.destroy()) and will cause vehicles disjoint which makes second smarts env failed.

**SMARTS version**
develop branch

**Steps to reproduce the bug**
Just create one more smarts env in https://github.com/huawei-noah/SMARTS/blob/develop/examples/traffic_histories_vehicle_replacement.py and use it to do rest task

**Resulting and expected behaviour**
HistroyTrafficProvider should be removed when smarts env be destroyed

**Error logs and screenshots**
the normal providers should be like:

> provider num:5
[<smarts.core.agents_provider.AgentPhysicsProvider object at 0x7f44a4318c90>, <smarts.core.agents_provider.DirectControlProvider object at 0x7f44a4318f10>, <smarts.core.agents_provider.MotionPlannerProvider object at 0x7f44a4318fd0>, <smarts.core.agents_provider.TrajectoryInterpolationProvider object at 0x7f44a43300d0>, <smarts.core.traffic_history_provider.TrafficHistoryProvider object at 0x7f95ab69b4d0>]

However, if I then initialize two more smarts env and make sure the first two smarts env are destroyed, the providers of the third env also included ex-provider.

> provider num:7
[<smarts.core.agents_provider.AgentPhysicsProvider object at 0x7f95a90fe390>, <smarts.core.agents_provider.DirectControlProvider object at 0x7f95a90fe090>, <smarts.core.agents_provider.MotionPlannerProvid
er object at 0x7f95a90e4ed0>, <smarts.core.agents_provider.TrajectoryInterpolationProvider object at 0x7f95a90e4050>, <smarts.core.traffic_history_provider.TrafficHistoryProvider object at 0x7f95ab69b4d0>
, <smarts.core.traffic_history_provider.TrafficHistoryProvider object at 0x7f95a9118690>, <smarts.core.traffic_history_provider.TrafficHistoryProvider object at 0x7f95a90e4c10>]

The disjoint make ego-agent get done unproperly, the collision event show that it collide with its history-vehicle version.

**Comment by Gamenot** [comment]
Hello @CyberSY, I have made a fix for the likely issue: could you try out https://github.com/huawei-noah/SMARTS/pull/1544 or `git cherry-pick 2d526bd`?

**Comment by CyberSY** [comment]
> Hello @CyberSY, I have made a fix for the likely issue: could you try out #1544 or `git cherry-pick 2d526bd`?

@Gamenot It works! Thanks for the quick reply.

**Comment by Gamenot** [comment]
Fix is merged.
