### ISSUE TITLE
Design consideration of mapping mission to agent

### ISSUE THREAD

**Issue by AisenGinn** [huawei-noah/SMARTS#1546]
**High Level Description**
Currently missions in scenario are mapped based on an order to agents in example files. I tried to map the mission directly to the agents using a mission_name, which need a visualization of relation of agent, actor, actor selector to missions.

**Problems**
[Describe in detail the problems you are facing]
I am considering to add a Optional mission name list in AgentInterface that contains all missions that the agent should do. And adding a optional mission name for each actor in order to map the actor with specific missions. The mission name of the actor must in the mission name list of its agent, and different actors can perform same mission. I am not sure whether the missions should assign to Agent or the directly to the actor, and I am not sure the relation of agent, actor, actor selector to missions.

**Comment by Gamenot** [comment]
This has been associated with #1859
