### ISSUE TITLE
FAILED smarts/env/tests/test_social_agent.py::test_social_agents

### ISSUE THREAD

**Issue by JiyuanTHU** [huawei-noah/SMARTS#1560]
**High Level Description**
[make sanity-test]

**Desired SMARTS version**
[e.g. 0.6.1]

**Operating System**
[ ubuntu 20.04]

**Problems**
when I run 'make sanity-test', the test_social_agent.py failed with
[gw0] [ 14%] PASSED smarts/core/tests/test_python_version.py::test_python_version 
smarts/core/tests/test_smarts.py::test_smarts_doesnt_leak_tasks_after_reset 
[gw2] [ 28%] PASSED smarts/core/tests/test_dynamics_backend.py::test_set_pose 
smarts/env/tests/test_social_agent.py::test_social_agents 
[gw1] [ 42%] PASSED smarts/core/tests/test_sumo_version.py::test_sumo_version 
examples/tests/test_examples.py::test_examples[multi_agent] 
[gw2] [ 57%] FAILED smarts/env/tests/test_social_agent.py::test_social_agents 
[gw3] [ 71%] PASSED smarts/core/tests/test_sensors.py::test_waypoints_sensor 
[gw0] [ 85%] PASSED smarts/core/tests/test_smarts.py::test_smarts_doesnt_leak_tasks_after_reset 
[gw1] [100%] PASSED examples/tests/test_examples.py::test_examples[multi_agent] 

The whole output is attached as follows:
[gw2] linux -- Python 3.7.13 /home/jiyuan/anaconda3/envs/smarts/bin/python
self = <smarts.core.utils.class_factory.ClassRegister object at 0x7f44ffe31f90>
locator = 'scenarios.sumo.zoo_intersection.agent_prefabs:zoo-agent2-v0'

    def find_factory(self, locator):
        """Locates a factory given a locator."""
        self._raise_on_invalid_locator(locator)
    
        mod_name, name = locator.split(":", 1)
        # `name` could be simple name string (e.g. <open_agent-v0> or a URL
        try:
            # Import the module so that the agent may register it self in our self.index
>           module = importlib.import_module(mod_name)

smarts/core/utils/class_factory.py:114: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'scenarios.sumo.zoo_intersection.agent_prefabs', package = None

    def import_module(name, package=None):
        """Import a module.
    
        The 'package' argument is required when performing a relative import. It
        specifies the package to use as the anchor point from which to resolve the
        relative import to an absolute import.
    
        """
        level = 0
        if name.startswith('.'):
            if not package:
                msg = ("the 'package' argument is required to perform a relative "
                       "import for {!r}")
                raise TypeError(msg.format(name))
            for character in name:
                if character != '.':
                    break
                level += 1
>       return _bootstrap._gcd_import(name[level:], package, level)

../anaconda3/envs/smarts/lib/python3.7/importlib/__init__.py:127: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'scenarios.sumo.zoo_intersection.agent_prefabs', package = None
level = 0

>   ???

<frozen importlib._bootstrap>:1006: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'scenarios.sumo.zoo_intersection.agent_prefabs'
import_ = <function _gcd_import at 0x7f452d7b0b00>

>   ???

<frozen importlib._bootstrap>:983: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'scenarios.sumo.zoo_intersection.agent_prefabs'
import_ = <function _gcd_import at 0x7f452d7b0b00>

>   ???

<frozen importlib._bootstrap>:953: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

f = <function _gcd_import at 0x7f452d7b0b00>
args = ('scenarios.sumo.zoo_intersection',), kwds = {}

>   ???

<frozen importlib._bootstrap>:219: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'scenarios.sumo.zoo_intersection', package = None, level = 0

>   ???

<frozen importlib._bootstrap>:1006: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'scenarios.sumo.zoo_intersection'
import_ = <function _gcd_import at 0x7f452d7b0b00>

>   ???

<frozen importlib._bootstrap>:983: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'scenarios.sumo.zoo_intersection'
import_ = <function _gcd_import at 0x7f452d7b0b00>

>   ???

<frozen importlib._bootstrap>:953: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

f = <function _gcd_import at 0x7f452d7b0b00>, args = ('scenarios.sumo',)
kwds = {}

>   ???

<frozen importlib._bootstrap>:219: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'scenarios.sumo', package = None, level = 0

>   ???

<frozen importlib._bootstrap>:1006: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'scenarios.sumo', import_ = <function _gcd_import at 0x7f452d7b0b00>

>   ???

<frozen importlib._bootstrap>:983: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'scenarios.sumo', import_ = <function _gcd_import at 0x7f452d7b0b00>

>   ???

<frozen importlib._bootstrap>:953: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

f = <function _gcd_import at 0x7f452d7b0b00>, args = ('scenarios',), kwds = {}

>   ???

<frozen importlib._bootstrap>:219: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'scenarios', package = None, level = 0

>   ???

<frozen importlib._bootstrap>:1006: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'scenarios', import_ = <function _gcd_import at 0x7f452d7b0b00>

>   ???

<frozen importlib._bootstrap>:983: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'scenarios', import_ = <function _gcd_import at 0x7f452d7b0b00>

>   ???
E   ModuleNotFoundError: No module named 'scenarios'

<frozen importlib._bootstrap>:965: ModuleNotFoundError

During handling of the above exception, another exception occurred:

env = <smarts.env.hiway_env.HiWayEnv object at 0x7f44ff789e50>
agent_spec = AgentSpec(interface=AgentInterface(debug=False, event_configuration=EventConfiguration(not_moving_time=60, not_moving_..._adapter=<function AgentSpec.<lambda> at 0x7f44ffe904d0>, info_adapter=<function AgentSpec.<lambda> at 0x7f44ffe90290>)

    def test_social_agents(env, agent_spec):
        episode = None
        for episode in episodes(n=MAX_EPISODES):
            agent = agent_spec.build_agent()
>           observations = env.reset()

smarts/env/tests/test_social_agent.py:63: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
smarts/env/hiway_env.py:275: in reset
    scenario = next(self._scenarios_iterator)
smarts/core/scenario.py:206: in variations_for_all_scenario_roots
    for per_episode_social_agent_infos in social_agent_infos
smarts/core/scenario.py:206: in <listcomp>
    for per_episode_social_agent_infos in social_agent_infos
smarts/core/scenario.py:203: in <dictcomp>
    mission,
smarts/core/data_model.py:41: in to_agent_spec
    return make(locator=self.agent_locator, **self.policy_kwargs)
smarts/zoo/registry.py:69: in make
    agent_spec = agent_registry.make(locator, **kwargs)
smarts/core/utils/class_factory.py:131: in make
    factory = self.find_factory(locator)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <smarts.core.utils.class_factory.ClassRegister object at 0x7f44ffe31f90>
locator = 'scenarios.sumo.zoo_intersection.agent_prefabs:zoo-agent2-v0'

    def find_factory(self, locator):
        """Locates a factory given a locator."""
        self._raise_on_invalid_locator(locator)
    
        mod_name, name = locator.split(":", 1)
        # `name` could be simple name string (e.g. <open_agent-v0> or a URL
        try:
            # Import the module so that the agent may register it self in our self.index
            module = importlib.import_module(mod_name)
        except ImportError:
            raise ImportError(
>               f"Ensure that `{mod_name}` module can be found from your "
                f"PYTHONPATH and name=`{locator}` exists (e.g. was registered "
                "manually or downloaded."
            )
E           ImportError: Ensure that `scenarios.sumo.zoo_intersection.agent_prefabs` module can be found from your PYTHONPATH and name=`scenarios.sumo.zoo_intersection.agent_prefabs:zoo-agent2-v0` exists (e.g. was registered manually or downloaded.

smarts/core/utils/class_factory.py:117: ImportError
---------------------------------------------------------------------------------------------------- Captured stdout call -----------------------------------------------------------------------------------------------------
╭────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────╮
│            Episode │     Sim T / Wall T │        Total Steps │        Steps / Sec │       Scenario Map │    Scenario Routes │     Mission (Hash) │             Scores │
├────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┤
╰────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────╯
------------------------------------------------------------------------------- generated xml file: /home/jiyuan/SMARTS/sanity_test_result.xml --------------------------------------------------------------------------------
=================================================================================================== short test summary info ===================================================================================================
FAILED smarts/env/tests/test_social_agent.py::test_social_agents
================================================================================================ 1 failed, 6 passed in 11.01s =================================================================================================
make: *** [Makefile:24: sanity-test] Error 1

**Comment by Adaickalavan** [comment]
Hi @JiyuanTHU, 

The `make sanity-test` following these commands appear to run fine.
```bash
$ cd <path>/SMARTS
$ git checkout develop
# For NeurIPS2022 Driving SMARTS competition, checkout the comp-1 branch instead.
# $ git checkout comp-1
$ git pull
$ python3.8 -m venv ./.venv
$ source ./.venv/bin/activate
$ pip install --upgrade pip
$ pip install -e .[camera-obs,test]
$ make sanity-test
```

**Comment by JiyuanTHU** [comment]
>

**Comment by JiyuanTHU** [comment]
> Hi @JiyuanTHU,
> 
> The `make sanity-test` following these commands appear to run fine.
> 
> ```shell
> $ cd <path>/SMARTS
> $ git checkout develop
> # For NeurIPS2022 Driving SMARTS competition, checkout the comp-1 branch instead.
> # $ git checkout comp-1
> $ git pull
> $ python3.8 -m venv ./.venv
> $ source ./.venv/bin/activate
> $ pip install --upgrade pip
> $ pip install -e .[camera-obs,test]
> $ make sanity-test
> ```

Thanks very much! These work fine~

**Comment by zyzhang1130** [comment]
Hi @Adaickalavan do you have any idea how to fix the same issue if I'm using docker instead?

**Comment by LifGorg** [comment]
Got the same error and now able to pass sanity_test using the instruction above :)
