### ISSUE TITLE
How to simulate and visualize the pre-trained model - 2022 NeurIPS Competition track 2

### ISSUE THREAD

**Issue by HaroYoxy** [huawei-noah/SMARTS#1579]
**High Level Description**
How to simulate and visualize the pre-trained model - 2022 NeurIPS Competition track 2

**Desired SMARTS version**
0.4.12

**Operating System**
ubuntu16.04

**Problems**
I trained the IL model using Waymo. So I would like to know if there's a way to simulate and visualize my pre-trained model results, just like the envision example does?

**Comment by cz0204** [comment]
Hi, thanks for the question. We are adding this features and will be released very soon.

**Comment by Adaickalavan** [comment]
Hi @HaroYoxy,

Currently, an example code to locally
+ train an offline-learning model,
+ evaluate and visualize a pre-trained model 

is available for the CQL-based offline learning example [here](https://github.com/huawei-noah/SMARTS/tree/comp-1/competition/track2/train).

We hope this would be of help to you, while a similar local evaluation and visualization is prepared for the IL-based offline learning example.

**Comment by CrisCloseTheDoor** [comment]
> Hi @HaroYoxy,
> 
> Currently, an example code to locally
> 
> * train an offline-learning model,
> * evaluate and visualize a pre-trained model
> 
> is available for the CQL-based offline learning example [here](https://github.com/huawei-noah/SMARTS/tree/comp-1/competition/track2/train).
> 
> We hope this would be of help to you, while a similar local evaluation and visualization is prepared for the IL-based offline learning example.

Thanks for that, I'll have a try

**Comment by Adaickalavan** [comment]
Hi @HaroYoxy,

We have updated the IL-based offline learning example [code](https://github.com/smarts-project/smarts-project.rl/tree/master/neurips2022/track2) for NeurIPS2022 Track2 to include 
+ local training of an offline-learning model, and
+ local evaluation and visualization of a pre-trained model.

Further instructions are available [here](https://github.com/smarts-project/smarts-project.rl/blob/master/neurips2022/track2/train/README.md).

**Comment by Adaickalavan** [comment]
We hope the above addresses your question and thus this issue is being closed. Please feel free to reopen this issue if your problem persists or open a new issue for other questions.
