### ISSUE TITLE
Maintenance: Untether Actors From Lanes

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#1587]
@AisenGinn
Issue:
Agents are locked into being close to a lane. Essentially they are on a tether.

Request:
Agents should be able to move far off-road without causing the simulation to crash.

**Comment by AisenGinn** [comment]
Currently the `lookahead` in `smarts.core.road_map.curevature_radius_at_offset` only accept `lookahead>=1`, but `lookahead` is calculated by `lookahead = math.ceil(1 + math.log(self._target_speed))` in `smarts.core.local_traffic_provider._slow_for_curves`. The error will occur when the `self.target_speed` is very small which make the ` math.log(self._target_speed)<-1`. This will cause `lookahead` to be negative and thus raise the assertion error. Try to fixed it in PR1673:https://github.com/huawei-noah/SMARTS/pull/1673
