### ISSUE TITLE
Can we use multi observations to infer the act?

### ISSUE THREAD

**Issue by CrisCloseTheDoor** [huawei-noah/SMARTS#1611]
**High Level Description**
Can we use multi observations to infer the act?

**Desired SMARTS version**
0.4.12

**Operating System**
ubuntu 18.04

**Problems**
Hi developers, I notice that  in `single_agent.py` example, the `ChaseViaPointsAgents` everytime receives one-step obs and then output one-step act. I have a model which takes several steps of history as input, so I would like to know if there's a setting to let the agent receive multi history observations and then infer the act, including the first step?

**Comment by Adaickalavan** [comment]
Hi @CrisCloseTheDoor,

I believe you need a FrameStack environment wrapper. A FrameStack wrapper will stack the past `n` observations and return a stacked observation each time you call `env.step()` or `env.reset()`. This stacked observation may be fed to your RL model to compute an action for the latest time point. FrameStack wrappers also work at the first step.

+ Multi agent FrameStack wrapper
    + For multiagent SMARTS observation interface, we do provide a [FrameStack](https://github.com/huawei-noah/SMARTS/blob/comp-1/smarts/env/wrappers/frame_stack.py) wrapper.
    + An example using the multiagent FrameStack wrapper can be seen [here](https://github.com/huawei-noah/SMARTS/blob/bce2cf3ec6fb25f0b3e8272b84bede2bb1923b14/competition/track1/train/train/env.py#L34) in our Track1 example solution for the NeurIPS2022 competition.
    + For the first `n-1` steps, the returned stacked observation is padded with observation from the first step.

+ Single agent FrameStack wrapper
    + For environment's with single agent observation interface, you may consider using [VectorFrameStack](https://stable-baselines3.readthedocs.io/en/master/guide/vec_envs.html#vecframestack) wrapper from the Stable Baselines 3 library. 
    + An example using the `VecFrameStack` wrapper can be seen [here](https://github.com/huawei-noah/SMARTS/blob/bce2cf3ec6fb25f0b3e8272b84bede2bb1923b14/examples/rl/intersection/intersection/env.py#L34) in our [Intersection-v0](https://github.com/huawei-noah/SMARTS/tree/comp-1/examples/rl/intersection) model.

You may use our [FormatObs](https://github.com/huawei-noah/SMARTS/blob/comp-1/smarts/env/wrappers/format_obs.py) wrapper and [FormatAction](https://github.com/huawei-noah/SMARTS/blob/comp-1/smarts/env/wrappers/format_action.py) wrapper to ensure SMARTS environment observation space and action space, respectively, are fully gym compliant. An example using these wrappers can be seen [here](https://github.com/huawei-noah/SMARTS/blob/bce2cf3ec6fb25f0b3e8272b84bede2bb1923b14/competition/track1/train/train/env.py#L21-L23) in our Track1 example solution for the NeurIPS2022 competition.

**Comment by Adaickalavan** [comment]
We hope the above addresses your question and thus this issue is being closed. Please feel free to reopen this issue if your problem persists or open a new issue for other questions.
