### ISSUE TITLE
Maintenance: Upgrade `gym` version

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#1614]
## Issue
`gym` package version is out of date. This is an issue for supporting newer versions of packages and for support of . Associated with this issue is the requirement to define `action_space` and `observation_space` for all of our environments.

## Request
Define action and observation spaces for environments and update `gym` to newest version.

AC:
- [ ] SMARTS setup works with `gym>=0.25`
- [ ] Smarts setup works with `gym>=0.17.3,<=0.19.0`

**Comment by Adaickalavan** [comment]
Given the advent of `gymnasium`, this issue should be on deprecating `gym`.

**Comment by saulfield** [comment]
As @Adaickalavan commented above, we are planning to remove `gym` in favor of `gymnasium`. This is a part of #1981.
