### ISSUE TITLE
Action in TargetPose action space may cause the vehicle to teleport without physical constraints

### ISSUE THREAD

**Issue by GrandpaDZB** [huawei-noah/SMARTS#1615]
## **BUG REPORT**
**High Level Description**
Action in TargetPose action space may cause the vehicle to teleport without physical constraints.

**SMARTS version**
[0.6.1]

**Steps to reproduce the bug**
Here is the code
``` python
import gym
import numpy as np
if __name__ == "__main__":
    
    env = gym.make(
        "smarts.env:multi-scenario-v0",
        scenario='3lane_overtake',
        visdom=True
    )
    
    o = env.reset()
    init_pos = o['Agent_0'].ego_vehicle_state.position[:2]
    init_heading = o['Agent_0'].ego_vehicle_state.heading
    print(f'init_pos: {init_pos} init_heading: {init_heading:.2f}')
    
    a = np.array([init_pos[0] + 50, init_pos[1], init_heading + 1.57, 0.1])
    o, r, d, info = env.step({'Agent_0': a})
    print(f'action: {a}')
    pos = o['Agent_0'].ego_vehicle_state.position[:2]
    heading = o['Agent_0'].ego_vehicle_state.heading
    print(f'pos: {pos} heading: {heading:.2f}')
    print(f'done: {d["Agent_0"]}')
    
    pass
```

And the output is 
```
init_pos: [ 8.16 -3.2 ] init_heading: -1.57
action: [ 5.81600000e+01 -3.20000000e+00 -7.96326795e-04  1.00000000e-01]
pos: [58.16 -3.2 ] heading: -0.00
done: False
```
The vehicle teleports for 50m in 0.1s. We are able to get the vehicle to any location we want even without physical constraints. Is it a bug or a trait?

**Resulting and expected behaviour**
The vehicle may disobey the action if the target position or target heading is illegal.

 
**System information**
 
- ubuntu 20.04
- python 3.8
- gym 0.19.0
- eclipse-sumo 1.10.0
- Date when bug occurred 2022.8.31

**Comment by Gamenot** [comment]
Hello @GrandpaDZB , thank you for reporting this issue. It was an oversight that will be patching in a day or two. We overly focused on metrics but can tell now that is not enough. The vehicle will be constrained to a more limited range of motion (a rough maximum of 100km/h) which will not let target pose jump past other vehicles.
