### ISSUE TITLE
waymo dataset and dummy dataset has no background information for the first several time steps

### ISSUE THREAD

**Issue by cz0204** [huawei-noah/SMARTS#1619]
The waymo dataset and dummy dataset has no background information for the first several time steps. We can only see ego-vehicle in those images. 
<img width="312" alt="C4CD04BF-53A4-48CA-90E8-EE6BE92AC108" src="https://user-images.githubusercontent.com/84425524/188676640-a612a424-0fc1-47e3-ae95-df7c709d770e.png">

**Comment by saulfield** [comment]
Thanks, this has been fixed by #1620.
