### ISSUE TITLE
Hi, thanks! I've gone through the offline example, I am wondering if there is an available way in acquiring the ```Waypoint paths``` for neighborhood vehicles.

### ISSUE THREAD

**Issue by georgeliu233** [huawei-noah/SMARTS#1634]
Hi, thanks! I've gone through the offline example, I am wondering if there is an available way in acquiring the ```Waypoint paths``` for neighborhood vehicles.

_Originally posted by @georgeliu233 in https://github.com/huawei-noah/SMARTS/issues/1618#issuecomment-1250541950_

**Comment by georgeliu233** [comment]
FYI，for each ```/scenario_ids``` folder, is the .pkl refers to ego_vehicles only, or might also contain all the vehicles in the scenario?

**Comment by saulfield** [comment]
Hi @georgeliu233,

It sounds like you want to record observations for all vehicles in the scenario. You can do this by calling the `traffic_histories_to_observations.py` script with the `-v` option, followed by all the vehicle IDs you wish to record. There will be a `.pkl` file for each one, and they will each have `waypoint_paths`. I hope this answers your question.

**Comment by georgeliu233** [comment]
> Hi @georgeliu233,
> 
> It sounds like you want to record observations for all vehicles in the scenario. You can do this by calling the `traffic_histories_to_observations.py` script with the `-v` option, followed by all the vehicle IDs you wish to record. There will be a `.pkl` file for each one, and they will each have `waypoint_paths`. I hope this answers your question.

Thanks! I am wondering whether the hidden training dataset would contain all vehicles?

**Comment by Adaickalavan** [comment]
Hi @georgeliu233,

1. The hidden training dataset will only contain .pkl files, consisting of observation at each time point, for the ego agents which need to be controlled by the user.

**Comment by Adaickalavan** [comment]
Hi @georgeliu233,

1. The hidden training dataset only contains `.pkl` files, consisting of SMARTS observation at each time point, for the ego agents. For example, in a multi-agent scenario where the user needs to control two ego agents, the `<scenario_id>` folder will contain two `.pkl` files, one for each ego agent.
1. After your offline model is trained, it will be evaluated in a manner identical to that of Track1. During evaluation, the environment only returns SMARTS observation at each time point for the ego agents only. Hence, you will not have information on future trajectories of neighbourhood vehicles. You may deduce the past trajectories of neighbourhood vehicles, albeit probably incompletely, by looking at the ego's `observation.neighborhood_vehicle_states[<neighbor>].position` .
1. The SMARTS observation of each ego agent at each time point does not describe the future trajectories of neighbourhood vehicles as it is not reasonable to exactly know this information in real life.
1. For your own development and training purposes, you may generate `.pkl` files, consisting of SMARTS observation at each time point, for all vehicles following the instructions given above.

**Comment by georgeliu233** [comment]
> Hi @georgeliu233,
> 
> 1. The hidden training dataset only contains `.pkl` files, consisting of SMARTS observation at each time point, for the ego agents. For example, in a multi-agent scenario where the user needs to control two ego agents, the `<scenario_id>` folder will contain two `.pkl` files, one for each ego agent.
> 2. After your offline model is trained, it will be evaluated in a manner identical to that of Track1. During evaluation, the environment only returns SMARTS observation at each time point for the ego agents only. Hence, you will not have information on future trajectories of neighbourhood vehicles. You may deduce the past trajectories of neighbourhood vehicles, albeit probably incompletely, by looking at the ego's `observation.neighborhood_vehicle_states[<neighbor>].position` .
> 3. The SMARTS observation of each ego agent at each time point does not describe the future trajectories of neighbourhood vehicles as it is not reasonable to exactly know this information in real life.
> 4. For your own development and training purposes, you may generate `.pkl` files, consisting of SMARTS observation at each time point, for all vehicles following the instructions given above.

Hi,
Thanks for your detailed reply! However, what we are concerned about is actually not the future trajectory but the map information (```wapoint_paths``` or ```road_waypoint```) for each```obs.neighborhood vehicles```,  as it is common to be able to acquire the overall scene map information in real-life hypothesis; While in the current hidden dataset, almost all map information is missed for neighbor vehicles. Thanks again for your kindly help and reply!

**Comment by MCZhi** [comment]
The reason we need `waypoint_paths` for neighborhood vehicles is that we want to build a vectorized map representation of the driving scene. It would also be nice if the organizer could provide map information (map file) in the offline dataset. We genuinely hope the organizer could consider it.

**Comment by Adaickalavan** [comment]
Unfortunately, I am afraid we are unable to accomodate your request as far as the NeurIPS2022 competition is concerned, with respect to the vectorized map representation.
