### ISSUE TITLE
AttributeError when running multi agent scenario

### ISSUE THREAD

**Issue by georgeliu233** [huawei-noah/SMARTS#1638]
**High Level Description**
attribute error when testing the scenario ```3lane_cruise_multi_agent```

**Desired SMARTS version**
[e.g. 0.4.12]

**Problems**
When I'm testing my policy using ```3lane_cruise_multi_agent```, which comprises 3 agents to control; At first only ```Agent-2``` occurs, and everything operates well. However, when another agent ```Agent-0``` also occurs, the simulator is crashed due to the following error:

```SMARTS/smarts/core/controllers/motion_planner_controller.py", line 81, in perform_action
    pose, speed = controller_state.get_next_state(
AttributeError: 'NoneType' object has no attribute 'get_next_state'
```

It seems that the ```controller_state``` for the newly occurred agent ```agent-0``` is ```None```!

Help needed!

**Comment by Adaickalavan** [comment]
Hi @georgeliu233,

Could you kindly provide us a minimum working example to reproduce the error?

**Comment by georgeliu233** [comment]
> Hi @georgeliu233,
> 
> Could you kindly provide us a minimum working example to reproduce the error?

```
scenarios = ['/SMARTS/smarts/scenarios/straight/3lane_cruise_multi_agent']
for scene in scenarios:
    sc_score = Score()
    scene = scene.split('/')[-1]
    datastore = DataStore()
    env = gym.make("smarts.env:multi-scenario-v0",scenario=scene,**shared_configs)
    env = CopyData(env, list(env.agent_specs.keys()), datastore)
    env = gym.Wrapper(env)
    for wrapper in wrappers:
        env = wrapper(env)
    
    metric = Metric(env_name=scene, agent_names=datastore.agent_names)

    for episode in episodes(n=10):
        observations = env.reset()
        episode_len = 0
        dones = {"__all__": False}
        while not dones["__all__"]:
            actions = policy.act(observations)
            for t in range(1):
                action = {}
                for agent_id in actions.keys():
                    action[agent_id] = actions[agent_id][t]
                observations, rewards, dones, infos = env.step(action)
                episode_len += 1
                if dones["__all__"]:
                    break

        metric.store(infos=datastore.data["infos"], dones=datastore.data["dones"])

    counts, costs = metric.results()
```

**Comment by georgeliu233** [comment]
> Hi @georgeliu233,
> 
> Could you kindly provide us a minimum working example to reproduce the error?

It seems that in this env, 3 agents occur asynchronously, and the env will encounter the error at the 1st step of ``env.step()``` when the obs contains 2 agents

**Comment by Adaickalavan** [comment]
Hi @georgeliu233,

1. The `3lane_cruise_multi_agent` scenario appears to be working fine.
2. Could you provide a working example which can be executed in order to reproduce the error?

**Comment by Adaickalavan** [comment]
Hi @georgeliu233,

1. The `3lane_cruise_multi_agent` scenario appears to be working fine.
2. Could you provide a working example which can be executed in order to reproduce the error? Unfortunately, the previously provided example is not runnable.

**Comment by Adaickalavan** [comment]
Given the `3lane_cruise_multi_agent` scenario appears to be working fine and the lack of a minimum working example to reproduce the error, this issue is being closed. Please feel free to open a new issue for other questions.
