### ISSUE TITLE
Scenario Metadata Files

### ISSUE THREAD

**Issue by qianyi-sun** [huawei-noah/SMARTS#1645]
Regeneration of scenario resources should only occur if a resource has changed.
- Full optimization requires a dependency tree
- A resource should be regenerated when:
  - The resource file has been updated
  - The resource depends on another resource that has been updated
  - The resource has changed its dependencies
  - The version of SMARTS has changed since the resource was built
- This should result in a general improvement in scenario build time

**Comment by saulfield** [comment]
Duplicate of #1595.
