### ISSUE TITLE
[Possible issue]After running make test, ray processes will not end gracefully

### ISSUE THREAD

**Issue by iman512003** [huawei-noah/SMARTS#165]
The ray version on my machine is 0.8.3.

**Comment by GuyueHuang** [comment]
Hi, have you encountered a situation where the make test stops at 40%?

**Comment by GrayHHHH** [comment]
Hi, have you encountered a situation where the make test stops at 40%?

**Comment by Adaickalavan** [comment]
@iman512003 

After performing `make test` in the latest pull request #331, running the `htop` command does not show any leftover ray processes. Could you verify whether this issue still occurs?
