### ISSUE TITLE
Questions about the judgment of vehicle on_shoulder event when converting waymo dataset to SMARTS dataset

### ISSUE THREAD

**Issue by superCat-star** [huawei-noah/SMARTS#1653]
**High Level Description**
When I used examples/traffic_histories_to_observations.py to convert waymo dataset to SMARTS dataset according to the guidance of README in competition/track2, I had some questions about the judgment of the on_shoulder event of the ego vehicle.

**Problems**
When the ego vehicle is driving close to the edge of the road, the _is_done_with_events function in line 514 of the smarts/core/sensors.py will misjudge that the vehicle is partly out of road bounds (on_shoulder=True), which will cause the competition/track2/train/train.py to misjudge the terminal of the current step as true.

Here is an example:
File=validation.tfrecord-00011-of-00150, Scenario_id=3714ba3e1d32f18b, time=0.1s
![image](https://user-images.githubusercontent.com/59948975/193398042-93bae3f4-a0d4-4df2-a2a6-c57eba1f7a71.png)

**Comment by Adaickalavan** [comment]
Hi @superCat-star,

1. From the provided image, the ego agent appears to be driving on road shoulder, thus `on_shoulder=True` is reasonable.
2. Please refer to the updated terminal conditions in `competition/track2/train/train.py`.
https://github.com/huawei-noah/SMARTS/blob/ea3315c4caf2cb70a9e6b1611a142ebc90b1d178/competition/track2/train/train.py#L124-L132
