### ISSUE TITLE
Incompatible Ray

### ISSUE THREAD

**Issue by KornbergFresnel** [huawei-noah/SMARTS#167]
I found the default version of Ray is 0.8.3. But the CoRL benchmarking requires 0.8.7. I think we can upgrade it to 1.0.0 to address this incompatible and taste the new features of Ray.

**Comment by KornbergFresnel** [comment]
@mg2015started and I can handle it.

**Comment by Gamenot** [comment]
Ok, I have used ray 1.0 in SMARTS before with little issues. There may be no problems with upgrading.

**Comment by cinjon** [comment]
I'm running into this when running `pip install -e .[train]` and getting `No matching distribution found for ray[rllib]==1.0.0`. This is happening regardless of if I use 0.8.4 (default) or change it to 1.0.0 in both setup.py and requirements.txt.

**Comment by cinjon** [comment]
This appears to be related to Ray not having a 3.9 wheel.

**Comment by Gamenot** [comment]
> This appears to be related to Ray not having a 3.9 wheel.

Hi, this is useful to know. Currently the most compatible version of `python` is 3.7. We cannot currently guarantee that other versions of python will work out of the box without some extra effort.

We will be working soon to expand to ensure 3.8 also works. #266
