### ISSUE TITLE
Competition submission has been running too long

### ISSUE THREAD

**Issue by MCZhi** [huawei-noah/SMARTS#1675]
**Problems**
Hi, there. I submitted my solution to the Track 1 Test server on Oct 17 and the submission has been running for two days without returning the results. Is it normal? And if it is not, can anybody offer some help? Thank you very much!

**Comment by Gamenot** [comment]
Hello @MCZhi, apologies it looks like there may have been an error with the queue. It looks like the submission never started. I have cancelled it.

**Comment by Adaickalavan** [comment]
Hi @MCZhi,

Your submission is being re-run now.

**Comment by MCZhi** [comment]
Thanks for your help!
