### ISSUE TITLE
Environment observations

### ISSUE THREAD

**Issue by baimukashev** [huawei-noah/SMARTS#1678]
Hi, some of the observations in the documentation (https://smarts.readthedocs.io/en/latest/sim/observations.html) are listed as optional. What does this exactly mean? Can we assume that these observations are always available in all scenarios from Waymo, Ngsim, etc. ?

**Comment by Adaickalavan** [comment]
Hi @baimukashev,

1. Some of the observations may be toggled on/off or be configured individually for each agent by setting the appropriate values in the corresponding [`AgentInterface`](https://github.com/huawei-noah/SMARTS/blob/49ece7157bb338570b0e2620a7cd4b376a986821/smarts/core/agent_interface.py#L230) supplied when creating the SMARTS environment.
2. For example, the optional observation item `top_down_rgb` will be made available in the returned observation when the corresponding `rgb` attribute is set in the `AgentInterface` supplied to the enviroment during its creation.  
    ```
    agent_specs = {
        f"Agent_{i}": AgentSpec(
            interface=AgentInterface(
                rgb=RGB(
                    width=img_pixels,
                    height=img_pixels,
                    resolution=img_meters / img_pixels,
                ),
            )
        )
        for i in range(num_agent)
    }
    
    env = HiWayEnv(
        scenarios=scenario,
        agent_specs=agent_specs,
    )
    ```

**Comment by baimukashev** [comment]
Thanks!
