### ISSUE TITLE
Waymo Road Map `lane_to_left` asserts

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#1680]
## **BUG REPORT**
**High Level Description**
Waymo road map is unable to find a lane left of an existing lane for the purposes of generating the lane dividers.

**SMARTS version**
NeurIPS competition branch `comp-1`
[58a61aa](https://github.com/huawei-noah/SMARTS/commit/58a61aa01145a0534e2eab82c500327e0b11acf4)

**Previous associated issues**
N/A

**Steps to reproduce the bug**
This issue shows up when generating waymo scenarios:
```
+ validation.tfrecord-00045-of-00150
+ eb0f5d3f1760206e
```

**Resulting and expected behaviour**
Should generate the scenario without issues but runs into a missing lane.

**Error logs and screenshots**
```
cli/studio.py, line 79, in _build_single_scenario_proc
   build_single_scenario(clean, allow_offset_map, scenario, seed, click.echo)
smarts/sstudio/build_scenario.py, line 75, in build_single_scenario
   road_map.to_glb(os.path.join(scenario_root, "map.glb"))
smarts/core/waymo_map.py, line 994, in to_glb
   glb = self._make_glb_from_polys()
smarts/core/waymo_map.py, line 1019, in _make_glb_from_polys
   lane_dividers = self._compute_traffic_dividers()
smarts/core/waymo_map.py, line 1037, in _compute_traffic_dividers
   lane_to_left, _ = lane.lane_to_left
smarts/core/waymo_map.py, line 1255, in lane_to_left
   return self._get_side_lane("left")
smarts/core/waymo_map.py, line 1251, in _get_side_lane
   return self._map.lane_by_id(side_lane_id), same_dir
smarts/core/waymo_map.py, line 1564, in lane_by_id
   assert lane, f"WaymoMap got request for unknown lane_id: '{lane_id}'"
AssertionError: WaymoMap got request for unknown lane_id: '151_3'

```

**Comment by Gamenot** [comment]
There are 3 speculated reasons why this is happening:

1) `lane_id=="151_3"` should exist but was not generated.
2) lane index is inappropriately counted resulting in incorrect `lane_id`.
3) `composite_roads` somehow has a mismatched number of lanes (number of lanes on all roads in the composite should be the same)

**Comment by saulfield** [comment]
I believe this was fixed, though I can't find the PR.
