### ISSUE TITLE
Track1 multiagent scenario

### ISSUE THREAD

**Issue by zyzhang1130** [huawei-noah/SMARTS#1689]
So does anyone have a way to train in multiagent setting in any of the tack1 scenarios? Since PyMARL and MALib doesn't work at the moment, is there any workaround to make two agents training on single RL algo simultaneously in a scenario?

**Comment by Adaickalavan** [comment]
Hi @zyzhang1130,

There are several options available, which includes the following.
1. Consider using other multiagent RL libraries, such as [RLlib](https://docs.ray.io/en/latest/rllib/index.html).
1. Alternatively, consider training a single agent during training and during inference infer the actions of each agent individually. An example of this approach is shown in the given Track1 example.
https://github.com/huawei-noah/SMARTS/blob/a8c7e2292edd782c3fd8d89a341c3ee76c89cfcd/competition/track1/submission/policy.py#L77-L82

**Comment by zyzhang1130** [comment]
for option 1, is there any guide on how to run RLlib in smarts env?

**Comment by Adaickalavan** [comment]
1. SMARTS observation outputs a dictionary format which is compatible with [RLlib](https://docs.ray.io/en/latest/rllib/index.html). Hence, directly follow the instructions at [RLlib](https://docs.ray.io/en/latest/rllib/index.html).
2. An example of using SMARTS env with RLlib is available [here](https://github.com/huawei-noah/SMARTS/tree/develop/examples/rllib).

**Comment by Adaickalavan** [comment]
We hope the above addresses your question and thus this issue is being closed. Please feel free to reopen this issue if your problem persists or open a new issue for other questions.

**Comment by OscarBastardo** [comment]
> 1. SMARTS observation outputs a dictionary format which is compatible with [RLlib](https://docs.ray.io/en/latest/rllib/index.html). Hence, directly follow the instructions at [RLlib](https://docs.ray.io/en/latest/rllib/index.html).
> 2. An example of using SMARTS env with RLlib is available [here](https://github.com/huawei-noah/SMARTS/tree/develop/examples/rllib).

Hi, the link for the example gives 404. Presumably, the directory was moved within the develop branch. Could you share a link to this example if it is still available? Thanks

**Comment by Adaickalavan** [comment]
Hi @OscarBastardo ,

The RLlib example can be found [here](https://github.com/huawei-noah/SMARTS/tree/develop/examples/rl/rllib).
