### ISSUE TITLE
Time needed to run the validation

### ISSUE THREAD

**Issue by yuant95** [huawei-noah/SMARTS#1694]
**High Level Description**
Verify my submission status to the validation stage. 

**Desired SMARTS version**
0.6

**Operating System**
ubuntu 20.04

**Problems**
I've submitted a submission to track1 validation, but it's been more than 7 hours, and it's still in the status of running. I'm wondering whether it actually takes that long to run, or something I submitted crashed/stuck in infinite loop etc. 
My colab account is yuant426. Let me know if you need more information to locate my submission. Thanks!

**Comment by smarts-project** [comment]
Hello @yuant95, yes it can take that long to run. It looks like the track may have stuck. I am attempting to get it running again.

**Comment by yuant95** [comment]
Thanks for getting back to me! However, I just submit a submission to track1 which ends up fail. The timestamp of the submission is 11/03/2022 21:53:00. I didn't find too much useful information for me to debug the issue. Is there anything you could provide to me to see why it failed? Thanks!

**Comment by Gamenot** [comment]
Hello @yuant95, I assume you are listed as `yuant426`. I see a failed submission at 11/3/2022, 5:53:00 PM UTC and a new submission that is in queue since 11/4/2022, 2:46:54 AM UTC.

It looks like some part of your policy failed. The following error occurred many times in your submission:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/codalab3/tmplBFku7/run/program/evaluate.py", line 354, in _worker
    actions = policy.act(observations)
  File "/tmp/codalab3/tmplBFku7/run/input/res/policy.py", line 89, in act
    action = self.get_next_goal_pos(agent_obs, agent_id)
  File "/tmp/codalab3/tmplBFku7/run/input/res/policy.py", line 164, in get_next_goal_pos
    goal_path_index = self.get_cloest_path_index_to_goal(agent_obs)
  File "/tmp/codalab3/tmplBFku7/run/input/res/policy.py", line 291, in get_cloest_path_index_to_goal
    path_index = np.argmin(dist_to_goal)
  File "<__array_function__ internals>", line 180, in argmin
  File "/opt/.venv/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 1312, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out, **kwds)
  File "/opt/.venv/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/opt/.venv/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: attempt to get argmin of an empty sequence
```

It seems there was an empty sequence passed in `"/tmp/codalab3/tmplBFku7/run/input/res/policy.py", line 291, path_index = np.argmin(dist_to_goal)`.

**Comment by yuant95** [comment]
Yes, that's correct. Just for confirmation, this error msg is from the failed submission earlier, not the new one in the queue?

Thank you! This is helpful for me to debug.

**Comment by Gamenot** [comment]
> Yes, that's correct. Just for confirmation, this error msg is from the failed submission earlier, not the new one in the queue?
> 
> Thank you! This is helpful for me to debug.

Yes, this is from the failed submission. Your new submission appears to be running right now.

**Comment by Gamenot** [comment]
@yuant95 Your most recent submission is successful.

**Comment by Gamenot** [comment]
@yuant95 Your submission has started running.
