### ISSUE TITLE
OSError: Could not load model file(s): ['.../map.glb']

### ISSUE THREAD

**Issue by yuant95** [huawei-noah/SMARTS#1699]
**High Level Description**
Smarts crashes when I run multiple simulation with the same scenario concurrently.  

**Desired SMARTS version**
0.6

**Operating System**
ubuntu 20.04

**Problems**
I tried to start multiple jobs for running the simulation on the scenario on parallel. However, once I have more than one job running on parallel, I alway encounter the error as below. 

```
OSError: Could not load model file(s): ['/ubc/cs/research/plai-scratch/smarts/miniconda3/envs/smartsEnv/lib/python3.8/site-packages/smarts/scenarios/intersection/1_to_2lane_left_turn_t/map.glb']
ERROR:SMARTS:Failed to successfully reset after 2 times.
```

Somehow one of the job cannot find this file, and caused the crash. I suspect that smarts will rewrite/delete this file while running, and that's why I can't run 2 jobs on parallel. I'm wondering whether smarts is not designed to run parallel computing, or did I do something wrong for setting up parallel simulations?

Any help will be appreciated!

**Comment by Adaickalavan** [comment]
Hi @yuant95,

1. Which SMARTS environment are you using?
1. For the `multi-scenario-v0` env, every time the the environment is instantiated, the scenario folder is automatically built by the following build command
https://github.com/huawei-noah/SMARTS/blob/e07d960623aa145342f3dcc9cb0d51ebe5403440/smarts/env/multi_scenario_env.py#L116 
    which includes the `--clean` option by default. The `--clean` option cleans previously generated artifacts.
https://github.com/huawei-noah/SMARTS/blob/e07d960623aa145342f3dcc9cb0d51ebe5403440/smarts/sstudio/__init__.py#L57
    Here, if you use the same scenario folder for multiple environments, then the scenario folder will be rebuilt by competing environments causing the error seen by you.

There are several possible options:
1. Disable the `--clean` option by changing this line
https://github.com/huawei-noah/SMARTS/blob/e07d960623aa145342f3dcc9cb0d51ebe5403440/smarts/sstudio/__init__.py#L57
to
    ```python
    build_scenario = " ".join(["scl scenario build-all"] + scenario)
    ```
1. Or, disable the automatic building of the scenario folder by commenting out the [above line](https://github.com/huawei-noah/SMARTS/blob/e07d960623aa145342f3dcc9cb0d51ebe5403440/smarts/env/multi_scenario_env.py#L116). Build the scenario folder once manually by using the command `scl scenario build-all --clean <path to scenario folder>`. Then start multiple environments referring to the same scenario folder.
1. Or, duplicate the scenario folders and use different scenario folders for different environments.

**Comment by yuant95** [comment]
@Adaickalavan Thanks for getting back to me! I'll try this for sure.
