### ISSUE TITLE
Track1 Submission Status

### ISSUE THREAD

**Issue by yuant95** [huawei-noah/SMARTS#1700]
**High Level Description**
Check the status of my recent submission. 

**Problems**
I've submitted one solution last night, and it hasn't finished running after 12+ hours. I'm not sure is it still running, or track1 is stuck again? As we are getting closer to the deadline, is it possible for me to get some ealier feedback if it's stuck? My account is yuant426. 

Also for confirmation, is track 1 ending at Nov 7th, 5am UTC time? I never find the exact time that track1 would be closed. 

Thank you!

**Comment by Adaickalavan** [comment]
Hi @yuant95,

+ Currently, there is a high number of submissions running. 
+ All solutions submitted before the the respective track closing time will be scored and ranked (including submissions which are still pending at the track closing time).
+ Track1 closes on 7 Nov 2022, 05:00 UTC.

**Comment by Gamenot** [comment]
Hello @yuant95, as mentioned the track is set to end Nov 7th, 5am UTC time.

Your submission is currently in queue to be run now. There are a high number of submissions and yours should be started within 3-7 hours.

**Comment by Gamenot** [comment]
@yuant95 We are currently adding more workers, this should speed up submissions.

**Comment by yuant95** [comment]
@Gamenot  Thanks for getting back to me. Great to hear that more workers are added, although I'm wondering whether I will be able to submit new one if my old one failed due to errors? Also, as I don't get feedback soon enough, could I submit more than 2 submission in a day? Thanks!

**Comment by Gamenot** [comment]
@yuant95 If a submission fails it does not count against the total submission count but it does against the daily submission count. We are worried about clearing submissions in time so increasing the number of submissions a day is difficult.

We are currently considering extending the deadline by up to a day. But it will make clearing evaluation (and curating) for a winner by the 10th a bit tight.

**Comment by yuant95** [comment]
@Gamenot Thanks! I understand the current situation, however, does it seem to be possible that I would be able to view my score of this submission before the deadline so I can refine something and submit another one? Or I should just submit whatever I have now and wait for the final results....

Also, If after the deadline, my last submission turns out to fail to run, would I be given an opportunity to fix that issue and resubmit? I wasn't expecting the submission would take this long to run, so I'm a bit afriad that I don't have the time to fix any unexpected errors before the deadline. 

Thanks anyway! :)

**Comment by Adaickalavan** [comment]
@yuant95

**Comment by Adaickalavan** [comment]
Hi @yuant95,

1. Your last submission on 06/11/2022, 05:36:22, yuant426, has been successfully evaluated.
1. You may submit any other solutions before the Track1 closing time.
