### ISSUE TITLE
Can't submit to track1

### ISSUE THREAD

**Issue by yuant95** [huawei-noah/SMARTS#1701]
**High Level Description**
Can't submit to track1

**Problems**
I've been trying to make my final submission to track1. However, once I selected the file to submit, it just stuck at the page with the submit button disabled. I've waited for a while, but nothing happens. I've only made 3 successfuly submission to track1 so far, so I don't think that I ran out of submissions tries?

**Comment by Gamenot** [comment]
Hello @yuant95, I have increased the daily submissions, please confirm if you still cannot submit.

**Comment by yuant95** [comment]
It's submitted now. Sorry, false alarm.

**Comment by yuant95** [comment]
Hi @Gamenot, sorry I think I just failed to upload my last submission. Could you check whether the submission is successful?

**Comment by yuant95** [comment]
Hi @Gamenot, I think my submission just failed.... Is it possible for my to send my last submission? I just found a typo in my previous submission, and I was hoping I could submit a new one.....

**Comment by Gamenot** [comment]
Hello @yuant95, I see a submission sent in by you roughly 4 hours ago. Is that the submission you are referring to or did you just make a new submission?

I only see one submission for you today.

**Comment by yuant95** [comment]
I just made a new submission like roughly 20 minutes ago, but it then showed my upload failed error message.

**Comment by Gamenot** [comment]
Does it let you try again? There are a large number of submissions at this time.

**Comment by yuant95** [comment]
It was showing somthing like `uploading failed due to internet issue` error. Sorry I don't remember the exact error message. But should I just try to submit again now? I thought I just passed the deadline.

**Comment by Gamenot** [comment]
@yuant95 There are still 1.5 hours left on the deadline since it closes midnight PST.

I can see a new submission in the queue now.

**Comment by yuant95** [comment]
Thanks! Ah! I was doing the conversion from the 5am UTC, and the daylight saving changes confuses me a bit.

**Comment by Gamenot** [comment]
No worries, UTC made the conversion confusing, the end time is 8 UTC and daylight savings time confuses everyone at least twice a year.
