### ISSUE TITLE
Track 1 Submission Failed with Standard Error

### ISSUE THREAD

**Issue by yuant95** [huawei-noah/SMARTS#1704]
Thanks for all the timely help before track 1 deadline so I can make my final submission!

Unfortunately, I just found that my last submission failed in my submission page. I was trying to get some error log, but it only returns `Standard error for submission #0 by yuant426.`. Does it mean it is not my submission failed to run, but something else happened? Will my submission get rerun before the 10th? Otherwise, I was just hoping I could get some closure of the failure. 

I also noticed a weird behavior of the submission page. My last submission seemed to be messed up into 2 submission with one of it has really small size. This only showed up today. Everything seemed normal after my submission. Is this just some frontend glitch? Or should I be worried?

Thanks so much :) !!! It's almost done :)

**Comment by Gamenot** [comment]
Hello @yuant95, I was just about to get into contact with you. We were having some issues with your submission. The size of the submission was fairly large ~1.2GB and was causing issues with Codalab which appears to expect submissions up to 300mb in size. 

The Codalab platform appears to have corrupted the submission so it is no longer possible to rerun the solution. We have a copy of the submission separately.

If you have time now we can reopen the Track 1 temporarily for you to resubmit the exact same final submission.

**Comment by yuant95** [comment]
@Gamenot Thanks for getting back to me! I can resubmit the file now if needed.

**Comment by Gamenot** [comment]
Track2 is temporarily reopened for your submission.

**Comment by yuant95** [comment]
Cool, I just uploaded it. Let me know if it fails again or it's not the same file. I'm 99% sure it should be the same file as I didn't touch it after the submission last night. But if not, is it possible for you to send me the file? Or somehow submit it from your side? I may lost track of which version of code I submitted.....

**Comment by Gamenot** [comment]
We have a copy of the submission.
![image](https://user-images.githubusercontent.com/8764693/200490208-63ebc34d-f404-40f7-966c-0f968e44fcf3.png)
We believe it should be the same.

**Comment by yuant95** [comment]
Great! It's showing running in the status now, but no value in the size block. Hope it works out this time. I should have saved my neural network model in a different format to aviod the big size now I think back....

**Comment by Gamenot** [comment]
Yes, we see it now. It may take a bit to get working...

**Comment by Gamenot** [comment]
@yuant95 Your submission is complete.

**Comment by yuant95** [comment]
Great! Thanks so much for the help!
