### ISSUE TITLE
Track2 docker image build 

### ISSUE THREAD

**Issue by yuant95** [huawei-noah/SMARTS#1709]
**Problems**
I'm new to the docker file and docker hub stuff, so I'm a bit confused about the docker requirement in the track2 submission. 

I've set up the train and submission folders for track2 properly, and have manually ran the train.py and policy.py to make sure they work. 

I've built the docker image (using the provided docker file without any changes) and I'm trying to run it locally to test it before I push it to Docker Hub. 

However, the error `No module named `smarts``  poped up when I try to run the docker image locally. I assume this is due to I didn't install smarts (as it is not included in my requirement.txt file under the submission folder) for my docker image. However, I'm not certainly sure how to install smarts in the docker, or whehter I need to do so. Will this dependency be resolved if the docker image is build on the competition server? Or it is something I should figure out.

Any help is appreciated!

**Comment by yuant95** [comment]
I think I figured it out by adding the smarts==0.6.0 into the requirment.txt file. However, I still cannot run the docker locally as it throws

```
/SMARTS/competition/offline_dataset/sumo_2/Agent-history-vehicle-1.pkl
Traceback (most recent call last):
  File "/SMARTS/competition/track2/train/train.py", line 121, in <module>
    main(args)
  File "/SMARTS/competition/track2/train/train.py", line 100, in main
    train(input_path, output_path)
  File "/SMARTS/competition/track2/train/train.py", line 56, in train
    dataset = track2Dataset(input_dir=train_config["input_path"])
  File "/SMARTS/competition/track2/train/custom_dataset.py", line 22, in __init__
    data = pickle.load(f)
TypeError: __new__() takes 18 positional arguments but 19 were given
```

I'm not sure what's wrong. That pickle file is definitely found in the docker as I did a os.walk to get that file path, but I can't read the pickle file in the docker....? I'm not sure why? I've test it outside of the docker, and it works. I'm running out ideas.

**Comment by yuant95** [comment]
Ah, I've tried the original track2 example package provided in the repo. I ran into the same issue. It first complains `No module named smarts`, and then after I add smarts in the requirment.txt. It complains that cannot load the pickle file. 

I guess I've dealt the `No module named smarts` error wrong?

**Comment by Gamenot** [comment]
Dear @yuant95, `smarts==0.6.0` would be out of date such that it is not possible to load the pickle files you mentioned. If you are trying to test your solution then you may or may not want to try the following lines for getting the correct competition dependencies:

https://github.com/huawei-noah/SMARTS/blob/e07d960623aa145342f3dcc9cb0d51ebe5403440/competition/evaluation/requirements.txt#L1-L3

**Comment by Adaickalavan** [comment]
Hi @yuant95,

1. Please try using the latest Track2 Dockerfile which pip installs smarts package.
https://github.com/huawei-noah/SMARTS/blob/31ee15a153e2163774fc2571da46fed6ac1421ba/competition/track2/Dockerfile#L32-L35

2. Make the necessary fixes, reupload your Docker image to DockerHub, and resubmit online to Codalab Track2.

**Comment by yuant95** [comment]
Hi @Adaickalavan, 

Thanks for the reply! Indeed, I didn't pull the newest changes from the repo, so I didn't have the updated dockerfile and setup.py file in the train folder. Once I did, I got rid of the exception. I'll upload my new image and resubmit again. Thanks!
