### ISSUE TITLE
Trying to have scenarios with social agents into the training

### ISSUE THREAD

**Issue by yuant95** [huawei-noah/SMARTS#1715]
**High Level Description**
I'm trying to set up scenarios with social agents (from zoo for now) to be used in training a ego car model.

**Desired SMARTS version**
0.6.1

**Problems**
Here is the error msg I received. I'm not sure how to resolved it. Or is there any example you can point me to that load scenarios with social agents?

```
Ensure that `scenarios.straight.3lane_cruise_single_agent.agent_prefabs` module can be found from your PYTHONPATH and name=`scenarios.straight.3lane_cruise_single_agent.agent_prefabs:zoo-agent-v0` exists (e.g. was registered manually or downloaded.
```

**Comment by Gamenot** [comment]
Hello @yuant95, we also ran into this issue suddenly recently. Our agent loading lost a small amount of functionality at an unknown time.

The relation that the agent tag has to a module is the following:

`"path.to.module:agent_name-v#"`

An example of this is: `scenarios.straight.cruise_3lane_single_agent.agent_prefabs:cruise-v3`

## `path.to.module`

The module path must be located in a place that can be resolved by python. This means the directory has to follow python restrictions.

The rule is that `import path.to.module` or a dynamic version (such as using importlib) must be valid as `path/to/module/__init__.py` or `path/to/module.py` from a path in `sys.path`.

```python
# example.py
import scenarios.straight.cruise_3lane_single_agent.agent_prefabs
from smarts.zoo import registry

agent_kwargs = dict(...)
loc = "scenarios.straight.cruise_3lane_single_agent.agent_prefabs:cruise-v3"
agent_spec = registry.make(loc, **agent_kwargs)
```

This means for `scenarios.straight.cruise_3lane_single_agent.agent_prefabs` that the file structure needs to look like:

```
<PATH> (must be within python path i.e. `sys.path`)
└── scenarios
    └── straight
        └── cruise_3lane_single_agent
            └── agent_prefabs.py

or if you are trying to be safe

<PATH>
└── scenarios
    ├── __init__.py
    └── straight
        ├── cruise_3lane_single_agent
        │   ├── agent_prefabs.py
        │   └── __init__.py
        └── __init__.py

```

## `agent_name`
Is the name value of the agent similar to the gym environment convention.

## `-v#`
Is the the versioning number of the agent. It can be incremented like `-v0`, `-v1`, ...

## The easy way to deal with this
If you have a module you can place the registration of the agents in that module and then reference them.

```python
## example.py
import yuant
from smarts.zoo import registry

loc = "yuant:cruise-v3"
# If this works with your current environment then any scenario
#   referencing "yaunt:cruise-v3" will also work even without doing 
#   this explicitly.
agent_spec = registry.make(loc)
```

```python
## yuant/__init__.py
from smarts.zoo import registry
from smarts.core.agent_spec import AgentSpec

def entrypoint(**kwargs):
    return AgentSpec(**kwargs)

registry.register("cruise-v3", entry_point=entrypoint)
```

**Comment by yuant95** [comment]
Great, thanks! I'll give it a try later when I started these scenrios with social agents.
