### ISSUE TITLE
Smarts map coordinate system

### ISSUE THREAD

**Issue by yuant95** [huawei-noah/SMARTS#1722]
**Problems**
I noticed that smarts map is not centered but rather started at left bottom corner? I am wondering whether I can center the map, or get the bounding box of the map so I can convert the agent location into a centered map. 

I need to figure this out to get a third part library to generate actions for some custom agents I implemented. They centered the map, so I need to do the conversion. 

Let me know if my question is not clear or you need more information. Thanks!

**Comment by Gamenot** [comment]
Hello @yuant95, if you have access to the underlying `SMARTS` instance you can use it to get the map:

```python
smarts_instance = hiway_env._smarts
hiway_env.reset()
## the current road map is available after SMARTS.reset(scenario) or HiwayEnv.reset() 
center = smarts_instance.road_map.bounding_box.center
```

another option is to get the road map centers beforehand

```python
scenario_roots = smarts.core.Scenario.get_scenario_list(scenarios_or_scenarios_dirs)
for root in scenario_roots:
    map_spec = smarts.core.Scenario.discover_map(scenario_root, 1.0, None)
    road_map, road_map_hash = map_spec.builder_fn(map_spec)
    center = road_map.bounding_box.center
```

**Comment by Gamenot** [comment]
Another option is to use the metadata from the glb https://github.com/huawei-noah/SMARTS/pull/1716/files.

```python
meta = road_map.map_glb_metadata
bounding_box = meta["bounding_box"]
```
