### ISSUE TITLE
CI test of competition

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#1731]
- [ ] Competition action space test
- [ ] Competition multi-env test
- [ ] Competition bubble_env test

**Comment by Adaickalavan** [comment]
Currently, we have CI [test](https://github.com/huawei-noah/SMARTS/blob/ffa85d91a9903d4341d9f72a1b28f41055cf4178/.github/workflows/ci-base-tests-linux.yml#L68-L129) for Driving SMARTS 2023.1, 2023.2, and 2023.3 .
