### ISSUE TITLE
Find storage for competition models

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#1737]
- [ ] Find ways to reduce the size of models
- [ ] Find host for trained models (e.g. PyPI)
- [ ] Save models are not stored in `git`.
- [ ] Integrate competition models into the Zoo

**Comment by Adaickalavan** [comment]
Selected contributed agents during competitions are integrated into Agent Zoo and listed in the [docs](https://smarts.readthedocs.io/en/latest/benchmarks/agent_zoo.html#available-zoo-agents). They are hosted at PyPI as package and corresponding source code is hosted at [smarts-project.rl](https://github.com/smarts-project/smarts-project.rl).
