### ISSUE TITLE
Fix `Completion` metric

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#1748]
- [x] Base completion on successfully reaching goal of scenario.

**Comment by Adaickalavan** [comment]
In PR #1753 , the completion metric is now computed as the proportion of successfully completed scenarios (i.e., goal_achieved / number_of_episodes).
https://github.com/huawei-noah/SMARTS/blob/3dedf1c2457beca99811fd9831f8cc6946808acd/smarts/env/wrappers/metrics.py#L255-L256
