### ISSUE TITLE
Resolve Cloudpickle incompatibility

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#1757]
## **BUG REPORT**
**High Level Description**
Cloudpickle requirement can conflict with gym and cause issues with running SMARTS.

**SMARTS version**
smarts==0.7.0

**Steps to reproduce the bug**
Environments without python-dev will have this problem.

**Resulting and expected behaviour**
Python will refuse to run SMARTS because of context conflicts.

**Error logs and screenshots**
```bash
> make sanity-test                                                    scl scenario build --clean scenarios/sumo/loop
Traceback (most recent call last):
  File "/home/mtuck/repos/SMARTS/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/home/mtuck/repos/SMARTS/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/mtuck/repos/SMARTS/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 800, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (cloudpickle 2.1.0 (/home/mtuck/repos/SMARTS/.venv/lib/python3.8/site-packages), Requirement.parse('cloudpickle<1.7.0,>=1.2.0'), {'gym'})
```
 
**System information**
 
- Operating system & Environment [Please note if using Docker]: Ubuntu Server20.04
- Number of system cores available: 16
- Python version [Please note if using Jupyter]: 3.8
- Python packages [e.g. from `pip freeze`]
- SUMO version: 1.10
- Date when bug occurred: Nov 29 2022

**Comment by saulfield** [comment]
Included in #1981.
