### ISSUE TITLE
NO rendering in visdom?

### ISSUE THREAD

**Issue by SHITIANYU-hue** [huawei-noah/SMARTS#1783]
I run this  example script with wisdom==True, but there is no rendering in wisdom:

![image](https://user-images.githubusercontent.com/38762389/209230569-6cbfb19d-beb9-4b5d-a4b0-5d0c357748e1.png)

`import gym

from smarts.core.agent_interface import AgentInterface, AgentType
from smarts.core.agent import Agent
from smarts.zoo.agent_spec import AgentSpec

class SimpleAgent(Agent):
    def act(self, obs):
        return "keep_lane"

agent_spec = AgentSpec(
    interface=AgentInterface.from_type(AgentType.Laner, max_episode_steps=None),
    agent_builder=SimpleAgent,
)

agent_specs = {
    "Agent-007": agent_spec,
    "Agent-008": agent_spec,
}

env = gym.make(
    "smarts.env:hiway-v0",
    scenarios=["scenarios/sumo/loop"],
    agent_specs=agent_specs,
)

agents = {
    agent_id: agent_spec.build_agent()
    for agent_id, agent_spec in agent_specs.items()
}
observations = env.reset()

for _ in range(1000):
    agent_actions = {
        agent_id: agents[agent_id].act(agent_obs)
        for agent_id, agent_obs in observations.items()
    }
    observations, _, _, _ = env.step(agent_actions)`

**Comment by Adaickalavan** [comment]
Hi @SHITIANYU-hue,

Try the following instructions with the corrected code below.

```bash
$ cd <path/to>/SMARTS
$ python3.8 -m venv ./.venv
$ source ./.venv/bin/activate
$ pip install --upgrade pip wheel setuptools
# Install camera dependency which is required for visualization
$ pip install -e .[camera_obs]
# Build the scenario
$ scl scenario build-all ./scenarios/sumo/loop/
# Launch Visdom in the background
$ visdom & 
# Run the example code
$ python3.8 <path to example code>
# Navigate to http://localhost:8097
```

```python
import gym

from smarts.core.agent_interface import AgentInterface, AgentType
from smarts.core.agent import Agent
from smarts.zoo.agent_spec import AgentSpec

class SimpleAgent(Agent):
    def act(self, obs):
        return "keep_lane"

agent_spec = AgentSpec(
    interface=AgentInterface.from_type(
        AgentType.Laner, 
        max_episode_steps=None,
        rgb=True, # Enable RGB image rendering
    ),
    agent_builder=SimpleAgent,
)

agent_specs = {
    "Agent-007": agent_spec,
    "Agent-008": agent_spec,
}

env = gym.make(
    "smarts.env:hiway-v0",
    scenarios=["scenarios/sumo/loop"],
    agent_specs=agent_specs,
    visdom=True, # Enable Visdom
)

agents = {
        agent_id: agent_spec.build_agent()
        for agent_id, agent_spec in agent_specs.items()
    }

observations = env.reset()

for _ in range(100):
    agent_actions = {
        agent_id: agents[agent_id].act(agent_obs)
        for agent_id, agent_obs in observations.items()
    }
    observations, _, _, _ = env.step(agent_actions)

env.close()
```

**Comment by Adaickalavan** [comment]
We hope the above addresses your question and thus this issue is being closed. Please feel free to reopen this issue if your problem persists or open a new issue for other questions.
