### ISSUE TITLE
Supplying agent_interfaces dict to HiWayEnv results in environment with no agents

### ISSUE THREAD

**Issue by ajlangley** [huawei-noah/SMARTS#1810]
## **BUG REPORT**
**High Level Description**
Just started using SMARTS. I've received several warnings like
` DeprecationWarning: agent_specs has been deprecated in favor of agent_interfaces.  Please update your code.`

However, in `smarts/env/highway_env.py` line 124, `self._agent_inferfaces` is set to `{}`, so that supplying agent interfaces instead of agent specs results in a `HiWayEnv` object with no agents.

**SMARTS version**
1.0.1

**Steps to reproduce the bug**

```
from smarts.core.agent_interface import AgentInterface, AgentType
from smarts.env.hiway_env import HiWayEnv

agent_interface = AgentInterface.from_type(AgentType.Laner)
agent_interfaces = {'Agent1': agent_interface}
env = HiWayEnv(scenarios=['path/to/scenarios/sumo/intersections/2lane'], agent_interfaces=agent_interfaces)
print(env.agent_ids) // prints set()
print(env.reset()) // prints {} 
```
 
**Impact [If known]**
As far as I can tell, you can't create an environment using the preferred `AgentInterface` unless this is resolved.

**Comment by Gamenot** [comment]
Hello @ajlangley. Thanks for the report!

**Comment by Gamenot** [comment]
This should be resolved for develop. It will be merged into master later today.

**Comment by ajlangley** [comment]
Great, thank you!
