### ISSUE TITLE
Trouble running RLlib example with Envision.

### ISSUE THREAD

**Issue by OscarBastardo** [huawei-noah/SMARTS#1853]
**High Level Description**
I want to run the RLlib example from`examples/rl/rllib/rllib.py` with Envision, but I get an error instead of the browser UI.

**Desired SMARTS version**
1.0.3

**Operating System**
Ubuntu 20.04

**Problems**
I want to run the RLlib example from`examples/rl/rllib/rllib.py` with Envision by running:

```
$ python examples/rl/rllib/rllib.py --envision
```

But I get the warning.
```
WARNING:Client:Connection to Envision failed with: [Errno 111] Connection refused.  Try using `--headless` if not using Envision server.
```

And no Envision UI in the browser. Otherwise, training seems to proceed as expected.

I can confirm that Envision is working correctly by running the basic example, which opens the UI on the browser.

```
$ scl scenario build --clean scenarios/sumo/loop
$ scl run --envision examples/control/chase_via_points.py scenarios/sumo/loop
```

**Comment by Gamenot** [comment]
@OscarBastardo thank you for the question. I should note that envision requires the envision server to be running which `scl run` usually handles`.

```
$ scl envision start & # detached or in a different console
& python examples/rl/rllib/rllib.py 
```

**Comment by OscarBastardo** [comment]
@Gamenot thanks for the response. I can confirm this works.
