### ISSUE TITLE
Disappearing waypoints path at intersection

### ISSUE THREAD

**Issue by Adaickalavan** [huawei-noah/SMARTS#1911]
Do we know why the waypoints path appear and then disappear here?

Steps to reproduce:
```
$ git checkout zoo-7
$ cd <path>/SMARTS/examples/rl/baseline
$ python3.8 -m venv ./.venv
$ source ./.venv/bin/activate
$ pip install --upgrade pip wheel
$ pip install -e ./../../../.[camera_obs,dev,doc]
$ pip install -e ./inference/
$ python3.8 train/run.py
```

Here we use the scenario: SMARTS/scenarios/sumo/platoon/merge_exit_agents_1

This example enables sumo-gui by default for debugging. Simulation runs until the lead vehicle (in blue colour) reaches near the exit ramp. Then, a top-down rgb image with the waypoints superimposed in green colour is plotted at each time step. Simply close each of the rgb image to proceed to the next step in the simulation.

The intended outcome is for the social vehicle to turn right into the exit ramp. The social vehicle uses action space `ActionSpaceType.LaneWithContinuousSpeed`. It always executes "change-lane-to-right" action when it is near the exit ramp (i.e., when the rgb images start to be plotted).

Stepping through the simulation, we see that the waypoint path leading towards the exit ramp appear (see first attached image), then disappear for one time step (see second attached image), before re-appearing again. I guess it reappears because the social vehicle continuously attempts to change lane to right. The question is why did the waypoint path leading towards the exit ramp disappear in one of the time step?

Try running a couple of episodes or rebuilding the scenario, if the issue is not seen in the first episode.

![1](https://user-images.githubusercontent.com/24203326/226357856-f14c5866-2ba9-4567-90ea-b0064b9dad99.png)

![2](https://user-images.githubusercontent.com/24203326/226357902-fe94e396-6735-4261-b397-dd176d3f189e.png)

**Comment by saulfield** [comment]
This looks like an issue with how waypoints are generated in junctions. Currently, waypoints are only generated for the nearest junction lane (and the other lanes in that lane's road & outgoing road). But ideally we want waypoints for all junction lanes that the vehicle is on. I've implemented this on on the [saul/waypoint-fixes](https://github.com/huawei-noah/SMARTS/tree/saul/waypoint-fixes) branch, and it appears to fix the issue for this scenario. I will continue testing it and see if it fixes the other waypoint issues we've encountered. Please give it a try and let me know if it seems reasonable for your use cases.

**Comment by Adaickalavan** [comment]
The fix in `saul/waypoint-fixes` works for the `merge_exit_agents_1` scenario.

**Comment by Adaickalavan** [comment]
The following occurred after including code changes from PR #1924.

Here, we consider the "fork" scenario which uses sumo map.

+ In the first time point, all 8 possible waypoint paths are shown. For each waypoint path, the [x,y] position and lane id of the first and last waypoints are given.
    ![Screenshot from 2023-03-27 03-32-41c](https://user-images.githubusercontent.com/24203326/227873740-02ca7a8f-77d2-468d-8b8f-4af213dbb50b.jpg)
    + Path 0: start = [197.84547343  -4.8       ] E0_0 ; end = [270.65966765 -33.06201259] E_right_0
    + Path 1: start = [197.84547343  -4.8       ] E0_0 ; end = [271.83578589 -30.09184327] E_right_1
    + Path 2: start = [197.84547343  -4.8       ] E0_0 ; end = [271.83528384  23.21311439] E_left_0
    + Path 3: start = [197.84547343  -4.8       ] E0_0 ; end = [270.65635034  26.18041407] E_left_1
    + Path 4: start = [197.84547343  -1.6       ] E0_1 ; end = [267.86923477 -31.96042994] E_right_0
    + Path 5: start =  [197.84547343  -1.6       ] E0_1 ; end = [270.90569953 -29.72450233] E_right_1
    + Path 6: start =[197.84547343  -1.6       ] E0_1 ; end = [271.83528384  23.21311439] E_left_0
    + Path 7: start = [197.84547343  -1.6       ] E0_1 ; end = [270.65635034  26.18041407] E_left_1

+ In the immediate next time point, only two possible waypoint paths are shown. Paths 2 and 3 overlap. Paths 6 and 7 overlap. Paths 0, 1, 4, and 5 only have a single waypoint each.
    ![Screenshot from 2023-03-27 03-33-16c](https://user-images.githubusercontent.com/24203326/227873748-72e4f0fb-27a1-4823-a41d-9447b8909cc1.jpg)
    + Path 0: start = [198.5  -1.6] :J_1_4_0 ; end = [198.5  -1.6] :J_1_4_0
    + Path 1: start = [198.5  -1.6] :J_1_4_0 ; end = [198.5  -1.6] :J_1_4_0
    + Path 2: start = [198.43632137  -1.59521932] :J_1_6_0 ; end = [273.69544157  23.94783423] E_left_0
    + Path 3: start = [198.43632137  -1.59521932] :J_1_6_0 ; end = [273.69544157  23.94783423] E_left_0
    + Path 4: start = [198.5  -1.6] :J_1_4_1 ; end = [198.5  -1.6] :J_1_4_1
    + Path 5: start = [198.5  -1.6] :J_1_4_1 ; end = [198.5  -1.6] :J_1_4_1
    + Path 6: start = [198.3120145   -1.61422259] :J_1_6_1 ; end = [272.5165399  26.9150533] E_left_1
    + Path 7: start = [198.3120145   -1.61422259] :J_1_6_1 ; end = [272.5165399  26.9150533] E_left_1

Issues:
1. Preferably all legal waypoint paths within reasonable distance should be made available to the agent.
1. Overlapped waypoint paths and single-point waypoint paths should be avoided.

**Comment by saulfield** [comment]
@Adaickalavan I have a proposed fix up on the `saul/sumo-junction-waypoints` branch. Please try it out and let me know if it's adequate. Here's a video of what the fork scenario looks like with it:

https://user-images.githubusercontent.com/17256344/229229352-713f51c3-34bb-4066-85e6-5886b482ed56.mp4

**Comment by Adaickalavan** [comment]
@saulfield I tried `saul/sumo-junction-waypoints`, it appears adequate and can be made into a PR.

**Comment by Adaickalavan** [comment]
+ In roads (see top image), the waypoint paths is ordered depth-first, right to left.
+ In junctions (see bottom image), the waypoint paths appear ordered differently as E_right_0, E_left_0, E_right_1, E_left_1, instead of right to left as E_right_0, E_right_1, E_left_0, E_left_1 .
+ If possible, could we have the waypoint paths always ordered depth-first, right to left?

![Screenshot from 2023-04-12 18-58-06](https://user-images.githubusercontent.com/24203326/231606215-b8b2592a-0289-4e72-a85d-7d0f72b3a47f.png)
