### ISSUE TITLE
[Bug Report] rl/racing example conflict between dependencies

### ISSUE THREAD

**Issue by atanas-kom** [huawei-noah/SMARTS#1912]
### High Level Description

When trying to setup rl/racing a conflict between dependencies of racing, racing==0.1.1, smarts and smarts[camera-obs]==1.0.0 occurs.

### Version

SMARTS 1.0.8

### Steps to reproduce the bug

```shell
## Setup

$ git clone https://github.com/huawei-noah/SMARTS.git
$ cd <path>/SMARTS/examples/rl/racing
$ python3.7 -m venv ./.venv
$ source ./.venv/bin/activate
$ pip install --upgrade pip
$ pip install -e .
```

### System info

Dual boot Ubuntu 22.04.1 **and** Oracle VM VirtualBox Ubuntu 22.04.1
python3.7 **and** python3.8

### Error logs and screenshots

<pre><font color="#C01C28">ERROR: Cannot install racing, racing==0.1.1, smarts and smarts[camera-obs]==1.0.0 because these package versions have conflicting dependencies.</font>

The conflict is caused by:
    racing 0.1.1 depends on numpy&lt;=1.23.0 and &gt;=1.19
    smarts[camera-obs] 1.0.0 depends on numpy&gt;=1.19.5
    tensorflow 2.4.0 depends on numpy~=1.19.2
    tensorflow-probability 0.12.2 depends on numpy&gt;=1.13.3
    gymnasium 0.27.0 depends on numpy&gt;=1.21.0

</pre>

**Comment by Gamenot** [comment]
Hello, @atanas-kom, thank you for the report. This appears to be fixed by bumping up the version of. A fix is going in.
