### ISSUE TITLE
Strict waypoint paths in Argoverse map

### ISSUE THREAD

**Issue by Adaickalavan** [huawei-noah/SMARTS#1927]
Steps to reproduce:
```
$ git checkout zoo-9
# Place scenario id "c624608b-fd20-43c9-bc2c-c4181ce9dafa" in `SMARTS/argoverse/data/` folder
$ cd <path>/SMARTS/examples/rl/baseline
$ python3.8 -m venv ./.venv
$ source ./.venv/bin/activate
$ pip install --upgrade pip wheel
$ pip install -e ./../../../.[camera_obs,argoverse]
$ pip install -e ./inference/
# Enable envision for debugging
$ scl envision start &
$ python3.8 train/run.py --head
# Scenario used: SMARTS/scenarios/argoverse/platoon/map_3_agents_1/scenario.py
```

Simulation runs until the ego vehicle (in red colour) reaches near the intersection. Then, a top-down rgb image with the waypoints superimposed in green colour is plotted at each time step. Simply close each of the rgb image to proceed to the next step in the simulation.

Stepping through the simulation, we see the ego's turn-left and turn-right waypoints appear as it reaches the intersection. However, both turn-left and turn-right waypoints disappear simultaneously very early on, making the potential waypoints too strict. This is especially true for the turn-left waypoints which disappear too quickly although the turn-left still appears some distance ahead. 

Is it reasonable to make the potential waypoint paths slightly less strict?

Two consecutive images are shown below depicting this phenomenon. The embedded rgb images, in each image below, show three consecutive time points.

![Screenshot from 2023-03-25 21-00-42](https://user-images.githubusercontent.com/24203326/227803745-db5f03d7-ac08-45be-a65f-a8d005c89404.png)

![Screenshot from 2023-03-25 21-01-06](https://user-images.githubusercontent.com/24203326/227803749-08db6791-44b9-475e-b312-5e1f72b05205.png)

**Comment by Gamenot** [comment]
This is potentially related to #1847
