### ISSUE TITLE
Incorrect social agent position display in Envision 

### ISSUE THREAD

**Issue by Adaickalavan** [huawei-noah/SMARTS#1928]
Here, we consider the "fork" scenario which uses sumo map, has one social agent and one ego agent. The [x, y, z] position of the social agent is shown as [20.83, -1.62, -0.02] which seems incorrect. The social agent's correct position should be x > 22.27 and y =~ -4.79 .

![Screenshot from 2023-03-27 04-23-32](https://user-images.githubusercontent.com/24203326/227884326-28d5911a-c40f-4f72-a4e6-c57e86a3cc15.png)

**Comment by Gamenot** [comment]
This is concerning because it could mean that the information received from the `SumoTrafficSimulation` could be incorrect.
