### ISSUE TITLE
Creating, training and registering new agents

### ISSUE THREAD

**Issue by atanas-kom** [huawei-noah/SMARTS#1943]
### High Level Description

Hi, I am trying to create a simple actor-critic model agent, to test on the `driving_smarts==0.0` benchmark. I understand that in order for it to work with the benchmark it needs to use a `TargetPose` or `RelativeTargetPose` action space (with `Boid` interface?, I am struggling to understand the relation between a specific interface and action space). I get that I need to choose an agent's policy and interface in an `agent.py` sort of file, but what about training and saving the agent, do I need to register it for everything to work? The only reference to this I did find in the documents only mentions the following with no specifics:
`First, add the new agent to [zoo/policies](https://github.com/huawei-noah/SMARTS/tree/master/zoo/policies). It should contain

- package setup file,
- inference code with prebuilt model, and
- algorithm explanation.

Then, register the newly added zoo agent in [zoo/policies/__init__.py](https://github.com/huawei-noah/SMARTS/tree/master/zoo/policies/__init__.py).`

Would you be able to walk me through the process in simple terms. 
Appologies for asking a question which might be obvious to someone more experienced, I have only worked with trainig reinforcement learning agents with `OpenAI gym` in Jupyter Notebooks.
Thank you!

### Version

1.0.11

### Operating System

Ubuntu 20.04

**Comment by atanas-kom** [comment]
I realised we are talking about continuous actions and space, hence I would like to apply a simple actor-critic model, not q-learning. Appologies.

**Comment by Adaickalavan** [comment]
Hi @atanas-kom,

I see that you would like to develop a reinforcement learning model and evaluate it on the `driving_smarts_2022` benchmark.

We are in the midst of developing a new benchmark, named `driving_smarts_2023.3`. The mechanics of using a SMARTS environment, training models, and evaluating models in benchmarks, are similar across different benchmarks, with the only difference being the underlying observation/action spaces, tasks, maps, and scoring formula.

Consider reading the [docs](https://smarts.readthedocs.io/en/latest/benchmarks/driving_smarts_2023_3.html) on `driving_smarts_2023.3` benchmark. It explains the task, observation space, action space, and required code structure. Additionally, an [example](https://github.com/huawei-noah/SMARTS/blob/master/examples/rl/platoon) for training & saving a model, registering an user's agent, and evaluating the model, is provided with instructions. Please note that the `scl benchmark run driving_smarts_2023_3 examples.rl.platoon.inference:contrib-agent-v0 --auto-install` [command](https://smarts.readthedocs.io/en/latest/benchmarks/driving_smarts_2023_3.html#evaluate), and scoring, would only be functional after PR #1952 is merged. In the meantime, do the following instead to evaluate the given example after training.

```bash
# On terminal-A
$ cd <path>/SMARTS/examples/rl/platoon
$ source ./.venv/bin/activate
$ scl envision start
# Open http://localhost:8081/

# On a different terminal-B
$ cd <path>/SMARTS/examples/rl/platoon
$ source ./.venv/bin/activate
$ python3.8 train/run.py --mode=evaluate --model=<path>/SMARTS/examples/rl/platoon/train/logs/<folder>/<model>.zip --head
```

On the question of "_relation between a specific interface and action space_", the user is able to specify their desired action space through the agent interface as shown [here](https://github.com/huawei-noah/SMARTS/blob/878ca2b7a0f72a0f47bdb1f935d69f3aa4d3ea66/examples/rl/platoon/inference/__init__.py#L10-L23). SMARTS provides several action spaces, see [here](https://smarts.readthedocs.io/en/latest/api/smarts.core.controllers.html#smarts.core.controllers.ActionSpaceType), but only selected action spaces are allowed in the benchmarks. For example, the `driving_smarts_2023.3` benchmark currently only allows [`ActionSpaceType.Continuous`](https://smarts.readthedocs.io/en/latest/api/smarts.core.controllers.html#smarts.core.controllers.ActionSpaceType.Continuous).

I hope that walking through the example given for `driving_smarts_2023.3` benchmark helps to provide a better understanding on how to use SMARTS and its benchmarks. Wishing you the best to achieve an excellent driving model on the `driving_smarts_2022` benchmark.

**Comment by Adaickalavan** [comment]
We hope the above addresses your question and thus this issue is being closed. Please feel free to reopen this issue if your problem persists or open a new issue for other questions.
