### ISSUE TITLE
[Feature request] Render pedestrians in camera observations

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#1992]
### Motivation

Pedestrians currently show up in the low-dimension observations but not in the camera observations. There is a need to render them in the observations to allow for agents that only use cameras to be able to interact with pedestrians.

### Proposal

Pedestrians should show up in observations. Pedestrians should be accented to show up more distinctly in low-resolution images if possible. Perhaps a pedestrian-specific colour?

This might be a useful point to change to update the renderer using the simulation frame instead of direct updates using per-vehicle vehicle states.

**Comment by saulfield** [comment]
It looks like pedestrians do show up in the camera observations already (see below image). Any thoughts on what enhancements we should make to them (if any)? Perhaps a distinct colour, size increase, or some other visual indicator added to them, like a circle?

![{ Type Agent_0-Top-Down RGB }(3)](https://user-images.githubusercontent.com/17256344/235488364-002ea407-2dc4-4162-ade3-0d67b0828b26.png)
