### ISSUE TITLE
[Feature request] Render traffic lights in envision

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#1993]
### Motivation

Traffic lights are currently not represented in the envision visualization which can make it difficult to understand why traffic is behaving in the way it is.

### Proposal

I could suggest that traffic lights be represented similarly to how they are represented in `sumo-gui`. See: [SUMO signal state definitions](https://sumo.dlr.de/docs/Simulation/Traffic_Lights.html#signal_state_definitions).

**Comment by smarts-project** [comment]
![image](https://github.com/huawei-noah/SMARTS/assets/69439799/6e59d8d1-6a3c-4fac-a313-36a8196720b1)
