### ISSUE TITLE
[Feature request] Conditional vehicle takeover

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#2002]
### Motivation

We need a way to express conditions under SMARTS systems should change the controlling owner of a vehicle

Cases:
- After another vehicle shows up in the simulation
- Vehicle is on-road.
- If the vehicle is a particular type.
- When vehicle is released by another agent.
- Delay # seconds.

This is a companion to #2001 

### Proposal

The first step to solving these problems is to provide an interface for conditions that allows for combining them. The conditions should purely declare if a condition is met and nothing else.

### Additional context

Issue #1965 is the first attempt at this.

**Comment by qianyi-sun** [comment]
another case could be "if the vehicle has a particular id", to exclude the leader in following scenarios as well
