### ISSUE TITLE
[Help Request] How to get the current number of the episode?

### ISSUE THREAD

**Issue by rodrigogutierrezm** [huawei-noah/SMARTS#2021]
### High Level Description

Hi folks,

Do you know how can I get the current number of the episode? I am running the hiway_env.py scenario, but I do not know how I can retrieve that information in order to obtain the tracked agents per traffic scenario.

### Version

1.0.11

**Comment by Gamenot** [comment]
Hello @rodrigogutierrezm, could you clarify what you mean: 

- You wish to get the number of agents in the current episode?
- You wish to get the sequential episode count?
