### ISSUE TITLE
Single waypoint showing in wrong lane

### ISSUE THREAD

**Issue by Ceudan** [huawei-noah/SMARTS#2028]
### High Level Description

There is still a single waypoint showing per incorrect lane. For tracks 1 and 2, the only showing waypoints should be those on a path/lane leading to the destination. Specifically, in certain situations the incorrect waypath has n=1 points, while the correct waypath has n=80 points. N should either be 0 or 80 n∈{0,80}, either the path is correct or incorrect. A partial waypoint with n=1 points should not exist.

### Version

zoo-8

### Steps to reproduce the bug

```shell
Branch = zoo-8
Scenarios = "merge_exit_sumo_t_agents_1","0a7488fc-30e6-4124-973b-80c5c8769df5_agents_1", there may be more
Drive the agent to the point where the correct waypath diverges from the main road. 
Observe the behavior of the waypoints in the non-turning lane. 
Video demonstration attached.
```

### Error logs and screenshots
![single_waypoint](https://github.com/huawei-noah/SMARTS/assets/24203326/50a1447c-d41e-4319-b045-a43039fdbe18)

### Impact (If known)

Any metric which uses location of the correct waypath (track 1 and 2) may be compromised, as there still exists points in the incorrect lanes.

**Comment by Gamenot** [comment]
This was also noted in https://github.com/huawei-noah/SMARTS/issues/2023
