### ISSUE TITLE
[Bug Report] ScenarioMetadata requires keyword arguments, causing many errors during scenario construction

### ISSUE THREAD

**Issue by lurenlym** [huawei-noah/SMARTS#2057]
### High Level Description

#2037  ScenarioMetadata is required to use keyword arguments, like this: 
```
scenario_metadata=ScenarioMetadata(`
actor_of_interest_re_filter="Leader-007",
actor_of_interest_color=Colors.Blue,
)
```
 but many scenarios, like [this one](https://github.com/huawei-noah/SMARTS/blob/88806a6e9eade352af8a342152270307d47560a6/scenarios/sumo/vehicle_following/merge_exit_sumo_agents_1/scenario.py#LL95C21-L95C21), still use positional arguments, which will lead to a TypeError during construction.

### Version

master

### Steps to reproduce the bug

use another scenario to train a rl model

### System info

ubuntu 18.04

### Error logs and screenshots

![1686109769244](https://github.com/huawei-noah/SMARTS/assets/26338549/7e02336b-4db8-4bd3-a315-326ebad7b621)

**Comment by Adaickalavan** [comment]
Hi @lurenlym,

This issue will be fixed by PR #2044 when it is merged.
