### ISSUE TITLE
[Bug Report] IdEntryTactic reset timestamp to 0

### ISSUE THREAD

**Issue by Edward11235** [huawei-noah/SMARTS#2070]
### High Level Description

For each iteation, I have 1000 iterations, which means that I call step() method 1000 times and my episode should be 100s given that my environment runs at 10 frames per second.
On my scenario.py, when I define Mission for ego_mission, I set entry_tactic=IdEntryTactic(start_time=0, actor_id="car-E0_0_0-E0_0_max--59446--11620-0-0.3".
The traffic vehicle with actor_id="car-E0_0_0-E0_0_max--59446--11620-0-0.3" is created at 22.4 seconds. After I 'hijack' this car, my episode runs for 122.4 (= 100 + 22.4) seconds, which means that time is reset to zero when I take control of this car.
This is not supposed to happen.

### Version

I am using master branch.

### System info

Ubuntu 20.04, Python 3.8

**Comment by Gamenot** [comment]
Hello @Edward11235, to be clear the following is true:

- "car-E0_0_0-E0_0_max--59446--11620-0-0.3" is created at 22.4s
- "car-E0_0_0-E0_0_max--59446--11620-0-0.3" is taken over by the ego at 22.4s (after 224 steps from 1 call to `reset()` until an ego agent enters into the simulation)
- Ego has control of "car-E0_0_0-E0_0_max--59446--11620-0-0.3" for 100s (1000 steps, 1000 calls to `step()`)
- Total elapsed simulation time is 122.4s

If this is the behaviour you are seeing, it is intended. We have to simulate the time leading up to the ego's entry into the simulation. You can reduce this if you wish by checking against `env.smarts.step_count` which will give you the steps taken.
