### ISSUE TITLE
Automate long running tests

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#208]
Automation of a long running test case for SMARTS to avoid test myopia.

Test criteria:
- [ ] Runs for a week successfully
- [ ] Runs to 1 million steps successfully
- [ ] Reaches ~50k episodes successfully
- [ ] Uses a testing set of 10k different scenarios

**Comment by Adaickalavan** [comment]
This issue is being closed as it is superceded by issue #489.
