### ISSUE TITLE
[Help Request]  Debugging Needs During Training and Visualizing Specific Episodes

### ISSUE THREAD

**Issue by l1xiao** [huawei-noah/SMARTS#2096]
### High Level Description

Hello,

I have some debugging needs during the training process(e10_drive). For instance, I have implemented a reward item based on the distance to the boundary and I would like to verify its correctness. Additionally, I am interested in viewing the replays and corresponding logs of failed cases during training. These needs can be summarized as: How can I inspect specific episodes frame by frame, and perform visualization or logging on them?

Has this requirement been implemented? If so, could you provide an example? If not, how should I utilize the existing envision to select a specific episode（or rollout）, print logs, and add visualization content?

I have another question. I noticed there is a "Record" button in Envision, but no files are saved after clicking it. How should I use this feature?

Thank you for your assistance.

### Version

1.4.0

**Comment by Adaickalavan** [comment]
Hi @l1xiao,

A simple method for precise frame-by-frame visualization and debugging would be to plot the agent's observation image at every iteration. The plotter can be included inside the reward function and inside the preprocess function. 

For example code which includes plotter functions for debugging, see the following:
+ Plot agent's observation image inside the [reward function](https://github.com/huawei-noah/SMARTS/blob/ba31fe5772acb5517263efc15e23e350617da202/examples/e10_drive/train/reward.py#L92-L95).
 + Plot agent's observation image inside the [preprocess function](https://github.com/huawei-noah/SMARTS/blob/ba31fe5772acb5517263efc15e23e350617da202/examples/e10_drive/train/preprocess.py#L44-L47).
