### ISSUE TITLE
[Help Request] Problems encountered in SMARTS simulation using ROS

### ISSUE THREAD

**Issue by piqiuni** [huawei-noah/SMARTS#2103]
### High Level Description

Hello,
I want to use ROS for testing, but I get an error in "rosrun smarts_ros ros_driver.py":
> smarts.core.smarts.SMARTSDestroyedError: ('ERROR: A SMARTS instance may have been deleted by gc before a call to destroy. Please explicitly call `del obj` or `SMARTS.destroy()` to make this error go away.', AttributeError("'SMARTS' object has no attribute '_agent_manager'"))

I didn't see any introduction to the ROS interface in the document. Does the new version of SMARTS still support the use of ROS?
Thanks!

### Version

1.4.0

### Operating System

ubuntu 20.04

**Comment by Gamenot** [comment]
Generally we have not kept up support for use of ROS for recent versions of `SMARTS`. It may be broken at this time.

**Comment by piqiuni** [comment]
Thanks!
