### ISSUE TITLE
[Help Request] Can't find visualization in Envision for waymo dataset

### ISSUE THREAD

**Issue by l1xiao** [huawei-noah/SMARTS#2109]
### High Level Description

I've been trying to use egoless to play the Waymo dataset as the documentation descriped, but I've noticed that I can't see the map and vehicle logs in the Envision visualization. Could you please help me understand what the issue might be?
The waymo dataset version is 1.1.
`python3.8 e1_egoless.py`
![image](https://github.com/huawei-noah/SMARTS/assets/6694585/8272908a-2e95-4a32-ab37-2869bb0a443c)
![image](https://github.com/huawei-noah/SMARTS/assets/6694585/18dacc82-3b33-45f2-8dab-486a7f55a4e5)
Here is scenario.py:
![image](https://github.com/huawei-noah/SMARTS/assets/6694585/0143b21b-d60e-4b76-873f-f3dd864fec4d)
Here is e1_egoless.py:
<img width="653" alt="image" src="https://github.com/huawei-noah/SMARTS/assets/6694585/a32c73e6-2837-49ba-94c8-012539c2c456">

I also tried in argoverse dataset and met the same problem.
### Version

1.4

### Operating System

ubuntu20.04

**Comment by Gamenot** [comment]
I will test this out tomorrow.

**Comment by Gamenot** [comment]
From what I found the simulation is there but the camera is not centred on it. I will see if I can apply a fix.
