### ISSUE TITLE
Update zoo RLAgent to Tensorflow 2.2

### ISSUE THREAD

**Issue by davidrusu** [huawei-noah/SMARTS#211]
Currently RLAgent's version of tensorflow conflicts with the version of tensorflow used by SMARTS.

AC:
 * RLAgent has been updated to use the same version of TF as that used by SMARTS
 * We've updated the RLAgent version / built a new wheel
 * Scenarios depending on the RLAgent have been updated to use the new RLAgent.

**Comment by Gamenot** [comment]
SMARTS as a platform should work with agents that are using any tensorflow version.
