### ISSUE TITLE
[Help Request] Wanna to know about traffic model

### ISSUE THREAD

**Issue by Frzgunr1** [huawei-noah/SMARTS#2119]
### High Level Description

      The control model of traffic in smarts is not clear, it is controlled by sumo or smarts and can be customized with some parameters. It appears to be unresponsive to the behavior of surrounding vehicles. 
       However, in `scenarios/sumo/loop`, traffic slows down when it catches up with the car in front of it and continues to run for 20 minutes without collision. But in my own program ego_vehicle is a laner class agent and traffic will collide with ego_vehicle.
       Or perhaps it is due to insufficient training of my model. But I really want to know what the underlying model of the traffic class is. If it is IDM, please let me know. And is it possible to customize the traffic control model? (Compared to social agents, this does not require returning information, so the speed will be faster when the scale is large.)

### Problems
     The existing model looks like IDM, but I'm not sure.  I need to customize HDV for a smarter operational model (at least IDM) 
     What modifications need to be made to customize the model for traffic if possible? 
     Thank u very much, looking forward to ur reply!

### Version

1.4.0

### Operating System

ubuntu 20.04

**Comment by Gamenot** [comment]
Hello @Frzgunr1, I am not quite certain of your intention here so I am going to try to describe what I think I am hearing.

- You are trying to create a better HDV. 
- The current traffic flow model is not performing as you expect.
- You wish to configure the traffic flow model.

## Actions

### Changing existing models in scenario studio
The traffic model can be configured in the scenario

#### SUMO
My understanding is that if you are using `SUMO` traffic the model is a modified `Krauss` as is noted on [this page](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#car-following_models.) They mention it is a combination of `Krauss` and safety metrics.

SUMO traffic can be selected in the scenario this way:

```python
```

#### SMARTS
If you are using `SMARTS` traffic it is a bit less clear, it is mostly similar to the SUMO `Krauss` implementation but the lane changing model became more integrated.


### Injected
Another possibility is that you can implement your own `TrafficProvider` if necessary as noted here:

https://github.com/huawei-noah/SMARTS/issues/1870#issuecomment-1480381436

**Comment by Frzgunr1** [comment]
Thank you @Gamenot      very much for your suggestion!
      I checked `SMARTS/smarts/core/sumo_traffic_simulation.py`s source code and SUMO's docs, and as I understand it, smarts is created by the `_ create_vehicle()` method to generate the vehicle flow.
     So, just add
` self._traci_conn.vehicle.add(vehicle_id, carFollowModel="IDM")` 
at the end of the method 
`_create_vehicle()` 
to realize that the car flow becomes an IDM model.The other sumo heel chi models are also similar.
     I'm not sure if my understanding and modification is correct, could you please confirm this for me, thank you very much!
