### ISSUE TITLE
I want to know the dynamic or kinematic model of vehicles in SMARTS

### ISSUE THREAD

**Issue by dailf678** [huawei-noah/SMARTS#2120]
### High Level Description

When I select ActuatorDynamic for my ActionSpaceType, I need to set throttle, brake, and steering_ Rate. But I don't know the dynamics or kinematic models inside the vehicle.

### Version

latest

### Problems

In your paper "SMARTS: Scalable Multi-Agent Reinforcement
Learning Training School for Autonomous Driving" that you mentioned "Physics is supported through the vehicle provider, which simulates the specific physical vehicle model and exposes a control interface at different levels of abstraction: throttle stroke training, trajectory tracking, and lane following." I would like to know if it is possible to set up a "physical vehicle model."

**Comment by Gamenot** [comment]
See https://github.com/huawei-noah/SMARTS/issues/2116.
