### ISSUE TITLE
[Help Request] Can not find lane_position from observations

### ISSUE THREAD

**Issue by JiyuanTHU** [huawei-noah/SMARTS#2142]
### High Level Description

I want to use the lane_position information for RL training. But, even if I have set the lane_position=True, explicitly, I still not get the lane_postion from the env output variables. 

### Version

1.4.0

### Operating System

ubuntu20.04

### Problems

![image](https://github.com/huawei-noah/SMARTS/assets/48142953/85c1b16b-e51f-49b5-ab59-afed650430fc)
I want to use the lane_position information for RL training. But, even if I have set the lane_position=True, explicitly, I still not get the lane_postion from the env output variables.

**Comment by Gamenot** [comment]
Hello @JiyuanTHU, apologies for this oversight, the formatted observations do not yet contain lane position. You can still still currently get that information from the unformatted observations that are included in `info`:

`info[AGENT_ID].env_obs.ego_vehicle_state.lane_position`

**Comment by Gamenot** [comment]
#2143 fixes this.
