### ISSUE TITLE
安装官方文档训练好模型后使用scl zoo进行评估出现debug参数缺失问题

### ISSUE THREAD

**Issue by Ppig01** [huawei-noah/SMARTS#2146]
### High Level Description

安装官方文档训练好模型后使用scl zoo进行评估出现debug参数缺失问题

### Version

smarts2.0

### Operating System

ubuntu 20.04

### Problems

(.venv) root@autodl-container-f4b94a8e05-b0338b83:~/autodl-tmp/SMARTS# scl benchmark run driving_smarts_2023_1 examples.e10_drive.inference:contrib-agent-v0 --auto-install
Looking in indexes: http://mirrors.aliyun.com/pypi/simple
Requirement already satisfied: ray<2.6.0,>2.0 in ./.venv/lib/python3.8/site-packages (2.5.1)
Requirement already satisfied: attrs in ./.venv/lib/python3.8/site-packages (from ray<2.6.0,>2.0) (23.2.0)
Requirement already satisfied: click>=7.0 in ./.venv/lib/python3.8/site-packages (from ray<2.6.0,>2.0) (8.1.7)
Requirement already satisfied: filelock in ./.venv/lib/python3.8/site-packages (from ray<2.6.0,>2.0) (3.13.3)
Requirement already satisfied: jsonschema in ./.venv/lib/python3.8/site-packages (from ray<2.6.0,>2.0) (4.21.1)
Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in ./.venv/lib/python3.8/site-packages (from ray<2.6.0,>2.0) (1.0.8)
Requirement already satisfied: packaging in ./.venv/lib/python3.8/site-packages (from ray<2.6.0,>2.0) (24.0)
Requirement already satisfied: protobuf!=3.19.5,>=3.15.3 in ./.venv/lib/python3.8/site-packages (from ray<2.6.0,>2.0) (3.20.1)
Requirement already satisfied: pyyaml in ./.venv/lib/python3.8/site-packages (from ray<2.6.0,>2.0) (6.0.1)
Requirement already satisfied: aiosignal in ./.venv/lib/python3.8/site-packages (from ray<2.6.0,>2.0) (1.3.1)
Requirement already satisfied: frozenlist in ./.venv/lib/python3.8/site-packages (from ray<2.6.0,>2.0) (1.4.1)
Requirement already satisfied: requests in ./.venv/lib/python3.8/site-packages (from ray<2.6.0,>2.0) (2.31.0)
Requirement already satisfied: grpcio<=1.51.3,>=1.32.0 in ./.venv/lib/python3.8/site-packages (from ray<2.6.0,>2.0) (1.51.3)
Requirement already satisfied: numpy>=1.16 in ./.venv/lib/python3.8/site-packages (from ray<2.6.0,>2.0) (1.23.1)
Requirement already satisfied: importlib-resources>=1.4.0 in ./.venv/lib/python3.8/site-packages (from jsonschema->ray<2.6.0,>2.0) (6.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in ./.venv/lib/python3.8/site-packages (from jsonschema->ray<2.6.0,>2.0) (2023.12.1)
Requirement already satisfied: pkgutil-resolve-name>=1.3.10 in ./.venv/lib/python3.8/site-packages (from jsonschema->ray<2.6.0,>2.0) (1.3.10)
Requirement already satisfied: referencing>=0.28.4 in ./.venv/lib/python3.8/site-packages (from jsonschema->ray<2.6.0,>2.0) (0.34.0)
Requirement already satisfied: rpds-py>=0.7.1 in ./.venv/lib/python3.8/site-packages (from jsonschema->ray<2.6.0,>2.0) (0.18.0)
Requirement already satisfied: charset-normalizer<4,>=2 in ./.venv/lib/python3.8/site-packages (from requests->ray<2.6.0,>2.0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.8/site-packages (from requests->ray<2.6.0,>2.0) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.venv/lib/python3.8/site-packages (from requests->ray<2.6.0,>2.0) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in ./.venv/lib/python3.8/site-packages (from requests->ray<2.6.0,>2.0) (2024.2.2)
Requirement already satisfied: zipp>=3.1.0 in ./.venv/lib/python3.8/site-packages (from importlib-resources>=1.4.0->jsonschema->ray<2.6.0,>2.0) (3.18.1)
Traceback (most recent call last):
  File "/root/autodl-tmp/SMARTS/.venv/bin/scl", line 8, in <module>
    sys.exit(scl())
  File "/root/autodl-tmp/SMARTS/.venv/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/root/autodl-tmp/SMARTS/.venv/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/root/autodl-tmp/SMARTS/.venv/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/autodl-tmp/SMARTS/.venv/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/autodl-tmp/SMARTS/.venv/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/autodl-tmp/SMARTS/.venv/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/root/autodl-tmp/SMARTS/cli/benchmark.py", line 72, in run
    run_benchmark(
  File "/root/autodl-tmp/SMARTS/smarts/benchmark/__init__.py", line 111, in run_benchmark
    entrypoint(
TypeError: benchmark_from_configs() got an unexpected keyword argument 'debug_log'

**Comment by Gamenot** [comment]
Fixed https://github.com/huawei-noah/SMARTS/releases/tag/v2.0.1
