### ISSUE TITLE
[Help Request] Why "ModuleNotFoundError: No module named 'gymnasium' " 

### ISSUE THREAD

**Issue by Silkbamboo** [huawei-noah/SMARTS#2151]
### High Level Description

when I want to run a example, the error is "ModuleNotFoundError: No module named 'gymnasium' "  but I can find 'gymnasium' in '/smarts/env/gymnasium'

### Version

2.0.1

### Operating System

ubuntu 18.04

### Problems

when I want to run a example, the error is ```ModuleNotFoundError: No module named 'gymnasium'  ``` but I can find ```'gymnasium' ```in ```SMARTS/smarts/env/gymnasium```

```
(.venv) root@czjvm:/home/czj/SMARTS# scl run examples/e1_egoless.py 
Traceback (most recent call last):
  File "examples/e1_egoless.py", line 4, in <module>
    import gymnasium as gym
ModuleNotFoundError: No module named 'gymnasium'
Killed
```
![image](https://github.com/huawei-noah/SMARTS/assets/93428473/86ccbde6-e6de-469f-99d0-9107651af0c8)

![image](https://github.com/huawei-noah/SMARTS/assets/93428473/89cbe3d5-8fc9-4552-af65-4be44bdf9cdb)

**Comment by Gamenot** [comment]
Hello, this would be the result of not installing smarts dependencies.

Please follow these instructions: https://smarts.readthedocs.io/en/latest/setup.html#development
