### ISSUE TITLE
[Help Request] ModuleNotFoundError: No module named 'contrib_policy'

### ISSUE THREAD

**Issue by Silkbamboo** [huawei-noah/SMARTS#2153]
### High Level Description

  I want to run the ```examples/e10_drive``` 

### Version

2.0.1

### Operating System

22.04

### Problems

when I run ```(.venv) ~/SMARTS/examples/e10_drive#  python3.8 train/run.py```
 an error occurred:
```(.venv) ~/SMARTS/examples/e10_drive#  python3.8 train/run.py
Traceback (most recent call last):
  File "train/run.py", line 18, in <module>
    import inference
  File "~/SMARTS/examples/e10_drive/inference/__init__.py", line 1, in <module>
    from contrib_policy.policy import Policy
ModuleNotFoundError: No module named 'contrib_policy'
```

**Comment by Gamenot** [comment]
It is not clear but for this you would need to install the inference directory:

```bash
~/SMARTS/examples/e10_drive# pip install -e ./inference/
```

The example setup is covered here: https://smarts.readthedocs.io/en/latest/benchmarks/driving_smarts_2023_1.html#example

**Comment by Silkbamboo** [comment]
> It is not clear but for this you would need to install the inference directory:
> 
> ```shell
> ~/SMARTS/examples/e10_drive# pip install -e ./inference/
> ```
> 
> The example setup is covered here: https://smarts.readthedocs.io/en/latest/benchmarks/driving_smarts_2023_1.html#example

Thank you very much ,I have solved it. The problem is that I dont pip install inference.
