### ISSUE TITLE
Publish OpEn to PyPI

### ISSUE THREAD

**Issue by liamchzh** [huawei-noah/SMARTS#223]
The OpEn agent has a dependency on the [generated bindings](https://github.com/huawei-noah/SMARTS/tree/master/zoo/policies/python-bindings-open-agent-solver), we need to pack all these packages to be at the same level. 

@davidrusu mentioned:
> The name of that package comes from the generated rust project. so we need to trace through how that generated rust project gets its name and see if we can inject a smarts prefix.

**Comment by liamchzh** [comment]
I had been fighting the `python-bindings-open-agent-solver` but could find a way to pack a *.whl and install it due to ` No matching distribution found for python-bindings-open-agent-solver`

I also found:
> Dependency links support has been dropped by pip starting with version 19.0 

according to [Dependencies Management in Setuptools](https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html?highlight=dependency_links#dependencies-that-aren-t-in-pypi)

**Comment by cinjon** [comment]
Same issue.

**Comment by davidrusu** [comment]
I found that I could publish the open-agent (to test.pypi.org) via:

```bash
cd zoo/policies

# Upload the python bindings package first
twine upload --repository-url https://test.pypi.org/legacy/ python-bindings-open-agent-solver/*

# Then upload the OpEn agent
twine upload --repository-url https://test.pypi.org/legacy/ open-agent/open_agent-0.1.187-py3-none-any.whl
```

The uploaded agent is here:

https://test.pypi.org/project/open-agent/

I didn't go through this process on the main pypi instance, but it should be the same.

**Comment by liamchzh** [comment]
This works. Thanks.

I was trying to pack bindings together with OpEn last week. Bit it is easier to publish if we separate them.

I published them on PyPI, cc invited @Gamenot as a collaborator.
* [open-agent](https://pypi.org/project/open-agent/)
* [python-bindings-open-agent-solver](https://pypi.org/project/python-bindings-open-agent-solver/)

**Comment by davidrusu** [comment]
Yeah, it's not easy to pack them together since it's easier to compile the bindings separately for each platform and have a platform independent open-agent package which will pull in the platform bindings
