### ISSUE TITLE
Support multiple traffic history data in one scenario

### ISSUE THREAD

**Issue by zbzhu99** [huawei-noah/SMARTS#226]
When generating scenarios with history replay vehicles, we specify the traffic history files to be used via the `traffic_histories` parameter. This parameter currently supports passing in a list containing file names, but actually, only the first file in that list will be used.

The use of multiple historical data files (replayed one by one) in one scenario should be supported.

Example scenario and related traffic history files:

[interaction_dataset_merging.zip](https://github.com/huawei-noah/SMARTS/files/5603745/interaction_dataset_merging.zip)

**Comment by liamchzh** [comment]
* https://github.com/huawei-noah/SMARTS/blob/master/smarts/core/scenario.py#L529
* https://gitlab.smartsai.xyz/smarts/SMARTS/-/merge_requests/758/diffs
* https://gitlab.smartsai.xyz/smarts/imitation-learning/-/tree/master/scenarios
