### ISSUE TITLE
Change ego vehicles without recreating SMARTS instance

### ISSUE THREAD

**Issue by zbzhu99** [huawei-noah/SMARTS#230]
The SMARTS instance used for imitation learning will specify a part of the historical vehicle as ego vehicles when it is created.

https://github.com/huawei-noah/SMARTS/blob/5389e904c3665801674f7c3b5eb3bd816df60238/examples/history_vehicles_replacement_for_imitation_learning.py#L39-L43

In imitation learning, we need to traverse all vehicles as ego vehicles to obtain enough data for training. Currently, every time we switch the ego car, we need to destroy the previous SMARTS instance and recreate another one with different `agent_interfaces`. There will be some overhead in this process.

The function of switching the controlled ego car in the life cycle of a SMARTS instance needs to be implemented.

**Related Issue:** 
Running "history_vehicles_replacement_for_imitation_learning.py" currently has an error when trap manager attempts to remove a non-existent "sumo" vehicle, where in reality the vehicle is from traffic history instead of sumo. 

2 possible solutions:
1. decrease the trap area of trap_manager so that it does not trap any vehicle and thus will not attempt to remove any vehicles
2. avoid the trapping process when using history provider for imitation learning

**Comment by Gamenot** [comment]
Sorry for the late reply, we had this at one time but did not have a good way of providing the syntax for capturing the next vehicle. 

I can see the driving need for this since the overhead for each SMARTS instance is non-trivial when dealing with short episodes.

**Comment by liamchzh** [comment]
Will close this one after @zbzhu99 test the example.
