### ISSUE TITLE
Envision record as MP4

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#239]
The README for RecordRTC suggests that it is possible to configure the video type: https://github.com/muaz-khan/RecordRTC/blob/master/README.md

As of current webm is a new format and can be inconvenient to convert. There are additional options for video format for the `RecordRTSPromisesHandler`.

```JavaScript
    // audio/webm
    // audio/webm;codecs=pcm
    // video/mp4
    // video/webm;codecs=vp9
    // video/webm;codecs=vp8
    // video/webm;codecs=h264
    // video/x-matroska;codecs=avc1
    // video/mpeg -- NOT supported by any browser, yet
    // audio/wav
    // audio/ogg  -- ONLY Firefox
    // demo: simple-demos/isTypeSupported.html
    mimeType: 'video/webm',
```

Formats that should work for mp4 are: `video/mp4` and `video/webm;codecs=h264`

**Comment by JVillella** [comment]
I recall trying this and it didn't work. Same guy shared this code to the conversion: https://github.com/muaz-khan/WebRTC-Experiment/blob/master/ffmpeg/webm-to-mp4.html.
