### ISSUE TITLE
Test Determinism Failing

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#255]
`test_determinism` is currently failing we need further information on this.

Format:
- Commit hash
- Command run
- Number of cpu cores
- Text log of run

**Comment by Gamenot** [comment]
One capture: 
Commit hash: ead80f9
Command run: `make test`
Number of cpu cores: 16
Text log: [make_test_result.txt](https://github.com/huawei-noah/SMARTS/files/5625835/make_test_result.txt)

**Comment by Gamenot** [comment]
The cause seems to be some part of the heterogeneous agents in merge 245ce6c43c335ee1aad9d5c33137183a34d89086.

**Comment by Adaickalavan** [comment]
@Gamenot 

The `test_determinism` test does not appear to fail in the latest pull request #331. Could you verify whether this problem still occurs?
