### ISSUE TITLE
Physics check of vehicles controlled by laner controller 

### ISSUE THREAD

**Issue by liamchzh** [huawei-noah/SMARTS#258]
This is a `laner with speed` agent. When it changes to the right lane, seems unrealistic compared to lane change in the real world. The action input is `(target_speed, -1)`.

The action of laner is dynamic, but just wondering if we can tune it to make it looks like a human driver.

A few things to check:
- What's the max angular velocity
- Is the speed slow down when it changes lane

![ezgif com-gif-maker](https://user-images.githubusercontent.com/2217445/100900857-4657e600-3491-11eb-9f98-472d724b2608.gif)

**Comment by liamchzh** [comment]
@mg2015started @iman512003

**Comment by mg2015started** [comment]
test branch: https://github.com/huawei-noah/SMARTS/tree/258-changelane-example/lane_change

```bash
python run_changelane.py scenario/lane_change
```

output: 
![image](https://user-images.githubusercontent.com/20150115/101046699-3688f080-35bc-11eb-9d1d-3ea13e83226a.png)
