### ISSUE TITLE
`macos` Tests

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#270]
Current CI tests run on `linux v18` but there are no tests currently to make sure that SMARTS continues to work on `macos`.

AC:
- [x] Test installation steps on `macos`.
- [x] CI runs the `make test` test for `macos` os on merge to master.
- [x] CI tests dependency requirements for `macos` on merge to master.

Related: #265

**Comment by liamchzh** [comment]
@liamchzh bring this up with Nancy.
