### ISSUE TITLE
Envision performance tuning

### ISSUE THREAD

**Issue by JVillella** [huawei-noah/SMARTS#283]
Envision cost seems to be about 40 fps on a regularly 100 fps run. That should turn out to be about 7 milliseconds.

We want to ideally cut that down to 3 or less.

**Comment by liamchzh** [comment]
https://github.com/huawei-noah/SMARTS/pull/451#issuecomment-764783206 

Are we are sending envision state asynchronously?

@Gamenot @JingfeiPeng We need to figure this out.

**Comment by JingfeiPeng** [comment]
Two conclusions so far:
Smarts when headless is True performs consistently better than when headless is False
steps/sec when  headless is False or replay path is defined:
```
10.54
25.31
14.58
16.85
10.61
25.63
23.67
24.45
22.41
```
steps/sec when headless is True and replay path not defined:
```
13.14
42.06
19.34
21.92
12.37
41.86
35.37
40.34
34.54
44.27
```

https://github.com/huawei-noah/SMARTS/blob/develop/smarts/core/smarts.py#L873
The only difference between headless True and False is this emit envision state call here. If I comment out calling this method and set Headless to False, Smarts does have the same performance as when headless is True. 

However, when timing the time spent on this method, it spent 0.3ms~0.4ms per call and there are 70~600 calls per episode, which doesn't even add up to 1 second. But the time spent difference between headless and no headless is a few seconds.

**Comment by JingfeiPeng** [comment]
@Adaickalavan  A script to calculate total time from smarts logs
```
import fileinput

def cal_time(fileName):
    with fileinput.input(files=(fileName)) as f:
        total = float(0)
        totalExampleRunning = float(0)
        for line in f:
            if "Emit envision" in line:
                time = float(line.split("took: ")[1].split('ms')[0])
                total += time
            elif "run example" in line:
                time = float(line.split("took: ")[1].split('ms')[0])
                totalExampleRunning += time
                print(f"episode time: {time/1000}s")
        print(f"total time spent in _try_emit_envision_state: {total/1000}s")
        print(f"total time spent in all episodes: {totalExampleRunning/1000}s")

cal_time('logtimeit.txt')
cal_time('logtimeitNotSend.txt')
```
