### ISSUE TITLE
Only Basic Metrics Available

### ISSUE THREAD

**Issue by valaxkong** [huawei-noah/SMARTS#293]
I just found a base_metric.py under benchmark dir.
It only contains the metric about collsion, goal distance and goal reach rate.
Where is the metrics about safety, agility, stability and any other metrics mentioned in SMARTS paper?

**Comment by Gamenot** [comment]
@KornbergFresnel Could you look at this asap. Preferably by Wednesday next week.

**Comment by KornbergFresnel** [comment]
Sure, I'll make a PR asap.

**Comment by valaxkong** [comment]
@Gamenot @KornbergFresnel 
And would you want to add RSS to SMARTS as a safety related metric?

**Comment by Gamenot** [comment]
> @Gamenot @KornbergFresnel
> And would you want to add RSS to SMARTS as a safety related metric?

Sorry for the late reply, any metric that would be needed to replicate the paper.
