### ISSUE TITLE
Don't have this verison package "ray[rllib]==0.8.4"

### ISSUE THREAD

**Issue by 98luobo** [huawei-noah/SMARTS#308]
Oh,
I want to build this environment in my windows laptop, but unfortunately, the CMD prompts the following error message.
"No local packages or working download links found for ray[rllib]==0.8.4
error: Could not find suitable distribution for Requirement.parse('ray[rllib]==0.8.4')"

And I have looked up some versions of the package, but there  this version is not available

**Comment by Gamenot** [comment]
Hello @98luobo, sorry if we have not made it clear, SMARTS does not have direct support on windows currently. The current way of running SMARTS on Windows OS is by using options like WSL or Docker.

**Comment by 98luobo** [comment]
> Hello @98luobo, sorry if we have not made it clear, SMARTS does not have direct support on windows currently. The current way of running SMARTS on Windows OS is by using options like WSL or Docker.
> 
> We have a section about using docker in the readme. Alternately, I believe that if `ray[rllib]` is the only issue it may be possible to use ray>=1.0.
     
Thanks, It works perfectly on my Linux system
