### ISSUE TITLE
Fix observation test 

### ISSUE THREAD

**Issue by liamchzh** [huawei-noah/SMARTS#32]
There seems to be a Panda3D bug where the zBuffer ordering of vehicles to plane is random.

For now, a few assertions had been commented out to get it passed (see #14 & #31). Need to revisit the issue after open-sourcing.

**Comment by junluo-huawei** [comment]
@JVillella @Gamenot : should we file a bug report to Panda3D?

**Comment by aurorahcx** [comment]
I think the zBuffer ordering should fix the RGB map, currently it is the OGM map that's failing.
