### ISSUE TITLE
Envision `Record` Video not Seek-able

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#33]
The resulting recorded video from envision is not seek-able when using most video players. This makes the video much less useful.

RecordRTC documentation would suggest that `getSeekableBlob` would fix this issue: https://github.com/muaz-khan/RecordRTC/blob/master/README.md#global-apis

**Comment by liamchzh** [comment]
Actually, only Chrome has this seeking issue when playing the webm file for the first time.

So there are other ways to avoid this issue:
1. Use other browsers.
2. Wait until the video finish then it's seekable.
