### ISSUE TITLE
Zoo Worker: Failure while handling connection EOFError()

### ISSUE THREAD

**Issue by JianmingTONG** [huawei-noah/SMARTS#334]
Hi,
I'm under 
ubuntu 18.04
sumo 1.7.0
python 3.7
smarts 0.4.7 release

I follow the following codes to run the benchmark.
```
# terminal 1
scl envision start -s ./scenarios -p 8081
# terminal 2
python run.py scenarios/intersections/4lane -f agents/ppo/baseline-continuous-control.yaml
```

It complains the following error:
```
(pid=14099) ERROR:RemoteAgentBuffer:Waiting for local zoo worker to start up, retrying 0 / 3
(pid=14099) ERROR:Zoo Worker:Failure while handling connection EOFError()
```

Although the training could proceed with these two errors, I am worried that such errors night degrade the performance and impact the results. Might I request anyone to help solve it?

Thanks

**Comment by Gamenot** [comment]
Hello, @JianmingTONG these errors are currently over-eagerly reported at current and should be dropped to warning or log. It is not a problem that should impede the training.

**Comment by JianmingTONG** [comment]
Thanks, my problem gets answerd
