### ISSUE TITLE
CoRL Benchmark Specific Tag (pinned)

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#352]
@mg2015started fill out. Try to address by 31st of December.

We are trying to get a stable tagged version for reproduction of the paper. Please ask for any clarifications needed.

AC:
- [x] Refer to the tag for reproducing the paper
- [ ] Tagged commit should work with "run.py"

**Comment by mg2015started** [comment]
@KornbergFresnel What's the commit or version tag for experiments in benchmark paper?
