### ISSUE TITLE
What about a pure trajectory interpolation controller?

### ISSUE THREAD

**Issue by valaxkong** [huawei-noah/SMARTS#358]
I consider that it is necessary to offering a pure trajectory interpolation controller to move vehicle without considering vehicle dynamic details. It can enhance input compatibility and is helpful to make developer more focus on designing interaction algorithm.

**Comment by valaxkong** [comment]
@Gamenot 
Hi, I have posted a patch to solve this issue. Waiting for review.

**Comment by liamchzh** [comment]
@valaxkong Thanks for contributing to SMARTS!

@iman512003 Please also take a look when you have a chance.

**Comment by Gamenot** [comment]
@valaxkong are you still interested in adding the test for this controller?

**Comment by valaxkong** [comment]
@Gamenot Yes.Sorry for the delay. I'll finish the work by February 28th.
