### ISSUE TITLE
Properly close sumo subprocess

### ISSUE THREAD

**Issue by Adaickalavan** [huawei-noah/SMARTS#366]
Running 
```
python3.7 ./examples/single_agent.py ./scenarios/straight/ --headless 
```
throws the following message at the end of code execution:
```
/usr/lib/python3.7/subprocess.py:883: ResourceWarning: subprocess 26149 is still running
```

This message is due to `self._sumo_proc` not being closed properly. Relevant sections of the code are shown below.

https://github.com/huawei-noah/SMARTS/blob/49b2842192b179e8ab65ceeb8e511cc9261032ed/smarts/core/sumo_traffic_simulation.py#L130-L136

https://github.com/huawei-noah/SMARTS/blob/49b2842192b179e8ab65ceeb8e511cc9261032ed/smarts/core/sumo_traffic_simulation.py#L257-L283

**Comment by liamchzh** [comment]
After a few experiments, turns out that SUMO will exit after all clients close the connection. So if the proc is not being closed properly, what could go wrong? Anyway, adding termination explicitly do no harm to the teardown.
