### ISSUE TITLE
Mini City Presentation

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#367]
@Gamenot 

Presentation: 15 minutes
1) Features added since open sourcing
   - [x] Check weekly highlights
   - [x] Bubbles/HAC/Envision/Optimisations/...
   - [x] Distributed computation of remote agents, in remote servers.

**Comment by Adaickalavan** [comment]
Smarts 0.4.11 is now hosted in our internal servers for testing of distributed computation of remote agents.
