### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by morningsky** [huawei-noah/SMARTS#375]
I follow the steps on Readme, but
 when running `pip install -e .[train]`
then return `no matches found: [train]`

How to install SMARTS on macOS?  Thanks!

**Comment by Gamenot** [comment]
Hello @morningsky, would you happen to be using a termial like `zsh`? 

I can find a similar issue like:
https://github.com/zalando/connexion/issues/779#issuecomment-441081238

**Comment by morningsky** [comment]
@Gamenot  Thank you very much

**Comment by morningsky** [comment]
@Gamenot  I met a new problem when I run `make test`, there are lots of test case failed... Can you help me?  all the failed case return `:-1: running the test CRASHED with signal 11`
![image](https://user-images.githubusercontent.com/11856746/103674170-695a4600-4fb9-11eb-8919-d49feb652738.png)

**Comment by Gamenot** [comment]
Hello @morningsky ,

The current version of `make test` is known to slightly [broken for macOS](https://github.com/huawei-noah/SMARTS/issues/265) and will eventually be a wrapper for this on `macOS`:

```
PYTHONHASHSEED=42 pytest -v \
                --cov=smarts \
                --doctest-modules \
                --forked \
                --dist=loadscope \
                -n `sysctl -n hw.logicalcpu` \
                ./tests ./smarts/core ./smarts/env ./smarts/contrib ./smarts/sstudio ./envision \
                --ignore=./smarts/env/tests/test_learning.py \
                --ignore=./smarts/core/tests/test_smarts_memory_growth.py \
                --ignore=./smarts/env/tests/test_benchmark.py
```

Are you able to run any of the tests manually?

i.e. `pytest -vv `./smarts/core/tests/test_smarts.py`

**Comment by Gamenot** [comment]
Closed for lack of reply.
