### ISSUE TITLE
Appropriately dispose of SMARTS at exit

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#378]
Instances of the SMARTS class hold on to a lot of resources that do not get automatically cleaned up on exit.

AC:
- [ ] Investigate to see if SMARTS instance can automatically close on exit
- [ ] SMARTS instance is cleaned up when destroyed (e.x. `SMARTS.destroy()` is called from `delete` or `atexit`)
- [ ] Introduce clear documentation to explain how to dispose of SMARTS instances appropriately.
- [ ] Update all examples to follow the appropriate practice.

**Comment by Gamenot** [comment]
@sah-huawei Help Jeffer with this ticket.

**Comment by JingfeiPeng** [comment]
Closed with #665
