### ISSUE TITLE
Docker fails to establish entrypoint

### ISSUE THREAD

**Issue by adreena** [huawei-noah/SMARTS#393]
Here is the error I get when I create a container on remote machines, the issue is not related to having an actual monitor for the remote machine or not, it occurs either way:

Note: there is no other docker running, and I used to be able to run the same script before recent changes. 
[xdummy.log](https://github.com/huawei-noah/SMARTS/files/5789735/xdummy.log)

```
Fatal server error:
(EE) Server is already active for display 1
        If this server is no longer running, remove /tmp/.X1-lock
        and start again.
(EE)
(EE)
Please consult the The X.Org Foundation support
         at http://wiki.x.org
 for help.
(EE)
```

**Comment by Gamenot** [comment]
From what I am reading in the log, x-dummy is struggling with not having `xserver-xorg-input-void` or `libinput` when trying to set up the dummy mouse and keyboard.

**Comment by Gamenot** [comment]
OK, I did some fiddling and managed to get it to work.

Looks like what is needed is:

`export DISPLAY=:1`

It seems like `export Display=:1` is wrong here.

**Comment by Gamenot** [comment]
We may have to do some extra configuration if we wish to make it easier https://stackoverflow.com/questions/34481914/ssh-login-shows-only-console-users-are-allowed-to-run-the-x-server.

Or a script like `start_display.sh`:

```bash
sudo export Display=:1
sudo /usr/bin/Xorg -noreset +extension GLX +extension RANDR +extension RENDER -logfile ./xdummy.log -config /etc/X11/xorg.conf -novtswitch $DISPLAY &
```

**Comment by Gamenot** [comment]
@adreena has mentioned she will try using an entrypoint script to see if that helps.

**Comment by Adaickalavan** [comment]
@adreena 
Can this issue be closed given the success in using a separate entrypoint script?

**Comment by adreena** [comment]
Yes, just fix those packages in setup/requirements that I mentioned in
espace.

**Comment by Adaickalavan** [comment]
Package version fix in requirements.txt
+ Pillow==7.2.0
+ chardet==3.0.2
+ dill==latest
+ packaging==latest
