### ISSUE TITLE
OpEn Calculation Forces Vehicle Off-road When turning to `-y` Direction

### ISSUE THREAD

**Issue by iman512003** [huawei-noah/SMARTS#401]
It seems that the heading error is not correctly calculated when the heading moving downward. I think this happens due to the new changes into the solver for behavorial model.
![Screenshot from 2021-01-12 09-02-41](https://user-images.githubusercontent.com/27947083/104324418-6679bc80-54b5-11eb-949e-de166f97d5a7.png)

**Comment by Gamenot** [comment]
@iman512003 Is this still a problem?

**Comment by iman512003** [comment]
I think it is resolved by #446 .
