### ISSUE TITLE
Limit the Memory Use of Loaded Traffic Histories 

### ISSUE THREAD

**Issue by JingfeiPeng** [huawei-noah/SMARTS#402]
Currently the discover_traffic_histories method in scenario.py loads all the traffic history at once. We want to limit the size of traffic histories that can be loaded at 1 time since the traffic histories could be very large.

**Comment by liamchzh** [comment]
For more context, please see https://github.com/huawei-noah/SMARTS/pull/390#discussion_r553573637

**Comment by JingfeiPeng** [comment]
Closed with #634
