### ISSUE TITLE
Customized SMARTS service for MAD co-sim

### ISSUE THREAD

**Issue by liamchzh** [huawei-noah/SMARTS#403]
A simple SMARTS service has been implemented 

- - - - 
## Motivations
1. Communicate with SMARTS
    - Manage the process
    - Supply with different scenarios
    - Pause/stop/start/reset

2. Easy setup (an environment to run SMARTS)
    - A MVS (minimum viable SMARTS) 

## Introduction
In current integration, H is the coordinator that will call SMARTS and KS. Now H starts a SMARTS instance by using a bash script. 

From H’s perspective, in order to accelerate the integration, SMARTS needs to:

1. reuse SUMO instance if the map is not changed.
2. reset everything without restart SUMO when switching between scenarios (#73)

H’s Workflow should be:

1. start the SMARTS service
    - service port
    - sumo port
    - number of SUMO external client

2. reset/setup a scenario, need to specify:
    - scenario
    - ego agent
    - max_episode_steps
    - timestep
    - seed
    - ...

3. start to run a scenario
4. stop running the scenario
5. Loop through from step 2 to 4 until service terminated

Per discussion, we will have a scenario service to provide functionalities such as initializing SMARTS, scenario setup and stepping, which is similar to what `env` layer is doing.

The Service should take care of:

- creating SMARTS instance
- setup scenario but not to run it until explicitly told to so do.
- building the scenario if it has not been built

**Comment by Gamenot** [comment]
#76 Related ticket

**Comment by Gamenot** [comment]
On hold indefinitely.
