### ISSUE TITLE
ultra assumes social observations in generate_logs

### ISSUE THREAD

**Issue by AlexLewandowski** [huawei-noah/SMARTS#404]
When checking for social violations in generate_logs in ultra/env/ultra_env.py:94, it is assumed that the agent has observations on social_vehicles.

This occurs if ignore_vehicle_behind = True, because of get_vehicles_not_behind in ultra/utils/common.py:170. But it also occurs on line ultra/utils/common.py:203 because of the loop over neighborhood_vehicle_states.

**Comment by adreena** [comment]
it's reasonable for logger to expect neighbor vehicles in the observation as the agent would be evaluated based on its social violation. policies need to be compared on a consistent basis, so my guess is the agentinterface was not covering the requirements for the agent.

**Comment by AlexLewandowski** [comment]
Closing because #471 will specify obs_space for ULTRA environments.
