### ISSUE TITLE
Header File Test

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#406]
Files have been making it into the SMARTS core files without the appropriate headers.

* https://github.com/huawei-noah/SMARTS/tree/master/smarts/core/tests/helpers/bubbles.py
* https://github.com/huawei-noah/SMARTS/tree/master/smarts/core/tests/helpers/scenario.py
* https://github.com/huawei-noah/SMARTS/tree/master/smarts/sstudio/tests/test_generate.py
* https://github.com/huawei-noah/SMARTS/tree/master/smarts/zoo/manager_pb2.py
* https://github.com/huawei-noah/SMARTS/tree/master/smarts/zoo/manager_pb2_grpc.py
* https://github.com/huawei-noah/SMARTS/tree/master/smarts/zoo/worker_pb2.py
* https://github.com/huawei-noah/SMARTS/tree/master/smarts/zoo/worker_pb2_grpc.py

Add a test to ensure copyright header is added to smarts files in core directories.

AC:
- [ ] Header test for python files in directories:
   - [ ] `cli`
   - [ ] `smarts`
   - [ ] `envision`
   - [ ] `benchmark`
   - [ ] `ultra`
- [ ] Header test for javascript files in directories:
   - [ ] `envision`
- [ ] Only applies to above directories 
- [ ] Test is separate from others like `ci-test-formating-and-dependencies`

**Comment by Gamenot** [comment]
@Adaickalavan suggests writing the header check in a bash script.

**Comment by Adaickalavan** [comment]
Sample bash script:
```
# !/usr/bin/env bash

# Collate files
python_files="$(find ./{cli,smarts,benchmark,envision,ultra} -name '*.py')"
js_files="$(find ./envision -name '*.js')"
files="$python_files $js_files"  

# Check and add copyright notice
for file in $files; do
    # ...
    echo $file
done
```
