### ISSUE TITLE
Provide Optional Scramble of Scenarios for `hiway_env`

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#41]
Configuration of `smarts.env.hiway_env.HiWayEnv` should provide the option for ordered and pseudo-randomised scenario execution.

The current implementation uses an iterator from `Scenario.scenario_variations()` that scrambles the scenario order. What is needed here is an additional option to `HiWayEnv` that will allow to specify that the execution order of scenarios should be the same as provided in the `__init__()`.

The current signature of `smarts.env.hiway_env.HiWayEnv`:
https://github.com/huawei-noah/SMARTS/blob/master/smarts/env/hiway_env.py#L68-L84

The scenario iterator:
https://github.com/huawei-noah/SMARTS/blob/master/smarts/env/hiway_env.py#L91-L93

**Comment by Adaickalavan** [comment]
+ List returned by `os.listdir()` is in arbitrary order. This affects the line 
https://github.com/huawei-noah/SMARTS/blob/ead80f99a0391c2a48dbe32bc41e6a90fba2fa5e/smarts/core/scenario.py#L452
