### ISSUE TITLE
Specify a frame rate for SMARTS

### ISSUE THREAD

**Issue by liamchzh** [huawei-noah/SMARTS#413]
When integrating with KS, it requires SMARTS to run at a specified frame rate or above, otherwise, the reflection (position) of the MAD vehicle in the SUMO becomes inaccurate and affects the observation that given to our agents.

For example, if SMARTS is required to be running higher than 25 fps, when a single step takes longer than 40ms, SMARTS needs to give a warning or raise an exception.

To address this issue, I think SMARTS can provide a context manager to monitor the frame rate, the main reason is that this approach provides flexibility,
1. Easy to use and plug it in. We can use it in the example or environment, or even in the SMARTS service in the future.
2. Easy to extend its functionality, like tolerances.

**Comment by liamchzh** [comment]
Chendong also reported that the time each step needs will increase as the `timestep_sec` increase. Now `timestep_sec` is 0.04s, each step needs around 40ms, however, when `timestep_sec` increases to 0.08s, the time for each step will also go up to around 80ms.

@iman512003 We need to dig into this issue.

**Comment by Gamenot** [comment]
Conclusion: SMARTS is not the bottleneck in this case. Imposes a non-deterministic framework on SMARTS.
