### ISSUE TITLE
ULTRA Force Info Adapter Implementation

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#422]
@adreena fill out when you get the chance.

ULTRA currently relies on pushing the logs out through modifying the `infos` in `hiway_env`. This should instead be done by fully defining `ultra_env` without it inheriting from `hiway_env` since it is specific to the ULTRA environment. There was some discussion on forcing the implementation of the info adapter to adhere to the `ultra_env` requirement.

**Comment by adreena** [comment]
We can keep the inheritance for readability purposes, ultra remains a child from highway, and instead of generate_logs we do a full override of step() module and that hides log object inside the info. the priority of user adapters also remains intact.
