### ISSUE TITLE
ULTRA Basic Documentation

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#424]
Provide minimum documentation to get users up to speed on running the ULTRA baselines.

- [x] How to get baseline models trained on task1 and task2
- [x] How to get the ULTRA docker set up
- [x]  Clean up writing on key features
- [x] Link ULTRA paper

**Comment by christianjans** [comment]
@AlexLewandowski does the ULTRA paper currently have an available link?

**Comment by AlexLewandowski** [comment]
@christianjans yeah here is the [link](https://ml4ad.github.io/files/papers2020/ULTRA:%20A%20reinforcement%20learning%20generalization%20benchmark%20for%20autonomous%20driving.pdf)

**Comment by christianjans** [comment]
@AlexLewandowski awesome thanks! I will add it to the README.
