### ISSUE TITLE
Zoo manager runtime error: dictionary size changed during iteration

### ISSUE THREAD

**Issue by liamchzh** [huawei-noah/SMARTS#436]
https://github.com/huawei-noah/SMARTS/blob/f8259388da49fade76758fef0717dd9169b15625/smarts/zoo/manager_servicer.py#L94-L97

![image](https://user-images.githubusercontent.com/2217445/104864948-93403080-5908-11eb-8a9f-c5a18bfb43e7.png)

**Comment by Adaickalavan** [comment]
What are the steps to reproduce this error?

**Comment by Adaickalavan** [comment]
@liamchzh updated that he was not able to reproduce this with a simple use case. Closing this issue, as no further leads are available on this matter.
