### ISSUE TITLE
Establish Gitflow Iteration

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#438]
Look into implementing [Gitflow](https://datasift.github.io/gitflow/IntroducingGitFlow.html) for SMARTS development cycle. 

Also look at:
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-branches#about-the-default-branch

**Comment by Adaickalavan** [comment]
I believe currently we have implemented the idea of 
+ `master`, 
+ `hotfixes`,
+ `develop`, and
+ feature branches. 

We only lack the idea of a `release` branch for bugfixes.

**Comment by Gamenot** [comment]
This is implemented
