### ISSUE TITLE
Module requirements - version

### ISSUE THREAD

**Issue by Sriram94** [huawei-noah/SMARTS#444]
Hello, 

I wanted to check if the following version changes for requirements will still work. We are trying to install SMARTS in HPCs and some required versions are harder to satisfy. 

< "ray[rllib]==0.8.6", # We use Ray for our multiprocessing needs
---
> "ray[rllib]==0.8.7", # We use Ray for our multiprocessing needs

< "tensorflow==2.2.1",
---
> "tensorflow==2.3.0",

< "torch==1.4.0",
< "torchvision==0.5.0",
---
> "torch==1.7.1",
> "torchvision==0.8.2",

Please comment if these version changes will not break anything. Thanks.

**Comment by Gamenot** [comment]
Hello @Sriram94, often different versions can work but we cannot guarantee it. I am currently testing to see if this configuration of packages are working. I should know by tomorrow morning.

**Comment by Gamenot** [comment]
@Sriram94 From my tests, those dependencies should work.

**Comment by Sriram94** [comment]
Thanks a lot.
