### ISSUE TITLE
Collisions between agent and social vehicles cannot be detected

### ISSUE THREAD

**Issue by GyChou** [huawei-noah/SMARTS#456]
As shown in the figure below, agent and social vehicles overlap
![TZ{CR_DKQTA8TC% $3% 5$D](https://user-images.githubusercontent.com/30279942/105459319-052bc780-5cc5-11eb-8113-d2076d76319a.png)
The environment also is smarts.env:hiway-v0

**Comment by liamchzh** [comment]
@Gamenot Is the collision detection broken again? :thinking:

**Comment by liamchzh** [comment]
https://user-images.githubusercontent.com/2217445/105541680-1b865300-5cc6-11eb-9473-2002b52bb1b2.mp4

Hit and run again! This could be reproduced by running single_agent.py with intersections/4lane_t

**Comment by liamchzh** [comment]
Jeffer and I dig into the issue, found that this bug only happens when the agent is slightly hit. We traced it back to a commit in early Nov and were able to reproduce this bug.

Per discussion, removed the urgent tag. But we need to figure this out ASAP.

**Comment by liamchzh** [comment]
@GyChou Could you provide more info like which commit you were using? Thanks

**Comment by GyChou** [comment]
Thanks for your reply
I was cloned on November 25, 2020, and I think I use the commit of 16 Nov 2020.
My OSis ubuntu18.04.
The case in your video also exists in `scenarios\loop`. The agent and the white vehicle will not overlap, but the agent will overlap with the 3d box vehicle, just like the one I circled in red line.

**Comment by Gamenot** [comment]
First step here is to remove the TargetPose agent from our examples for now.

1. Where agent gain control of a vehicle if it uses an interpolated action space it will need access to the AgentInterface to choose BoxChassis or AckermannChassis.
2. Change naming of pybullet_action_spaces to dynamic_action_spaces
3. Create controller cases for TargetPose and MultiTargetPose to handle `vehicle.control(<pose>)` with a BoxChassis expected
4. Scrap the provider used for TargetPose and MultiTargetPose

**Comment by Gamenot** [comment]
Fixed with #485
