### ISSUE TITLE
Modularize the social encoder

### ISSUE THREAD

**Issue by AlexLewandowski** [huawei-noah/SMARTS#458]
- [ ] Social encoder should be optional
- [ ] Allow user to supply their own social encoder

**Comment by adreena** [comment]
lets put this under a bigger task for refining state_preprocessor.
we currently have the feature for adding new encoders or disabling the encoders 
 - set social_capacity to 0 to disable any social vehicle observation
 - set encoder to no_encoder to get 4 states(position x, y, speed and steering) for each social vehicle [base case]
