### ISSUE TITLE
Create minimal gym-compatible ULTRA env

### ISSUE THREAD

**Issue by AlexLewandowski** [huawei-noah/SMARTS#459]
The ULTRA env is currently constructed based on an agent spec. We should see if its possible to construct an implementation of the env that would work with any gym-compatible agent.

**Comment by Adaickalavan** [comment]
SMARTS is currently gymnasium compatible, whereas ULTRA has been moved to [smarts-project.rl](https://github.com/smarts-project/smarts-project.rl) repository.
