### ISSUE TITLE
Investigate Physics Performance: Move Away from Pybullet

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#46]
@iman512003 Please clarify the approach to take with this.

The current pybullet physics engine use takes up a bit too much of the simulation step between collision processing and physics simulation step.

![image](https://user-images.githubusercontent.com/8764693/96780428-b8c9a680-13ba-11eb-9fa1-5392fd56e7ab.png)

Current plan: Move to a 2D physics model to improve performance

**Comment by Gamenot** [comment]
@Gamenot

**Comment by iman512003** [comment]
1) I have made the following changes to the physics and it reduced from 19% to 6% percent.

![yyy](https://user-images.githubusercontent.com/27947083/97369270-fdee4c80-1882-11eb-8c2e-af46940e7cf3.png)

2) I have an idea to use a simple 2D dynamics and then reset the position of the vehicle using bullet this way with minimal changes to smart.py we can test whether it can help or not.
