### ISSUE TITLE
Integrate RL frameworks with ULTRA

### ISSUE THREAD

**Issue by AlexLewandowski** [huawei-noah/SMARTS#460]
- [ ] RLLib (https://github.com/huawei-noah/SMARTS/issues/471)
 - [ ] Dopamine
 - [ ] Keras-RL?
 - [ ] Tensorforce?
 - [ ] TRFL?
 - [ ] Coach?

Many of these are compatible with gym, so #459 can be a shortcut.

**Comment by Adaickalavan** [comment]
SMARTS is currently gymnasium compatible, whereas ULTRA has been moved to [smarts-project.rl](https://github.com/smarts-project/smarts-project.rl) repository.
