### ISSUE TITLE
Include lane speed in observation

### ISSUE THREAD

**Issue by AlexLewandowski** [huawei-noah/SMARTS#461]
Currently speed discrepancies are penalized in the reward, but including it in the observation may help.

**Comment by christianjans** [comment]
Hi @AlexLewandowski and @adreena.

Okay sorry after looking at it again, is this not already implemented?

It looks like the baseline's observation adapter includes the road speed as the speed limit of the closest waypoint in its observation.
https://github.com/huawei-noah/SMARTS/blob/c4e17f403ac82b6e420a18b80b088f32cd233d7c/ultra/baselines/adapter.py#L79

Then, when this state gets passed to the baseline agent through the agent's `state` or `act` methods, this state gets further processed by the baseline agent's state preprocessor:
https://github.com/huawei-noah/SMARTS/blob/c4e17f403ac82b6e420a18b80b088f32cd233d7c/ultra/baselines/common/state_preprocessor.py#L111-L113

Where the road speed is normalized by 30 according to:
https://github.com/huawei-noah/SMARTS/blob/c4e17f403ac82b6e420a18b80b088f32cd233d7c/ultra/baselines/common/state_preprocessor.py#L178-L191

Finally, these normalized values (including the road speed) become the low dimensional states:
https://github.com/huawei-noah/SMARTS/blob/c4e17f403ac82b6e420a18b80b088f32cd233d7c/ultra/baselines/common/state_preprocessor.py#L115-L123

And are returned with the other processed parts of the state:
https://github.com/huawei-noah/SMARTS/blob/c4e17f403ac82b6e420a18b80b088f32cd233d7c/ultra/baselines/common/state_preprocessor.py#L149-L154

Let me know if I am missing something!

**Comment by adreena** [comment]
Oh it looks like we have integrated it, it must have been later in the
project and I couldn’t remember it.

**Comment by christianjans** [comment]
Oh okay perfect! Thanks for verifying!
