### ISSUE TITLE
Inaccurate agent speed in SUMO

### ISSUE THREAD

**Issue by liamchzh** [huawei-noah/SMARTS#466]
Need to dig into the sumo traffic sim, to see whether SMARTS set the correct speed for agents.

**Comment by Gamenot** [comment]
```bash
# sumo version 1.8
# python 3.7
# SMARTS v0.4.12 release
python examples/single_agent.py scenarios/straight --headless
```

I am seeing some difference in speed at least what sumo-gui is telling me:

![image](https://user-images.githubusercontent.com/8764693/105676469-9020e380-5eb8-11eb-811d-715110fa0a50.png)

And then an example with a bubble agent:

![image](https://user-images.githubusercontent.com/8764693/105676899-2a812700-5eb9-11eb-8d76-5e71e61838af.png)

I wonder if it is only counting speed in direction along the lane. Even still, it means that there is a significant difference.

**Comment by liamchzh** [comment]
[map.zip](https://github.com/huawei-noah/SMARTS/files/5870129/map.zip)

Can you try using this map? They reported that the speed drops when the agent is passing the intersection at the bottom.

**Comment by Gamenot** [comment]
SUMO's speed here is the projection to the lane from the vehicle velocity.
