### ISSUE TITLE
Automate DISPLAY start in Docker

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#468]
Current ULTRA docker image may not start the x-server since x-server needs privileged access to hardware.

We need to find a way to automate that in the dockerfile if possible. See:

https://github.com/huawei-noah/SMARTS/blob/master/ultra/Dockerfile

Also see #393:

> We may have to do some extra configuration if we wish to make it easier https://stackoverflow.com/questions/34481914/ssh-login-shows-only-console-users-are-allowed-to-run-the-x-server.
> 
> Or a script like `start_display.sh`:
> 
> ```bash
> sudo export DISPLAY=:1
> sudo /usr/bin/Xorg -noreset +extension GLX +extension RANDR +extension RENDER -logfile ./xdummy.log -config /etc/X11/xorg.conf -novtswitch $DISPLAY &
> ```
> 
> _Originally posted by @Gamenot in https://github.com/huawei-noah/SMARTS/issues/393#issuecomment-757663313_

**Comment by adreena** [comment]
opened a PR : https://github.com/huawei-noah/SMARTS/pull/486
