### ISSUE TITLE
WIP: make RLlibUltraEnv

### ISSUE THREAD

**Issue by adreena** [huawei-noah/SMARTS#471]
branch: https://github.com/huawei-noah/SMARTS/tree/ultra-rllib

- [x] create a train script
   - [x] pass environment config
   - [x] Use RLlib native policy/models
   - [x] add social_vehicle_encoders to the networks
   - [x] configure torch framework
   - [x] make ultra environment compatible with rllib 
   - [x] modify adapters to match the configuration
   - [x] configurations for observation_space and action_space
- [x] figure out how the evaluation works and setup the config @JenishPatel99 
   - [x] configuration 
   - [x] what should be the evaluation_interval
   - [x] check the scenarios switching to test scenarios
- [x] where experiments are saved

Might be shifted to v0.3 :
- [ ] config for tensorboard handle
- [ ] figure out how to integrate logger from episode object
- [ ] create agent script
- [ ] add SAC/DQN/DDPG

**Comment by christianjans** [comment]
Changes for ULTRA 0.2 have been implemented.
