### ISSUE TITLE
OpEn U-Turn & Cut-In Documentation

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#488]
A document describing the ideas behind tuning the OpEn agent, U-Turn, and Cut-In and how to change the parameters and hyperparameters.

**Comment by liamchzh** [comment]
This document should cover:
1. What's the approach that we chose to accomplish the tasks (U-Turn & Cut-in)
2. What are the responsibilities of the mission planner and OpEn
3. The ideas behind the trajectory calculation of u-turn and cut-in (What are the params and how do they affect the trigger timing)
4. Other topics that Chendong might be interested in (Jeffer can help clarify in the regular meetings)

**Comment by JingfeiPeng** [comment]
Done this is added in `docs/cutin-uturn-docs.rst`
