### ISSUE TITLE
Envision needed in headless mode? 

### ISSUE THREAD

**Issue by Sriram94** [huawei-noah/SMARTS#574]
Even while running headless, I get the error: "Client:Connection to Envision terminated with: [Errno 113]". I was just running the example training here: https://github.com/huawei-noah/SMARTS/tree/master/benchmark. Can you comment if the connection to Envision is still required while we run headless?

**Comment by Gamenot** [comment]
@Sriram94 Thank you for the question. There should be no need for envision while headless. It would be a bug if you are getting that connection warning when running with headless, although there should not be much loss.

Just to be clear are you running the training from the current master?

**Comment by Sriram94** [comment]
Thank you for your reply @Gamenot. Actually it was just a problem with my local installation (I had not updated it with the latest version of Master). The issue is fixed now, and I am closing this issue.
