### ISSUE TITLE
Simulate with multiple CPUs

### ISSUE THREAD

**Issue by Xiaoyu006** [huawei-noah/SMARTS#586]

**Comment by Xiaoyu006** [comment]
Hi,

I found that the simulation quite slow (<10fps) and it is using only one CPU while I have 10 CPUs with my desktop.
How to used multiple CPUs (2.0G Hz) to speed up the simulation?

**Comment by Gamenot** [comment]
Hello @Xiaoyu006 thank you for reaching out. Unfortunately we only have partially distributed simulation for a single SMARTS instance. Fully distributed simulation is planned for the future in addition to optimisations to improve general performance.

Our current way of training with multiple core involves using parallelisation of environments such as with `examples/rllib.py`.

**Comment by Xiaoyu006** [comment]
> Hello @Xiaoyu006 thank you for reaching out. Unfortunately we only have partially distributed simulation for a single SMARTS instance. Fully distributed simulation is planned for the future in addition to optimisations to improve general performance.
> 
> Our current way of training with multiple core involves using parallelisation of environments such as with `examples/rllib.py`.

Hi, @Gamenot Thank you for your quick reply and your suggestions.

**Comment by Adaickalavan** [comment]
You may consider using `ParallelEnv` class to simulate multiple SMARTS environments in parallel, with synchronous or asynchronous episodes, to collect observations at a faster rate.

See pull request #1087 for details.
