### ISSUE TITLE
no module named smarts

### ISSUE THREAD

**Issue by eerkaijun** [huawei-noah/SMARTS#588]
I've run `install_deps.sh` and `pip install -e .[train]` and `pip install -e .[test]`. However, when running `make test`, I encountered the following error, any ideas why? 

```
scl scenario build-all scenarios
Traceback (most recent call last):
  File "/afs/inf.ed.ac.uk/user/s18/s1800883/SMARTS/env/bin/scl", line 33, in <module>
    sys.exit(load_entry_point('smarts', 'console_scripts', 'scl')())
  File "/afs/inf.ed.ac.uk/user/s18/s1800883/SMARTS/env/bin/scl", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/afs/inf.ed.ac.uk/user/s18/s1800883/SMARTS/env/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/afs/inf.ed.ac.uk/user/s18/s1800883/miniconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/afs/inf.ed.ac.uk/user/s18/s1800883/SMARTS/cli/cli.py", line 22, in <module>
    from .envision import envision_cli
  File "/afs/inf.ed.ac.uk/user/s18/s1800883/SMARTS/cli/envision.py", line 22, in <module>
    from envision.server import run
  File "/afs/inf.ed.ac.uk/user/s18/s1800883/SMARTS/envision/server.py", line 41, in <module>
    import smarts.core.models
ModuleNotFoundError: No module named 'smarts'
make: *** [Makefile:51: build-all-scenarios] Error 1
```

When I do `pip list`, it shows that smarts is already installed

**Comment by Gamenot** [comment]
Hello @eerkaijun thank you for reaching out. I am unable to diagnose the problem with what you have provided.

Does the first line of: "/afs/inf.ed.ac.uk/user/s18/s1800883/SMARTS/env/bin/scl" match the python source `#!/afs/inf.ed.ac.uk/user/s18/s1800883/SMARTS/env/bin/python3.7`?

**Comment by eerkaijun** [comment]
HI @Gamenot, thanks for the response. I checked and the first line of scl is `#!/afs/inf.ed.ac.uk/user/s18/s1800883/SMARTS/env/bin/python`. But even after I changed python to python3.7, the same error still persists. Any ideas why?

**Comment by Gamenot** [comment]
Could you confirm the results for the following commands within your virtual environment:

```
pip --version && \
which python && \
python --version && \
which scl && \
python3.7 -m smarts && \
/afs/inf.ed.ac.uk/user/s18/s1800883/SMARTS/env/bin/pip list | grep smarts
```

**Comment by eerkaijun** [comment]
Hi, please find below: 

```
>>> pip --version 
pip 21.0.1 from /afs/inf.ed.ac.uk/user/s18/s1800883/SMARTS/env/lib/python3.7/site-packages/pip (python 3.7)

>>> which python 
/afs/inf.ed.ac.uk/user/s18/s1800883/SMARTS/env/bin/python

>>> which python3.7
/afs/inf.ed.ac.uk/user/s18/s1800883/SMARTS/env/bin/python3.7

>>> python --version
Python 3.7.3

>>> which scl
/afs/inf.ed.ac.uk/user/s18/s1800883/SMARTS/env/bin/scl

>>> python3.7 -m smarts
/afs/inf.ed.ac.uk/user/s18/s1800883/SMARTS/env/bin/python3.7: No module named smarts

>>> /afs/inf.ed.ac.uk/user/s18/s1800883/SMARTS/env/bin/pip list | grep smarts
smarts                   0.4.13      /afs/inf.ed.ac.uk/user/s18/s1800883/SMARTS
```

**Comment by Gamenot** [comment]
> \>\>\> python3.7 -m smarts
> /afs/inf.ed.ac.uk/user/s18/s1800883/SMARTS/env/bin/python3.7: No module named smarts

I do not quite understand what is happening here but the last ditch effort could be to call

```
python3.7 -m pip | grep afs
python3.7 -m pip list | grep smarts
python3.7 -m pip install -e .
python3.7 -m pip list | grep smarts
```

I would be extremely confused if this does not work and then the last thing I can think of is to check the python path from python.

```
$ python3.7
>>> import sys
>>> sys.path
```

Assuming that `/afs/inf.ed.ac.uk/user/s18/s1800883/SMARTS` is the smarts repository location it should be one of the paths in the returned list. And also assuming the `/afs/.../SMARTS` directory contains the SMARTS repository directories and files (i.e. scenarios, smarts, third_party, .gitignore, ...)

If that directory is not there it is a problem with how the virtual environment was set up and the following should find smarts but I would still suggest fixing the virtual environment:

```
PYTHONPATH='/afs/inf.ed.ac.uk/user/s18/s1800883/SMARTS/' scl scenario build-all scenarios
```

**Comment by Gamenot** [comment]
@eerkaijun Is this still a problem?

**Comment by eerkaijun** [comment]
Hello @Gamenot, even after running `PYTHONPATH='/afs/inf.ed.ac.uk/user/s18/s1800883/SMARTS/' scl scenario build-all scenarios` it still doesn't work for me. So I followed your suggestion to set up the virtual environment from scratch and it works. So I guess that's an issue with my virtual environment. 

Sorry for forgetting to update you, but thanks a lot for your help! (I'll close the issue now)
