### ISSUE TITLE
Turn `Showbase` inheritance into composition via singleton

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#597]
Context #184 

Convert from `SMARTS` inheriting `Showbase` to `SMARTS` just using a Showbase instance.

- [ ] Partition rendering instance so that SMARTS instances do not share information via camera observations
- [ ] Unique identifiers for SMARTS instances for accessing Showbase nodes.
- [ ] Close down `Showbase` instance when all SMARTS instances are closed

**Comment by sah-huawei** [comment]
@Gamenot : I have this mostly done (pending some cleanup) on a branch and passing all of the tests in `make tests`.  But do we have any specific test or examples that uses multiple SMARTS instances so I can verify the first bullet above?

**Comment by Gamenot** [comment]
@sah-huawei Unfortunately we do not since we were previously unable to have multiple SMARTS instances existing in the same process due to the global requirement of SMARTS.

I think I need to clarify what I mean here. If we are sharing Showbase as the renderer, there is also the potential issue of shared state passing between the steps of different SMARTS instances.
