### ISSUE TITLE
Automate build of scenario

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#602]
Add meta file(s) to scenario to build the scenario on run of SMARTS if a meaningful attribute has changed. On build of SMARTS the resulting scenario will also contain a meta file that can be compared with the state of parts of the scenario file to see if the scenario needs to be rebuilt.

- [ ] Rebuild scenario when running smarts
- [ ] Flag for skipping scenario rebuild on run
- [ ] Flag for forcing scenario rebuild on run
- [ ] Rebuild map if map file has been modified
- [ ] Rebuild scenario when running smarts based on the following
  - [ ] If scenario.py last edited date has changed
  - [ ] If map.net.xml last edited date has changed
  - [ ] If SMARTS version has changed
  - [ ] If any file in `smarts/sstudio` directory has been modified

**Comment by Adaickalavan** [comment]
Closed by #1764
