### ISSUE TITLE
WSL: gRPC error 92

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#614]
## **BUG REPORT**
Running SMARTS in Windows Subsystem for Linux can result in a protocol error that prevents social agents from working.

**SMARTS version**
0.4.13

**Previous associated issues**
None

**Steps to reproduce the bug**
Perform the setup steps for smarts on WSL.

**Resulting and expected behaviour**
Non-responsive social agents that only drive as if they were laners.

**Error logs and screenshots**
```
$ supervisord
E0223 11:45:18.666377900    5955 socket_utils_common_posix.cc:223] check for SO_REUSEPORT: {"created":"@1614098718.666326200","description":"Protocol not available","errno":92,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":201,"os_error":"Protocol not available","syscall":"getsockopt(SO_REUSEPORT)"}
╭────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────╮
│            Episode │     Sim T / Wall T │        Total Steps │        Steps / Sec │       Scenario Map │    Scenario Routes │     Mission (Hash) │             Scores │
├────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┤
E0223 11:45:23.426190600    5971 socket_utils_common_posix.cc:223] check for SO_REUSEPORT: {"created":"@1614098723.426160600","description":"Protocol not available","errno":92,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":201,"os_error":"Protocol not available","syscall":"getsockopt(SO_REUSEPORT)"}
E0223 11:45:24.151343700    5975 socket_utils_common_posix.cc:223] check for SO_REUSEPORT: {"created":"@1614098724.151313800","description":"Protocol not available","errno":92,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":201,"os_error":"Protocol not available","syscall":"getsockopt(SO_REUSEPORT)"}
E0223 11:45:24.259238800    5981 socket_utils_common_posix.cc:223] check for SO_REUSEPORT: {"created":"@1614098724.259207900","description":"Protocol not available","errno":92,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":201,"os_error":"Protocol not available","syscall":"getsockopt(SO_REUSEPORT)"}
E0223 11:45:25.422724500    5995 socket_utils_common_posix.cc:223] check for SO_REUSEPORT: {"created":"@1614098725.422695000","description":"Protocol not available","errno":92,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":201,"os_error":"Protocol not available","syscall":"getsockopt(SO_REUSEPORT)"}
E0223 11:45:27.920641800    6026 socket_utils_common_posix.cc:223] check for SO_REUSEPORT: {"created":"@1614098727.920610400","description":"Protocol not available","errno":92,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":201,"os_error":"Protocol not available","syscall":"getsockopt(SO_REUSEPORT)"}
E0223 11:45:28.613134700    6044 socket_utils_common_posix.cc:223] check for SO_REUSEPORT: {"created":"@1614098728.613104700","description":"Protocol not available","errno":92,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":201,"os_error":"Protocol not available","syscall":"getsockopt(SO_REUSEPORT)"}
E0223 11:45:28.846122800    6051 socket_utils_common_posix.cc:223] check for SO_REUSEPORT: {"created":"@1614098728.846093900","description":"Protocol not available","errno":92,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":201,"os_error":"Protocol not available","syscall":"getsockopt(SO_REUSEPORT)"}
│               0/10 │               0.04 │                  4 │               0.37 │              6lane │                    │ 336386240360290922 │  17.74 - Agent-007 │
^C2021-02-23 11:45:33,048 WARN received SIGINT indicating exit request
╰────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────╯
```
 
**System information**
 
- Operating system & Environment [Please note if using Docker]:
    Windows 10 WSL: Ubuntu 18.04
- Number of system cores available
    
- Python version [Please note if using Jupyter]
    Python 3.7.7
- Python packages [e.g. from `pip freeze`]
    [freeze.txt](https://github.com/huawei-noah/SMARTS/files/6030543/freeze.txt)
- SUMO version
   1.8.0
- Date when bug occurred
    2021-02-23
 
**Impact [If known]**

**Comment by Adaickalavan** [comment]
This error looks like an issue of gRPC's support for WSL. It was noted previously in grpc/grpc#23314 . We should try running a hello world gRPC example in WSL to narrow down the potential next steps in dealing with this.

**Comment by Gamenot** [comment]
@RutvikGupta could you confirm if this is fixed?

**Comment by RutvikGupta** [comment]
So, after setting up SMARTS on wsl and running make sanity-test I saw that most tests for social agents and for multi-agents either failed or throw errors. 
![image](https://user-images.githubusercontent.com/47334253/118848803-16649980-b89d-11eb-8a0c-bea95b32e5b1.png)
From the traceback calls of the failed tests we can see that the error came from the call to `grpc` methods of `grpc._utilities` package in `smarts/core/remote_agent.py` and `smarts/core/remote_agent_buffer.py`. This is because it gets a server timeout error trying to connect to the grpc server.
![image](https://user-images.githubusercontent.com/47334253/118850377-b7078900-b89e-11eb-890e-28f4fba19e38.png)
![image](https://user-images.githubusercontent.com/47334253/118850495-d56d8480-b89e-11eb-8a5c-15829ea534b0.png)
![image](https://user-images.githubusercontent.com/47334253/118850550-e4543700-b89e-11eb-9cd7-8298e541f5ff.png)
![image](https://user-images.githubusercontent.com/47334253/118850628-fa61f780-b89e-11eb-8e0f-86d7fe0cefda.png)

I think the grpc issue for the wsl still persists.

**Comment by RutvikGupta** [comment]
When I ran supervisord which ran the following command,
`python examples/single_agent.py scenarios/intersections/6lane`,
I got the gRPC error again but for the 9th episode,

![image](https://user-images.githubusercontent.com/47334253/118852041-62fda400-b8a0-11eb-9707-fbc2d2f380ad.png)

![image](https://user-images.githubusercontent.com/47334253/118852085-701a9300-b8a0-11eb-86f6-fdda22d3f5d0.png)

**Comment by dineshresearch** [comment]
Currently I am also facing the same grpc timeout issue. I am trying to run the marl benchmark example provided 

# from baselines/marl_benchmark/
$ python3.7 run.py <scenario> -f <config_file>
# E.x. python3.7 run.py scenarios/intersections/4lane -f agents/ppo/baseline-lane-control.yaml

But ending up with this issue. I have tested with master branch and release-4.18 branch as well and leading to the same issue.  @Gamenot @Adaickalavan @RutvikGupta can you please kindly help me with the fix soon. 

![image](https://user-images.githubusercontent.com/26215090/142466478-38a72205-c803-4dfc-b3da-ac54d21d8524.png)

**Comment by Adaickalavan** [comment]
@dineshresearch  
Are you using windows susbsystem for linux (WSL) ?

**Comment by dineshresearch** [comment]
I am using VDI machine with ubuntu 18.6 installed

**Comment by Adaickalavan** [comment]
@dineshresearch

**Comment by Adaickalavan** [comment]
This issue is being closed as the grpc functionality has been removed from SMARTS.
