### ISSUE TITLE
Errors and Failures in 'make test'

### ISSUE THREAD

**Issue by wang1351** [huawei-noah/SMARTS#636]
Dear researchers,

When I tried to set up, everything from 52 to the end of 'make test' either had error or failed.
I am new to this. I tried to follow instructions in 'Setup', my computer reported 'no command python3.7' so I used 'conda create'. The 'pip install -e .' for train and test was successful.

Could you please help me with this issue?

**Comment by wang1351** [comment]
Here is the message:

[gw31] [ 52%] ERROR smarts/env/tests/test_hiway_env.py::test_hiway_env
[gw11] [ 53%] ERROR smarts/core/tests/test_controller_lane.py::test_lane_following_controller[scenarios0-agent_and_agent_type0]
smarts/core/tests/test_controller_lane.py::test_lane_following_controller[scenarios0-agent_and_agent_type1]
[gw7] [ 54%] ERROR smarts/core/tests/test_boids.py::test_boids
[gw16] [ 55%] ERROR smarts/core/tests/test_observations.py::test_observations
[gw0] [ 56%] FAILED envision/tests/test_data_replay.py::test_data_replay
[gw1] [ 57%] ERROR smarts/contrib/malib/tests/test_malib_env.py::test_malib_env
[gw2] [ 58%] ERROR smarts/contrib/pymarl/tests/test_pymarl_env.py::test_pymarl_env
[gw27] [ 60%] ERROR smarts/core/tests/test_trap_manager.py::test_capture_vehicle
smarts/core/tests/test_trap_manager.py::test_emit_on_default
[gw32] [ 61%] FAILED smarts/env/tests/test_shutdown.py::test_graceful_shutdown
smarts/env/tests/test_shutdown.py::test_graceful_interrupt
[gw22] [ 62%] ERROR smarts/core/tests/test_smarts_reset.py::test_only_agents_reset_if_scenario_does_not_change
[gw30] [ 63%] FAILED smarts/env/tests/test_determinism.py::test_short_determinism
[gw8] [ 64%] ERROR smarts/core/tests/test_bubble_manager.py::test_bubble_manager_state_change
smarts/core/tests/test_bubble_manager.py::test_bubble_manager_limit[bubble0]
[gw36] [ 65%] FAILED tests/test_examples.py::test_examples[egoless]
tests/test_examples.py::test_examples[single_agent]
[gw33] [ 66%] ERROR smarts/env/tests/test_social_agent.py::test_social_agents
[gw9] [ 67%] ERROR smarts/core/tests/test_bubble_hijacking.py::test_bubble_hijacking
[gw21] [ 68%] ERROR smarts/core/tests/test_smarts.py::test_smarts_doesnt_leak_tasks_after_reset
[gw23] [ 70%] ERROR smarts/core/tests/test_traffic_simulation.py::test_traffic_sim_with_multi_client
[gw10] [ 71%] ERROR smarts/core/tests/test_collision.py::test_sim_level_collision (pid=3193063) Error in atexit._run_exitfuncs:
(pid=3193063) Traceback (most recent call last):
(pid=3193063)   File "/home/zywang/anaconda3/envs/py37smarts/lib/python3.7/site-packages/direct/showbase/ShowBase.py", line 82, in exitfunc
(pid=3193063)     builtins.base.destroy()
(pid=3193063)   File "/home/zywang/SMARTS/smarts/core/smarts.py", line 456, in destroy
(pid=3193063)     self.teardown()
(pid=3193063)   File "/home/zywang/SMARTS/smarts/core/smarts.py", line 431, in teardown
(pid=3193063)     self._agent_manager.teardown()
(pid=3193063) AttributeError: 'SMARTS' object has no attribute '_agent_manager'

[gw34] [ 72%] FAILED smarts/env/tests/test_rllib_hiway_env.py::test_rllib_hiway_env
[gw11] [ 73%] ERROR smarts/core/tests/test_controller_lane.py::test_lane_following_controller[scenarios0-agent_and_agent_type1]
smarts/core/tests/test_controller_lane.py::test_lane_following_controller[scenarios0-agent_and_agent_type2]
[gw27] [ 74%] ERROR smarts/core/tests/test_trap_manager.py::test_emit_on_default
smarts/core/tests/test_trap_manager.py::test_no_recapture_agent
[gw32] [ 75%] FAILED smarts/env/tests/test_shutdown.py::test_graceful_interrupt
[gw8] [ 76%] ERROR smarts/core/tests/test_bubble_manager.py::test_bubble_manager_limit[bubble0]
smarts/core/tests/test_bubble_manager.py::test_vehicle_spawned_in_bubble_is_not_captured
[gw36] [ 77%] FAILED tests/test_examples.py::test_examples[single_agent]
tests/test_examples.py::test_examples[multi_agent]
[gw17] [ 78%] FAILED smarts/core/tests/test_notebook.py::test_notebook1
[gw11] [ 80%] ERROR smarts/core/tests/test_controller_lane.py::test_lane_following_controller[scenarios0-agent_and_agent_type2]
smarts/core/tests/test_controller_lane.py::test_lane_following_controller[scenarios1-agent_and_agent_type0]
[gw27] [ 81%] ERROR smarts/core/tests/test_trap_manager.py::test_no_recapture_agent
[gw8] [ 82%] ERROR smarts/core/tests/test_bubble_manager.py::test_vehicle_spawned_in_bubble_is_not_captured
smarts/core/tests/test_bubble_manager.py::test_vehicle_spawned_outside_bubble_is_captured
[gw36] [ 83%] FAILED tests/test_examples.py::test_examples[multi_agent]
tests/test_examples.py::test_multi_instance_example
[gw11] [ 84%] ERROR smarts/core/tests/test_controller_lane.py::test_lane_following_controller[scenarios1-agent_and_agent_type0]
smarts/core/tests/test_controller_lane.py::test_lane_following_controller[scenarios1-agent_and_agent_type1]
[gw8] [ 85%] ERROR smarts/core/tests/test_bubble_manager.py::test_vehicle_spawned_outside_bubble_is_captured
[gw36] [ 86%] PASSED tests/test_examples.py::test_multi_instance_example
tests/test_examples.py::test_rllib_example
[gw11] [ 87%] ERROR smarts/core/tests/test_controller_lane.py::test_lane_following_controller[scenarios1-agent_and_agent_type1]
smarts/core/tests/test_controller_lane.py::test_lane_following_controller[scenarios1-agent_and_agent_type2]
[gw11] [ 88%] ERROR smarts/core/tests/test_controller_lane.py::test_lane_following_controller[scenarios1-agent_and_agent_type2]
smarts/core/tests/test_controller_lane.py::test_lane_following_controller[scenarios2-agent_and_agent_type0]
[gw11] [ 90%] ERROR smarts/core/tests/test_controller_lane.py::test_lane_following_controller[scenarios2-agent_and_agent_type0]
smarts/core/tests/test_controller_lane.py::test_lane_following_controller[scenarios2-agent_and_agent_type1]
[gw11] [ 91%] ERROR smarts/core/tests/test_controller_lane.py::test_lane_following_controller[scenarios2-agent_and_agent_type1]
smarts/core/tests/test_controller_lane.py::test_lane_following_controller[scenarios2-agent_and_agent_type2]
[gw11] [ 92%] ERROR smarts/core/tests/test_controller_lane.py::test_lane_following_controller[scenarios2-agent_and_agent_type2]
smarts/core/tests/test_controller_lane.py::test_lane_following_controller[scenarios3-agent_and_agent_type0]
[gw36] [ 93%] FAILED tests/test_examples.py::test_rllib_example
[gw11] [ 94%] ERROR smarts/core/tests/test_controller_lane.py::test_lane_following_controller[scenarios3-agent_and_agent_type0]
smarts/core/tests/test_controller_lane.py::test_lane_following_controller[scenarios3-agent_and_agent_type1]
[gw11] [ 95%] ERROR smarts/core/tests/test_controller_lane.py::test_lane_following_controller[scenarios3-agent_and_agent_type1]
smarts/core/tests/test_controller_lane.py::test_lane_following_controller[scenarios3-agent_and_agent_type2]
[gw11] [ 96%] ERROR smarts/core/tests/test_controller_lane.py::test_lane_following_controller[scenarios3-agent_and_agent_type2]
smarts/core/tests/test_controller_lane.py::test_lane_following_controller[scenarios4-agent_and_agent_type0]

**Comment by Gamenot** [comment]
@wang1351 Hello, thank you for reaching out. 

What you have supplied here is not enough to get to the root of the problem however the log suggests that SMARTS failed to initialise:

```
(pid=3193063) Error in atexit._run_exitfuncs:
(pid=3193063) Traceback (most recent call last):
(pid=3193063) File "/home/zywang/anaconda3/envs/py37smarts/lib/python3.7/site-packages/direct/showbase/ShowBase.py", line 82, in exitfunc
(pid=3193063) builtins.base.destroy()
(pid=3193063) File "/home/zywang/SMARTS/smarts/core/smarts.py", line 456, in destroy
(pid=3193063) self.teardown()
(pid=3193063) File "/home/zywang/SMARTS/smarts/core/smarts.py", line 431, in teardown
(pid=3193063) self._agent_manager.teardown()
(pid=3193063) AttributeError: 'SMARTS' object has no attribute '_agent_manager'
```

Could you run `pytest -vv smarts/env/tests/test_hiway_env.py`?

**Comment by wang1351** [comment]
@Gamenot Thank you for your reply! Should I start all over again or run this command in the current environment?

**Comment by Gamenot** [comment]
@wang1351 It looks make test is properly calling into `python3.7`. I assume that the other previous 51% of tests are working so I would suggest running it with your current environment.

**Comment by wang1351** [comment]
@Gamenot 
Thank you for your patience. I updated my pip again and try 'make test'. I noticed that there's an error message:
ERROR: Could not find a version that satisfies the requirement rl-agent==0.1.1
ERROR: No matching distribution found for rl-agent==0.1.1
I find the package should be 'rl-agents'. I'm not sure whether this is the cause.

Now only two lines of errer (instead of everything from 52%):
[gw31] [ 45%] FAILED smarts/env/tests/test_rllib_hiway_env.py::test_rllib_hiway_env
[gw36] [ 97%] FAILED tests/test_examples.py::test_rllib_example

Then I do 'pytest -v smarts/env/tests/test_hiway_env.py', here's the result, status is 'passed': 

platform linux -- Python 3.7.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- /home/zywang/SMARTS/.venv/bin/python3.7
cachedir: .pytest_cache
benchmark: 3.2.3 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/zywang/SMARTS
plugins: notebook-0.6.1, benchmark-3.2.3, xdist-2.2.1, cov-2.11.1, forked-1.3.0
collected 1 item

smarts/env/tests/test_hiway_env.py::test_hiway_env PASSED                                      [100%]

========================================== warnings summary 
.venv/lib/python3.7/site-packages/scipy/fft/__init__.py:97
  /home/zywang/SMARTS/.venv/lib/python3.7/site-packages/scipy/fft/__init__.py:97: DeprecationWarning: The module numpy.dual is deprecated.  Instead of using dual, use the functions directly from numpy or scipy.
    from numpy.dual import register_func

.venv/lib/python3.7/site-packages/scipy/special/orthogonal.py:81
.venv/lib/python3.7/site-packages/scipy/special/orthogonal.py:81
  /home/zywang/SMARTS/.venv/lib/python3.7/site-packages/scipy/special/orthogonal.py:81: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    from numpy import (exp, inf, pi, sqrt, floor, sin, cos, around, int,

smarts/env/tests/test_hiway_env.py: 50 warnings
  /home/zywang/SMARTS/.venv/lib/python3.7/site-packages/scipy/linalg/decomp_qr.py:20: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    kwargs['lwork'] = ret[-2][0].real.astype(numpy.int)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
================================== 1 passed, 53 warnings in 25.33s

**Comment by wang1351** [comment]
@Gamenot 
Hi, I managed to pass all the 'make test', but the issue of 'rl-agent' remains.
Then I tried to run 'scl scenario build --clean scenarios/loop' and then 'supervisord', I got a new error:

ERROR:Client:Connection to Envision terminated with: 15

What could be the cause of the error?

Thanks a lot!

**Comment by Gamenot** [comment]
@wang1351 Hello I am happy to hear that you were able to get it working. 

> ERROR: Could not find a version that satisfies the requirement rl-agent==0.1.1
> ERROR: No matching distribution found for rl-agent==0.1.1
> I find the package should be 'rl-agents'. I'm not sure whether this is the cause.

`rl-agent` can be found at: `zoo/rl-agent/rl_agent-0.1.1-py3-none-any.whl`, however it is currently a neglected dependency that needs to be updated https://github.com/huawei-noah/SMARTS/issues/211. This is fine though since `rl-agent` is not a core dependency.

> ERROR:Client:Connection to Envision terminated with: 15
This error is just the result of thread being cleaned up through timeout when the simulation is exiting. It is a handled error so it is not a problem but I have addressed it in https://github.com/huawei-noah/SMARTS/pull/643 .

**Comment by wang1351** [comment]
@Gamenot Thank you very much!

**Comment by Dikshuy** [comment]
Hello @Gamenot 
I am also facing this error while running the _make test_ command. When I ran this command: pytest -v smarts/env/tests/test_hiway_env.py. I got the following output:

E               FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/share/sumo/bin/sumo': '/usr/local/share/sumo/bin/sumo'

/usr/lib/python3.7/subprocess.py:1551: FileNotFoundError
----------------------------- Captured stdout call -----------------------------
╭────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────╮
│            Episode │     Sim T / Wall T │        Total Steps │        Steps / Sec │       Scenario Map │    Scenario Routes │     Mission (Hash) │             Scores │
├────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┤
╰────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────╯
=========================== short test summary info ============================
FAILED smarts/env/tests/test_hiway_env.py::test_hiway_env - FileNotFoundError...
============================== 1 failed in 4.72s ===============================


Also, my PC freezes at [40%] make always. I have tried a lot of times. can you please help me out in this?

**Comment by wang1351** [comment]
@Dikshuy reopened

**Comment by Gamenot** [comment]
@Dikshuy Thank you for the question.

> Hello @Gamenot
> I am also facing this error while running the _make test_ command. When I ran this command: pytest -v smarts/env/tests/test_hiway_env.py. I got the following output:
> 
> E FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/share/sumo/bin/sumo': '/usr/local/share/sumo/bin/sumo'
> 
> /usr/lib/python3.7/subprocess.py:1551: FileNotFoundError

This error comes from the `$SUMO_HOME` environment variable. Could you check to see if sumo is at `/usr/local/share/sumo/`? The contents should look like:

![image](https://user-images.githubusercontent.com/8764693/110063706-aa60a380-7d39-11eb-9979-e8a759cc55b0.png)

If the directory is not at that location it might also be at `/usr/share/sumo/` and you will need to set it to that location.

> Also, my PC freezes at [40%] make always. I have tried a lot of times. can you please help me out in this?

I will do what I can to help. I think to start this off I would suggest running both of these commands and looking at the log files they put out:

```
PYTHONHASHSEED=42 pytest -v \
		--cov=smarts \
		--forked \
		--dist=loadscope \
		-n `nproc --ignore 1` \
		./smarts/core \
		--ignore=./smarts/core/tests/test_smarts_memory_growth.py \
                > core_test.log
```

and 

```
PYTHONHASHSEED=42 pytest -v \
		--cov=smarts \
		--forked \
		--dist=loadscope \
		-n `nproc --ignore 1` \
		 ./smarts/env \
		--ignore=./smarts/env/tests/test_benchmark.py \
		--ignore=./smarts/env/tests/test_learning.py \
                -k 'not test_long_determinism' \
                > env_test.log
```

**Comment by Dikshuy** [comment]
![Screenshot from 2021-03-05 21-17-52](https://user-images.githubusercontent.com/40022959/110138868-6ed8de80-7df8-11eb-86e6-361a11022761.png)
my SUMO also lies in the same folders as yours. But isn't this location `/usr/share/sumo/`. I have set this as my environment variable in .bashrc using `export SUMO_HOME=/usr/share/sumo`. After rerunning the `pytest -v smarts/env/tests/test_hiway_env.py`, I again got the same error: ` FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/share/sumo/bin/sumo': '/usr/local/share/sumo/bin/sumo'`

**Comment by Dikshuy** [comment]
While trying `make test` again, I still got few errors. I have attached some snapshots of them.
![Screenshot from 2021-03-05 21-51-49](https://user-images.githubusercontent.com/40022959/110144325-3936f400-7dfe-11eb-8a28-a59fe11d26a7.png)
I interrupted the run in between, so at the end, I got sth like this:
![Screenshot from 2021-03-05 21-55-02](https://user-images.githubusercontent.com/40022959/110144422-54a1ff00-7dfe-11eb-806c-7db30819d27f.png)

**Comment by Gamenot** [comment]
@Dikshuy Sorry I was not able to get to your response yesterday, it is hard to tell what the problem is without a stack trace could you run:

`PYTHONHASHSEED=42 pytest -v smarts/core/tests/test_bubble_hijacking.py`

The stack trace from that test should give me enough information.

**Comment by Dikshuy** [comment]
`============================= test session starts ==============================
platform linux -- Python 3.7.10, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- /home/dikshant/github/SMARTS/.venv/bin/python3.7
cachedir: .pytest_cache
benchmark: 3.2.3 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/dikshant/github/SMARTS
plugins: benchmark-3.2.3, notebook-0.6.1, cov-2.11.1, forked-1.3.0, xdist-2.2.1
collected 1 item                                                               

smarts/core/tests/test_bubble_hijacking.py::test_bubble_hijacking PASSED [100%]

============================== 1 passed in 50.98s ==============================`

here's what I got after running this

**Comment by Gamenot** [comment]
@Dikshuy Hi sorry, I thought that would have crashed I think it would be best to check the earliest failing test:

`PYTHONHASHSEED=42 pytest -v smarts/core/tests/test_bubble_manager.py`

**Comment by Dikshuy** [comment]
@Gamenot 
the first test succeeded. but in the second test, it throws this error, and then it stopped. 
`3003 -> wrong number of parameters: 75 != 76`

**Comment by Dikshuy** [comment]
@Gamenot, thanks for your reply!
I have changed the sumo_headless = False and then ran the single_agent example. This time `SUMO` loads up and the simulations started but I have few doubts:
1. it was expected that it's a single agent case so only one vehicle should load up on sumo but the vehicles count keep on increasing up to 21 vehicles.
2. in the terminal, it still shows the same output: `3003 -> wrong number of parameters: 75 != 76` but the vehicles are moving in the SUMO.

**Comment by Gamenot** [comment]
> it was expected that it's a single agent case so only one vehicle should load up on sumo but the vehicles count keep on increasing up to 21 vehicles.

Yes, there is only one ego vehicle in there (coloured red) and then a number of other social vehicles. These vehicles are defined in the file `scenarios/loop/scenario.py`. The flows in in that file generate a stream of vehicles.

> in the terminal, it still shows the same output: 3003 -> wrong number of parameters: 75 != 76 but the vehicles are moving in the SUMO.

I believe this is a problem due to the `open-agent` not matching the solver it needs, this was an oversight on our part. I could suggest `pip install open-agent==0.0.0` to fix this.

**Comment by Gamenot** [comment]
@Dikshuy Hi I would suggest not worrying so much about passing `make test`, `test_rllib_example` and `test_rllib_hiway_env` tend to use up a lot of cpus so there is the possibility that they will time out when running `make test`.

If you are intending to do training I could suggest providing the error logs from: 

```bash
scl scenario build scenarios/loop --clean
PYTHONHASHSEED=42 pytest -v ./tests/test_examples.py::test_rllib_example
```

If there is an error you will see somewhere in the console history something like:

```
Number of trials: 1/1 (1 ERROR)
+-------------------------------+----------+-------+
| Trial name                    | status   | loc   |
|-------------------------------+----------+-------|
| PPO_RLlibHiWayEnv_77287_00000 | ERROR    |       |
+-------------------------------+----------+-------+
Number of errored trials: 1
+-------------------------------+--------------+----------------------------------------------------------------------------------------------------------------------------+
| Trial name                    |   # failures | error file                                                                                                                 |
|-------------------------------+--------------+----------------------------------------------------------------------------------------------------------------------------|
| PPO_RLlibHiWayEnv_77287_00000 |            1 | /home/dev/.smarts/smarts_rllib_smoke_test/RLlibHiWayEnv test/PPO_RLlibHiWayEnv_77287_00000_0_2021-03-13_15-19-51/error.txt |
+-------------------------------+--------------+----------------------------------------------------------------------------------------------------------------------------+

------------------------------------------------------------------------ Captured stderr call -------------------------------------------------------------------------
```

If it crashes you will want to look at that error.txt file.

**Comment by wang1351** [comment]
@Gamenot Hi, sorry to reopen this again. I tried to install latest version of SMARTS and got stuck at 'make test' again.
The error is 

(pid=3840539)   File "/home/zywang/smarts/lib/python3.7/site-packages/direct/showbase/ShowBase.py", line 82, in exitfunc
(pid=3840539)     builtins.base.destroy()
(pid=3840539)   File "/home/zywang/SMARTS/smarts/core/smarts.py", line 459, in destroy
(pid=3840539)     self.teardown()
(pid=3840539)   File "/home/zywang/SMARTS/smarts/core/smarts.py", line 431, in teardown
(pid=3840539)     if self._agent_manager is not None:
(pid=3840539) AttributeError: 'SMARTS' object has no attribute '_agent_manager'

is there any solution?

Thanks.

**Comment by Gamenot** [comment]
> @Gamenot Hi, sorry to reopen this again. I tried to install latest version of SMARTS and got stuck at 'make test' again.
> The error is
> 
> (pid=3840539) File "/home/zywang/smarts/lib/python3.7/site-packages/direct/showbase/ShowBase.py", line 82, in exitfunc
> (pid=3840539) builtins.base.destroy()
> (pid=3840539) File "/home/zywang/SMARTS/smarts/core/smarts.py", line 459, in destroy
> (pid=3840539) self.teardown()
> (pid=3840539) File "/home/zywang/SMARTS/smarts/core/smarts.py", line 431, in teardown
> (pid=3840539) if self._agent_manager is not None:
> (pid=3840539) AttributeError: 'SMARTS' object has no attribute '_agent_manager'
> 
> is there any solution?
> 
> Thanks.

@wang1351 Thank you for reaching out again, I tried to reproduce this bug but was unable to. I believe the way this bug would occur is if the SMARTS instance threw an exception earlier in instantiation and could have a large range of causes. 

If you are not using RLlibHiWayEnv I could suggest ignoring this failure. Otherwise, please run `pytest -vv tests/test_examples.py::test_rllib_example > rllib_example_log.txt` and, if the test fails, supply the output log.

**Comment by wang1351** [comment]
@Gamenot 

The pytest did not return anything. I can't pass the make test. I will contact you again when I restart to set up SMARTS. Thanks.

**Comment by Gamenot** [comment]
@mansur007 Thank you for the question. We have found that those two tests are failing for SMARTS v0.4.15 in part due to not locking down the dependencies. It is not a problem if those two tests fail.

The next version of SMARTS will be removing the instructions to run `make test`.

**Comment by mansur007** [comment]
> @mansur007 Thank you for the question. We have found that those two tests are failing for SMARTS v0.4.15 in part due to not locking down the dependencies. It is not a problem if those two tests fail.
> 
> The next version of SMARTS will be removing the instructions to run `make test`.

thank you for your prompt reply, I pulled the newest version and ran `make sanity-test ` and it passes all 8 tests
