### ISSUE TITLE
Store the processed mission object from history json file as a temporary binary file

### ISSUE THREAD

**Issue by JingfeiPeng** [huawei-noah/SMARTS#640]
**Is your feature request related to a problem? Please describe.**
The `fetch_agent_missions` method in `traffic_history_service` currently could potentially loop through a large large json file by `ijson.kvitems(...)` but only the first occurrence of each vehicle is needed to construct the mission. 

**Describe the solution you'd like**
If multiple scenarios use the same history file, it would be good to store the final mission object as a binary file and load if we need the missions again for a different scenario.

**Additional context**
_Originally posted by @Gamenot in https://github.com/huawei-noah/SMARTS/pull/634#discussion_r585156257_

**Comment by Gamenot** [comment]
A potential here is that we could create this file as a part of the conversion of the NGSIM dataset.

**Comment by JingfeiPeng** [comment]
yes and intersection_data_set_merging. 

Though `ijson.kvitems` is also used at two other places: init of `Traffic_history_service` to know all the timestamp and initial batch of history, and in child process to fetch next batch of history. It might be interesting to have the first looping over the json file to also store multiple partitions of original large history file as binary files. Then load these binary files in child process instead of looping original json file again

**Comment by JingfeiPeng** [comment]
Addressed in PR #681
