### ISSUE TITLE
Ultra GridSearch

### ISSUE THREAD

**Issue by adreena** [huawei-noah/SMARTS#656]
**Is your feature request related to a problem? Please describe.**
Adding gridSearch ability to train.py

**Describe the solution you'd like**
this requires some changes to params.yaml, here is an example of the config we need to pass to tune.run():
```son
config = {
    "encoder": tune.sample_from(["no_encoder", "precog_encoder", "pointnet_encoder"]),
    "l2": tune.sample_from(lambda _: 2**np.random.randint(2, 9)),
    "lr": tune.loguniform(1e-4, 1e-1),
    "batch_size": tune.choice([2, 4, 8, 16])
}
```

At each trial, Ray Tune will randomly sample a combination of parameters from these search spaces. It will then train a number of models in parallel and find the best performing one among these. 

- We need to use the a scheduler to terminate bad performing trials early.
- We also need a reporter to report metrics to tune.
- Evaluation design needs to be reconsidered [ we might need to treat it like RLlib]

Tasks:
- [x] change params.yaml to params.py and change them to tune objects for all baselines
  - Have a separate params.yaml and tune_params.py
- [x] decide on model termination criteria `get_best_trial("loss", "min", "last")`
  - You can specify this in the command line flags
- [x] check Tensorboard handles and make sure they're descriptive enough [indicating which experiment is related to which plots? if the files are saved correctly in directories of experiments]
- [x] report the best model at then end of search 
- [x] figure out if we need the `reporter = CLIReporter(metric_columns=["loss", "accuracy", "training_iteration"])` it might be necessary for early termination of training trials
  - `CLIReporter` is the default `progress_reporter`, its output can be suppressed by specifying the `log_to_file` parameter or the `verbose` parameter
  - The scheduler is what determines early termination of trials
- [x] handle evaluation in each training [ do we need to evaluate for all trials or we keep evaluation just for the best result?] @AlexLewandowski we need to discuss evaluation for grid search
  - Solution: Do evaluation with the best config after with the best config is found
  - The best config is saved as a .yaml so we could just use this file and run evaluate.py?
   

@christianjans @JenishPatel99 I am still in the middle of implementing things but feel free to take a look at `ultra-gs` ppo, we can discuss it in details

**Comment by christianjans** [comment]
Hi @adreena, regarding the Tensorboard experiment results, they seem to be saved in `/root/ray_results/` by default. In here, each tune experiment is given a directory, and each training session of a model run during the tuning is given a subdirectory of this experiment's directory to put the logs, data, and their own Tensorboards in. For example:

```sh
/root/
└── ray_results/
    └── DEFAULT_\<time-tune-experiment-was-run\>/  # The experiment directory
        ├── DEFAULT_\<description-of-model-1\>/  # Model's directory
        ├── DEFAULT_\<description-of-model-2\>/
         .
         .
         .
        └── DEFAULT_\<description-of-model-n\>/
```
Therefore, I don't think we have to worry about the Tensorboard handles between experiments because the results are all logged independently. Let me know if there are any other concerns with this though.

**Comment by christianjans** [comment]
Hi @adreena, the new branch regarding this issue is https://github.com/huawei-noah/SMARTS/tree/ultra_tune.

**Comment by adreena** [comment]
> Hi @adreena, the new branch regarding this issue is https://github.com/huawei-noah/SMARTS/tree/ultra_tune.

could you make a temporary pull request to compare the changes against the latest ultra?

**Comment by christianjans** [comment]
> > Hi @adreena, the new branch regarding this issue is https://github.com/huawei-noah/SMARTS/tree/ultra_tune.
> 
> could you make a temporary pull request to compare the changes against the latest ultra?

Sure thing!
