### ISSUE TITLE
3003 -> wrong number of the 75!=76

### ISSUE THREAD

**Issue by guanjiayi** [huawei-noah/SMARTS#678]
**High Level Description**
[Solution the wrong warning]

**Desired SMARTS version**
[e.g. 0.5]

**Operating System**
[ ubuntu 18.04]

**Problems**
[3003 -> wrong number of the 75!=76]

**Comment by Gamenot** [comment]
@guanjiayi Hello, sorry, this is a oversight in the current version of SMARTS that does not specify the exact dependency so it installs the wrong version of the solver for the open agent. It is possible to fix this warning using `pip install python-bindings-open-agent-solver==0.05`.

The other option is to use the dummy `open-agent` which is just a laner by using `pip install open-agent==0.0.0`.

**Comment by guanjiayi** [comment]
@Gamenot  Thank you for your reply!
