### ISSUE TITLE
Improve visibility of SMARTS Paper

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#690]
Ensure that it is easy to view the SMARTS paper from the documentation on the following sites:

- [ ] readthedocs
- [x] github
- [x] pypi

**Comment by JingfeiPeng** [comment]
github readme now has reference to the SMARTS paper.
Pypi's project description will be updated with the new readme when we release a new version
Can add a reference to SMARTS paper in documentation (`readthedocs`) while addressing issue #689

**Comment by JingfeiPeng** [comment]
closed with #701
