### ISSUE TITLE
Map a mission to a specific agent

### ISSUE THREAD

**Issue by JingfeiPeng** [huawei-noah/SMARTS#707]
**Is your feature request related to a problem? Please describe.**
Currently missions in scenario are mapped based on an order to agents in example files

**Describe the solution you'd like**
We need to figure out a way for direct mapping of mission to agents. 1 possible solution is to specify the mission ids in scenario and make example code import missions in scenario and map its agents to that.

**Describe alternatives you've considered**
Specifying target agent ids in the mission definition in scenario. However this makes scenarios tightly coupled with examples. This is not a good approach

**Comment by saulfield** [comment]
@Gamenot is this fixed by #1868? Please reopen if not.
