### ISSUE TITLE
Vehicle locations in sumo-gui does not match vehicle positions on envision

### ISSUE THREAD

**Issue by JingfeiPeng** [huawei-noah/SMARTS#716]
## **BUG REPORT**
**High Level Description**
The vehicle positions in sumo_gui are different from vehicle postions in envision

**SMARTS version**
0.4.15

**Previous associated issues**
This might be related to previous map location offset PR #673 

**Steps to reproduce the bug**
checkout `multi_agent_demo` branch, commit id: 4aee20350b97899bf202b6f3963a9f0b401b53c6 and run 
"python examples/game_of_tag.py scenarios/demo/"
Though vehicle positions in other scenarios worked fine. This might be related to the map creation

**Resulting and expected behaviour**
vehicle locations on sumo-gui should match postions in Envision

**Error logs and screenshots**
The envision vehicle position looks correct
![image](https://user-images.githubusercontent.com/36685292/112709676-d7fcc080-8e91-11eb-84e9-497a8b24042b.png)
sumo_gui vehicle positions are incorrect
![image](https://user-images.githubusercontent.com/36685292/112709650-a552c800-8e91-11eb-8ebb-4e1b64b88604.png)

**Comment by sah-huawei** [comment]
Yeah, it looks like the shift to the net file is not being passed to Sumo in `_base_sumo_load_params()`.  Need to rethink PR #673.
