### ISSUE TITLE
Accomodate image observations in ULTRA

### ISSUE THREAD

**Issue by AlexLewandowski** [huawei-noah/SMARTS#724]
**Is your feature request related to a problem? Please describe.**
Image observations are offered in SMARTS but not currently in ULTRA

**Describe the solution you'd like**
An option to use image features. Will likely require framestacking, but we can downsample and use greyscale to lower the dimension of the inputs. Would also require updating the baselines to accomodate this, there is already some CNN code for TD3 and BDQN. 

**Describe alternatives you've considered**
N/A

**Additional context**
We can either use images in addition to low-dim states (images replace social vehicles), or images alone. The images observations can be used as a sanity check for social vehicle interaction, but will require more compute.

**Comment by christianjans** [comment]
See https://github.com/huawei-noah/SMARTS/tree/ultra_baseline_image_observations for an initial implementation. DQN, BDQN, and TD3 all can support RGB image observations (turned to stacked grayscale images during preprocessing) using their CNNs.

It is far from ready to be merged (if that is what we intend to do), but it allows for training with images and low dimensional states as input.

**Comment by AlexLewandowski** [comment]
Looks pretty good! I'll run some experiments over the weekend and see if this helps the collision problem.
