### ISSUE TITLE
Possible to add vehicle's waypoints to VehicleObservation?

### ISSUE THREAD

**Issue by christianjans** [huawei-noah/SMARTS#726]
**Is your feature request related to a problem? Please describe.**
Currently, SMARTS' VehicleObservation does not contain the waypoints the vehicle is following. Experiments in ULTRA may need these waypoints of the neighbourhood vehicles as extra observation information.

**Describe the solution you'd like**
To be able to have a vehicle's waypoints be part of its VehicleObservation, similar to how the waypoints of the ego vehicle are included Observation if the ego vehicle is subscribed to a waypoint sensor. Perhaps this can be another subscription, where the ego vehicle will receive the waypoint paths of the neighbourhood vehicles if it is subscribed to a "neighbourhood waypoint sensor" or something like that.

**Describe alternatives you've considered**
Perhaps this would require adding a `waypoints` attribute to the VehicleObservation? https://github.com/huawei-noah/SMARTS/blob/6cb8ffda74e235c25d63b74313623b2e03e402f7/smarts/core/sensors.py#L54-L62 And then include it in the VehicleObservation of the neighbourhood vehicles if the ego vehicle is subscribed to the "neighbourhood waypoint sensor". https://github.com/huawei-noah/SMARTS/blob/6cb8ffda74e235c25d63b74313623b2e03e402f7/smarts/core/sensors.py#L183-L204

**Additional context**
Let me know if you need any more context or have any questions. We are currently still obtaining more information about this proposed experiment and will update this issue with any new information.

**Comment by christianjans** [comment]
Hi @Gamenot, just wondering if you or other SMARTS members have had a chance to look at this yet. Tagging @Elvirawzy too, as she is the one looking to use this functionality if it becomes available.

**Comment by Adaickalavan** [comment]
User may deduce the past trajectories of neighbourhood vehicles and predict their future trajectories, albeit probably incompletely, by looking at the ego's `observation.neighborhood_vehicle_states[<neighbor>].position` values. The SMARTS observation of each ego agent at each time point does not describe the future trajectories of neighbourhood vehicles as it is not reasonable to exactly know this information in real life.
