### ISSUE TITLE
Add `step()` and `save()` methods to `smarts.core.agent.Agent`

### ISSUE THREAD

**Issue by christianjans** [huawei-noah/SMARTS#748]
**Is your feature request related to a problem? Please describe.**
Include abstract or default implementations of `step(*args, **kwargs) -> dict` and `save(path: str, *args, **kwargs)` (or those methods with similar arguments) to: https://github.com/huawei-noah/SMARTS/blob/6cb8ffda74e235c25d63b74313623b2e03e402f7/smarts/core/agent.py#L34-L59 Ideally, maybe something like:
```python
    def step(*args, **kwargs) -> dict:
        """Updates the agent, returns a dictionary of information
        with the agent's update stats (such as NN loss).
        """
        return dict()

    def save(path: str, *args, **kwargs):
        """Saves the state of the agent so that it can be loaded
        from the same path.
        """
        pass
```

**Describe the solution you'd like**
Add the `step` method to SMARTS' Agent class because:
- It is needed for RL agents to add to a replay buffer (if they have one) and update their NNs (if they have any)

Add the `save` method to SMARTS' Agent class because:
- It allows the agent to save its state (without serializing) so that it can be loaded in other processes

**Additional context**
Kimia was mentioning how there were `save` and `load` methods (and potentially a `step` method?) in `smarts.core.agent.Agent` before. ULTRA uses these methods (`step` and `save`) since it was created when these methods were part of the Agent class. Any way to add them back?

@adreena, feel free to edit or comment if I have missed anything.

**Comment by Adaickalavan** [comment]
From experience, 
+ agent class methods `step` and `save` are not mandatory.
+ methods added by default such as `step` and `save` in the `Agent` class might not be actively used by end-users.
+ end-users mostly prefer to write their own agent or policy code to suit their individual needs.

Therefore this issue is being closed.
