### ISSUE TITLE
Model for two wheel vehicles

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#755]
A new model is needed to represent 2-wheeled vehicles. this will require a `.glb` and blender `.blend` file as well as a default physics model file `.urdf`.

AC:
- [x] Model file in `glb` format
- [x] Model file for editing in `.blend` format
- [ ] Physics parameters for model in `.urdf` format

**Comment by JingfeiPeng** [comment]
closes with #767 , physics urdf file no longer needed
