### ISSUE TITLE
Containerized Interaction Scenario Service

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#76]
Scenario service characterized by social agent interaction.

1. Design the service, in terms of functionalities and interfaces. Once we have the design, then next is the architecture, think about what are we going to put behind the service, can we draw a solid line between the service and SMARTS, etc.
2. Based on the design, we can ship a workable prototype in 0.4.3.
3. Collect feedbacks from ChenDong's team and keep polishing the service.
4. Warp thing in the container.

Actions:
- [x] Dockerfile @Adaickalavan 
- [x] Test building image and run the service inside a container @JingfeiPeng

**Comment by Adaickalavan** [comment]
Perhaps we can start by choosing an approrpiate Python REST server library which we would like to use.

**Comment by Adaickalavan** [comment]
This issue is addressed in a separate repository. A pull request is currently in progress in the other repository. A Dockerfile to build a Docker image is provided in the pull request.

**Comment by JingfeiPeng** [comment]
I get this error when running 
```
Collecting zope.interface==5.2.0
  Downloading zope.interface-5.2.0-cp37-cp37m-manylinux2010_x86_64.whl (237 kB)
INFO: pip is looking at multiple versions of absl-py to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r /src/requirements.txt (line 2) and chardet==4.0.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested chardet==4.0.0
    aiohttp 3.7.3 depends on chardet<4.0 and >=2.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```
Should I change the chardet version to be <4.0.0?

**Comment by JingfeiPeng** [comment]
```
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
(EE) 
Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE) 
(EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
```
Met this error when attempting to run server using
```
docker run \
    --rm \
    -it \
    --network=host \
    --device="/dev/input:/dev/input" \
    --env="DISPLAY=:1" \
    --volume=<path/to/external/agents>:/src/agents \
    --volume=<path/to/external/scenarios>:/src/scenarios \
    smarts-service
```
Are we supposed to open display in a docker container?

**Comment by JingfeiPeng** [comment]
Finished action and updated README on gitlab repo
