### ISSUE TITLE
Can not get social vehicle id with history replay scenarios

### ISSUE THREAD

**Issue by zbzhu99** [huawei-noah/SMARTS#762]
## **BUG REPORT**
**High Level Description**
Can not get social vehicle id with interaction dataset merging scenario.

**SMARTS version**
0.4.14, the latest `develop` branch

**Previous associated issues**
None

**Steps to reproduce the bug**
Run the example script `examples/observation_collection_for_imitation_learning.py` on INTERACTION dataset merging scenario which is attached below:

[interaction_dataset_merging.zip](https://github.com/huawei-noah/SMARTS/files/6301432/interaction_dataset_merging.zip)

**Resulting and expected behaviour**
smarts.vehicle_index.social_vehicle_ids() is expected to return available vehicle ids but return an empty set.
https://github.com/huawei-noah/SMARTS/blob/f9c0f08702dc4a0a1e8874022d84b3688e10942b/examples/observation_collection_for_imitation_learning.py#L36

**System information**
 
- Operating system & Environment [Please note if using Docker]: Ubuntu 16.04
- Number of system cores available
- Python version [Please note if using Jupyter] 3.7.9
- Python packages [e.g. from `pip freeze`]
- SUMO version 1.8.0
- Date when bug occurred 2021.4.13

**Comment by sah-huawei** [comment]
Thanks for filing this.  
This seems to work for me on my local `develop` branch (and the `.shf` files in the attached scenario seem fine), so I'm thinking it's either  (a) related to not having a `Renderer` or (b) some environmental difference related to `sqlite3` (which is used to query for the social vehicle ids).

Re (a), this could be related to Issue #696.  Even though SMARTS can now _start_ without a display, if/when you try to add camera-based sensors to a vehicle (which require a `Renderer`, which still requires a display), it will throw an exception.  In the case of `examples/observation_collection_for_imitation_learning.py`, it is going to try to do that in the `attach_sensors_to_vehicles()` call.  So I would expect the example to fail there if not in a docker container (and it might still once we solve this problem).  However, it seems it's not even getting _that_ far, so...

Re (b), could you please attach all of the messages (i.e., stdout and stderr) that appear in your console/terminal window when you run this?  I am wondering if there may be some clue there.

P.S.  re (a), I would also be interested to know if it acts any differently if you try to run it from a docker container (cf. #696).

**Comment by zbzhu99** [comment]
I tried to run the same code inside the docker, and the function still returns an empty set.

**Comment by zbzhu99** [comment]
I tried to run the same code inside the docker, and the function still returns an empty set.
It does not appear to have any stdout or stderr on console when I run the code.

**Comment by sah-huawei** [comment]
@zbzhu99 and I figured this out together.  It's because no data was being returned _at `sim_time=0`_, it all started at `sim_time=0.1` in the Interaction merging dataset.  I will update `genhistories.py` to ensure that the history actually starts at `sim_time=0`.

**Comment by sah-huawei** [comment]
PR #766 should fix this and has now been merged into `develop`.
@zbzhu99 this will require rebuilding your scenario, for exmample:  `scl scenario build --clean scenarios/interaction_dataset_merging`
