### ISSUE TITLE
Problem with RGB image colours when converting to gray-scale?

### ISSUE THREAD

**Issue by christianjans** [huawei-noah/SMARTS#768]
**Is your feature request related to a problem? Please describe.**
The colour values for the road and ego vehicle are similar when converting to gray-scale:
```sh
(.venv) $ python
>>> import numpy as np
>>> from smarts.core.colors import SceneColors
>>>
>>> gray_scale_weights1 = [0.2125, 0.7154, 0.0721]  # ~ A common gray-scale weighting
>>> gray_scale_weights2 = [1 / 3, 1 / 3, 1 / 3]  # Equal weighting
>>> ego_colour = SceneColors.Agent.value[:-1]  # Get RGB from RGBA
>>> road_colour = SceneColors.Road.value[:-1]  # Get RGB from RGBA
>>>
>>> np.dot(ego_colour, gray_scale_weights1)
0.26764705882352946
>>> np.dot(road_colour, gray_scale_weights1)
0.3137254901960784
>>> np.dot(ego_colour, gray_scale_weights2)
0.3529411764705882
>>> np.dot(road_colour, gray_scale_weights2)
0.3137254901960784
```
This may make it harder for RL agents using image observations to learn.

**Describe the solution you'd like**
If this is known to cause problems in learning for RL agents, perhaps the default colour values for either the ego vehicle or the road can be changed.

**Additional context**
Has an issue like this been brought up before? Have people trained RL agents with image observations (and these same colours) and had success?

**Comment by christianjans** [comment]
Hi @Gamenot, this was the issue I was planning to bring up in the meeting. In addition to the questions in this issue, a few other questions I had were:
1. I noticed that some DAI Competition agents used the top-down RGB image observation, but I was unable to find the specifics (i.e. whether they converted to gray-scale, used frame-stacking, etc.) of how they did it. Do you, or anyone from the SMARTS team remember how these competition agents processed the top-down RGB observation?
2. Do you know of any SMARTS users who have used the top-down RGB image in their research or project?
3. Does SMARTS support frame-stacking of the top-down RGB image? If not, are there plans to?

**Comment by Adaickalavan** [comment]
1) SMARTS currently supports frame-stacking for rgb images, via the `FrameStack` environment wrapper.

2) Consider the following for rgb conversion to grayscale and to preprocess images.
    ```python
    import numpy as np
    from skimage.color import rgb2gray
    from smarts.core.sensors import Observation
    
    def observation_adapter(obs: Observation) -> np.ndarray:
        # RGB grid map
        rgb = obs.top_down_rgb.data
        
        # Convert rgb to grayscale image
        grayscale = rgb2gray(rgb)
        
        # Center frames
        frame = grayscale * 2 - 1
        frame = frame.astype(np.float32)
        
        return frame
    ```
