### ISSUE TITLE
Attempting to perform action on non-existing agent

### ISSUE THREAD

**Issue by Adaickalavan** [huawei-noah/SMARTS#778]
## **BUG REPORT**
See: 
https://github.com/huawei-noah/SMARTS/blob/c071d5349a8046ef512e4deb523c900eff5b56b5/examples/multi_agent.py#L46-L53

Observation is generated for done agents on the last step when the agent becomes done. This done agent's observation is processed in the next environment iteration. A sample print-out of the simulation state is shown below for better illustration.

```
-----------------------------------------------
obs before =  dict_keys(['Agent 0', 'Agent 1'])
actions =  {'Agent 0': 'keep_lane', 'Agent 1': 'keep_lane'}
dones =  {'Agent 0': True, 'Agent 1': False, '__all__': False}
obs after=  dict_keys(['Agent 0', 'Agent 1'])
===============================================

-----------------------------------------------
obs before =  dict_keys(['Agent 0', 'Agent 1'])
actions =  {'Agent 0': 'keep_lane', 'Agent 1': 'keep_lane'}
WARNING:SMARTS:Attempted to perform actions on non-existing agent, Agent 0
dones =  {'Agent 1': False, '__all__': False}
obs after=  dict_keys(['Agent 1'])
===============================================

-----------------------------------------------
obs before =  dict_keys(['Agent 1'])
actions =  {'Agent 1': 'keep_lane'}
dones =  {'Agent 1': False, '__all__': False}
obs after=  dict_keys(['Agent 1'])
===============================================
```

**SMARTS version**
0.4.15

**Previous associated issues**
None

**Steps to reproduce the bug**
Run the following:
```bash
$ cd /path/to/SMARTS/
$ python3.7 ./examples/multi_agent.py ./scenarios/intersections/6lane/
```

**Resulting and expected behaviour**
Result: 
+ Warning message is printed: `WARNING:SMARTS:Attempted to perform actions on non-existing agent, Agent_001`
+ Attempted to step done agent 

Expected: 
+ No message printed.
+ Don't attempt to step done agent.

**Error logs and screenshots**
![image](https://user-images.githubusercontent.com/24203326/115250820-eee0ac80-a0f7-11eb-8b77-715f0b8d023a.png)
 
**System information**
- Operating system & Environment [Please note if using Docker]: Ubuntu 16.04
- Number of system cores available: 16
- Python version [Please note if using Jupyter]: Python3.7
- Python packages [e.g. from `pip freeze`]
- SUMO version: 1.8.0
- Date when bug occurred: 19 April 2021
 
**Impact [If known]**
+ Unnecessary consideration of done agent

**Comment by christianjans** [comment]
Also experienced in ULTRA's `train.py` and `evaluate.py` when simulating multiple ego agents.

**Comment by Adaickalavan** [comment]
In hindsight, having trained multi-agent multi-environment examples, printing a warning to alert the user of `done` agents might be better than silently ignoring the `done` agents in `step`.

**Comment by wanzi96** [comment]
Has this problem been solved, please? I'm having this problem too.
