### ISSUE TITLE
Minimal SMARTS with only the Core Dependencies

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#78]
Add a minimum setup option that only contains the packages needed to run the most basic SMARTS scenarios.

The examples should be modularised with their own separate requirements so that their dependencies do not pollute the core of SMARTS.

**Comment by davidrusu** [comment]
* examples should have requirements.txt next to example files
```
/examples
  /rllib_agent
    - requirements.txt
    - ...
  /open_agent
    - requirements.txt
    - main.py
```
* We have some very large dependencies, lets see if we can replace them with minimal packages that do just what we need.
  * scipy
  * sklearn
  * opencv

**Comment by liamchzh** [comment]
Or we can have different modes for doing research and running SMARTS core.

**Comment by saulfield** [comment]
Superseded by #1981.
