### ISSUE TITLE
Physics off in 0.4.16 pre-release

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#790]
## **BUG REPORT**
**High Level Description**
Physics is off, causing the ego vehicle to not collide.

**SMARTS version**
SMARTS develop branch 6cb8ffda74e235c25d63b74313623b2e03e402f7 .

This issue does not occur in master (i.e. 0.4.15.)

**Previous associated issues**
https://github.com/huawei-noah/SMARTS/issues/716

**Steps to reproduce the bug**
Run the following `python3.7 examples/single_agent.py cutin_stopped_vehicle_2lane` with this scenario: 
[cutin_stopped_vehicle_2lane.zip](https://github.com/huawei-noah/SMARTS/files/6363278/cutin_stopped_vehicle_2lane.zip)
 

**Resulting and expected behaviour**
Collision should occur between SMARTS agent and sumo traffic vehicke, ending the vehicle early, traffic vehicles ends up in correct location SUMO GUI but totally different location in SMARTS.

**Error logs and screenshots**
![image](https://user-images.githubusercontent.com/8764693/115812284-246aeb80-a3bf-11eb-8937-5f4355311f9e.png)

**Comment by sah-huawei** [comment]
@Gamenot Could you also please attach `scenarios/straightaway_2e` (referenced on line 10 of `cutin_stopped_vehicle_2lane_tmp/scenario.py`).  
Given the screenshot above, I am trying to run `scl scenario build scenarios/cutin_stopped_vehicle_2lane_tmp` in  order to double-check that the creation of the `.glb` for Envision correctly used the shifted map.

**Comment by Gamenot** [comment]
Sorry, yes, I commented out part of the file and forgot to remove the copy functionality. The file is already there named as `map.net.xml`
[cutin_stopped_vehicle_2lane.zip](https://github.com/huawei-noah/SMARTS/files/6363282/cutin_stopped_vehicle_2lane.zip)
