### ISSUE TITLE
Connection closed by SUMO when doing imitation learning

### ISSUE THREAD

**Issue by zbzhu99** [huawei-noah/SMARTS#803]
## **BUG REPORT**
**High Level Description**
SMARTS will raise the "Connection closed by SUMO" error when doing imitation learning experiments.

**SMARTS version**
0.4.15

**Steps to reproduce the bug**
When running imitation learning experiments, we need to replay the same history data multiple times. But from my test, it will cause the connection error of SUMO when we do the data replay more than one time.

Add a loop to run the following code twice:

https://github.com/huawei-noah/SMARTS/blob/6cb8ffda74e235c25d63b74313623b2e03e402f7/examples/history_vehicles_replacement_for_imitation_learning.py#L28-L60

And the error will be raised on the (about) 335th agent at the second loop time.

**System information**
 
- Operating system & Environment [Please note if using Docker]: **outside** Docker
- Number of system cores available
- Python version 3.7.10
- SUMO version 1.8.0
 
**Impact [If known]**

**Comment by sah-huawei** [comment]
Since this seems to be a crash within Sumo (or Traci), and since Sumo isn't needed when replaying traffic histories, we are going to try simply bypassing Sumo traffic for now.

(Of course, we should eventually circle back and try to understand why Sumo is crashing.)
