### ISSUE TITLE
Severe Memory Leak In `scenarios/loop`

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#805]
## **BUG REPORT**
**High Level Description**
@guanjiayi I am sorry for the length of time it took to discover where the problem is coming from. I have done some tests and confirmed that the configurations from the AgentInterface are not causing leaks. However, I have confirmed that the `intersection/loop` scenario has a bad memory leak and that the `rl-agent:rl-agent-v0` agents also does not properly manage memory. I am trying to narrow down the specific source of the problem.

This problem also appears to exist on all versions of SMARTS.

_Originally posted by @Gamenot in https://github.com/huawei-noah/SMARTS/issues/794#issuecomment-829316164_

**SMARTS version**
0.4.12 - 0.4.15

**Previous associated issues**
#794

**Steps to reproduce the bug**
`python3.7 examples/single_agent.py scenarios/loop --headless --episodes 1000`

**Resulting and expected behaviour**
Memory will quickly grow and roughly reach 16gb at 1000 episodes.

**Error logs and screenshots**
[Text or screenshots (preferably text)]
 
**System information**
 
- Operating system & Environment [Please note if using Docker]:
Ubuntu 18.04 LTS
- Number of system cores available
16
- Python version [Please note if using Jupyter]
3.7.5
- Python packages [e.g. from `pip freeze`]
[req.txt](https://github.com/huawei-noah/SMARTS/files/6399729/req.txt)
- SUMO version
Eclipse SUMO sumo Version 1.9.0
- Date when bug occurred
2021-04-29
 
**Impact [If known]**
Excessive memory usage blocking training.

**Comment by sah-huawei** [comment]
as another datapoint/clue:  I haven't been able to reproduce this myself.  I tried with both the current tips of `master` and the `develop` branch.  I'm using that same setup as you (Ubuntu 18.04, python 3.7.5, etc.) with the exception of less cores. I only ran for about 200 episodes on each branch, but the memory profile didn't budge throughout that.

So maybe there's something more complex than just a straightforward leak going on?

**Comment by Gamenot** [comment]
I managed to narrow this down to some extent. The larger kind of growth I am seeing is in virtual memory, which is increasing quite rapidly. I think virtual memory is an os optimisation so depending on the os settings it could cause a crash. Although even without tracking I am also seeing a small uptick in regular memory as well.

This memory growth goes away when I remove the social agents.
