### ISSUE TITLE
Scaling the StateQueue on client.js to prevent it from getting too many frames

### ISSUE THREAD

**Issue by JingfeiPeng** [huawei-noah/SMARTS#808]
## **BUG REPORT**
**High Level Description**
Currently, there is no guard in place to prevent the `stateQueue` in client.js from getting too many frames. Astrategy is needed to keep the `stateQueue` from being too long and occupying too much memory. New frames are added to the `stateQueue` on Line 103 in client.js. 
Several strategies on how to reduce size of `stateQueue` is discussed [here](https://github.com/huawei-noah/SMARTS/pull/785#discussion_r624008844)

**SMARTS version**
0.4.15

**Previous associated issues**
Generated from PR #785 

**Steps to reproduce the bug**
The only way stateQueue would get too many frames is when user is running a long simulation, and pausing on envision which accumulates frames sent from the server. Or Envision plays frames at lower speed than server and the differences accumulates over time

**Resulting and expected behaviour**
We want to ensure stateQueue is not overflowing or not taking up too much memory

 
**System information**
 
ubuntu 16.04

**Comment by sah-huawei** [comment]
While PR #810 limited the buffer size and so resolves this issue for now, we may want to revisit this again in the future to provide more options.
