### ISSUE TITLE
example of replacing multiple history vehicles 

### ISSUE THREAD

**Issue by sah-huawei** [huawei-noah/SMARTS#816]
Request from @zbzhu99 in Wechat:

> "I think we need to further implement multi-agent imitation learning on SMARTS, which needs to make all the history replay vehicles to be controlled by outside policies.  Can you provide an example script for this?"

**Comment by sah-huawei** [comment]
@zbzhu99 I think we can do this, although I have some clarification questions. 

I am thinking of expanding the existing `examples/history_vehicles_replacement_for_imitatation_learning.py` script to support replacing some chosen number of vehicles (say, `k`, where `k >= 1`).  But how these `k` vehicles are chosen (and potentially replaced if they exit the simulation) is complicated.

- Would it be ok to select the vehicles to replace at random?
    - if not random, then how should they be chosen?
- If `k` vehicles are chosen and then 1 exits the simulation (or is "done" for another reason), is it ok to continue with `k-1` vehicles?  Or do we need to pick another vehicle (at random?) to maintain `k`?
    - if we allow the number to decrease, is it o to end the data collection early (with less data) if the number gets too low (for example, down to 0 or 1)?

**Comment by zbzhu99** [comment]
Sorry for the late reply.  In multi-agent imitation learning, our ultimate goal is to control all the vehicles in the history data. But for the sake of doing curriculum Learning, the `k` number replacement is needed.
1. Random replacement is ok for now.
2. I think it is ok to continue with less than `k` vehicles. Each time we reset the environment, we choose `k` vehicles to be replaced, and continuously control them until all of them exit the simulation
