### ISSUE TITLE
Action space to directly control vehicle acceleration

### ISSUE THREAD

**Issue by zbzhu99** [huawei-noah/SMARTS#844]
**Is your feature request related to a problem? Please describe.**
Driving datasets like NGSIM only contain driving trajectories without action information. But for most imitation methods, we need expert action guidance. Since we can not directly recover brake and throttle from trajectories, the current continuous agent type can not be used.

**Describe the solution you'd like**
A new action space that includes the acceleration and angular velocity is needed so that we can compute the expert action from the expert states(e.g., position, speed, and heading at each timestep).

**Comment by sah-huawei** [comment]
@zbzhu99:  we are going to try to get this implemented in the next few days.

**Comment by sah-huawei** [comment]
@zbzhue99, we just merged PR #854 into the `develop` branch for this.  Please check it out and let us know if that's what you had in mind.

**Comment by zbzhu99** [comment]
> @zbzhu99, we just merged PR #854 into the `develop` branch for this. Please check it out and let us know if that's what you had in mind.

Thank you. And when will PR #827 be merged?

**Comment by sah-huawei** [comment]
@zbzhu99 I'm still waiting on a second review on it (our policy is that every merge should have 2), but if I haven't gotten one by the time I get the second review on #836, I will merge it anyway (since we discussed it in a meeting here, which sort of counts as a review).  Hopefully that will be tonight, as Iman said he could do it.

**Comment by sah-huawei** [comment]
Note:  PR #878 changes the semantics of this action space such that acceleration is now expected to be a 3-vector instead of a scalar.
