### ISSUE TITLE
Memory growth with Reset per episode

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#855]
## **BUG REPORT**
**High Level Description**
When running an example without `--headless` memory will steadily grow.

**SMARTS version**
SMARTS version 0.4.16 see https://github.com/huawei-noah/SMARTS/pull/852.

**Previous associated issues**
#805
#794

**Steps to reproduce the bug**
Without running envision run:
`python3.7 examples/single_agent.py scenarios/cloverleaf --episodes 1000`

**Resulting and expected behaviour**
Memory growth slowly climbs despite not connecting to envision.

**Comment by RutvikGupta** [comment]
So further investigating the issue, I found that theis a rise in memory is after every episode reset and not due to connection with headless. I saw the same size at the end of a given test i ran regardless of having the `--headless` or not. I believe its because of caching after every reset.

**Comment by RutvikGupta** [comment]
The issue indeed arises from caches, especially caching vehicle indexes and traffic simulation after every episodes. Cache have a maximum limit after which SMARTS stops caching these items and cleans them up. So the memory growth issue is actually just increase in cache size every episode reset. We can specify the maximum limit of caches so that the user can know whether there system can support running SMARTS or not. Although this issue will only arise for high number of episodes as memory increase is quite minor.

**Comment by RutvikGupta** [comment]
We can close this issue now!

**Comment by Yuanzhuo-Liu** [comment]
> The issue indeed arises from caches, especially caching vehicle indexes and traffic simulation after every episodes. Cache have a maximum limit after which SMARTS stops caching these items and cleans them up. So the memory growth issue is actually just increase in cache size every episode reset. We can specify the maximum limit of caches so that the user can know whether there system can support running SMARTS or not. Although this issue will only arise for high number of episodes as memory increase is quite minor.

So how can we solve this problem? Could you please give us a code example. I found this problem with running PPO in Benchmark's 4Lane as well.

**Comment by RutvikGupta** [comment]
This will be something we need to add to allow users to be able to toggle (turning it off or on) caching. 
For now you can remove the `@cache` related marks above methods in various files in SMARTS to prevent it from caching class objects and packages as a workaround.

**Comment by Yuanzhuo-Liu** [comment]
Thanks！How do I find useless caches？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huawei-noah/SMARTS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月3日(星期四) 晚上10:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huawei-noah/SMARTS] Memory growth with Reset per episode (#855)





 
This will be something we need to add to allow users to be able to toggle (turning it off or on) caching.
 For now you can remove the @cache related marks above methods in various files in SMARTS to prevent it from caching class objects and packages as a workaround.
