### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Yuanzhuo-Liu** [huawei-noah/SMARTS#864]
Could you have an installation package on CentOS?
When I use this './install_deps.sh', The following error occurred:
sudo: add-apt-repository: command not found
sudo: apt-get: command not found
sudo: apt-get: command not found

**Comment by Adaickalavan** [comment]
Hi @Yuanzhuo-Liu,

As an alternative, you may consider using our docker container https://github.com/huawei-noah/SMARTS#using-docker .

**Comment by Adaickalavan** [comment]
For the time being, Ubuntu is supported and Docker is provided for all other systems. Please feel free to re-open this issue or start a new one if you need any other help.
