### ISSUE TITLE
understanding single_agent.py conditions

### ISSUE THREAD

**Issue by Dikshuy** [huawei-noah/SMARTS#876]
** High-Level Description**
[Doubt about the conditions in chase via points agent class in `single_agent.py`]

**Desired SMARTS version**
[0.4.12]

**Operating System**
[ ubuntu 18.04]

**Problems**
[I was trying to understand what are the conditions in the act function in ChaseViaPointsAgent class. I want to use some different action space so that's why I need to understand these conditions first. as far as I am able to understand it, we are using the observation data and then passing velocity and lane changing instructions in the form of a tuple in this function, but unable to understand the if conditions.]

**Comment by Adaickalavan** [comment]
Hi @Dikshuy,

I hope the following will be helpful.
+ The docs at https://smarts.readthedocs.io/en/latest/sim/observations.html explains the fields inside the returned `Observation`. 
+ The class `Observation` is implemented here: https://github.com/huawei-noah/SMARTS/blob/master/smarts/core/sensors.py  .

**Comment by Dikshuy** [comment]
thanks @Adaickalavan 
Yeah, I understood how these actions are taking place, but I have doubt understanding these [conditions](https://github.com/huawei-noah/SMARTS/blob/c5a16088152e840dbaa9afe302e8bb9338bc6a93/examples/single_agent.py#L18). please, help in understanding these conditions.

**Comment by Gamenot** [comment]
Hello @Dikshuy , the intention of these ViaPoints are shown as such: https://github.com/huawei-noah/SMARTS/blob/c5a16088152e840dbaa9afe302e8bb9338bc6a93/smarts/core/sensors.py#L113-L117 

- `position` being the x,y location of the point.
- `lane_index` being the lane between `0 -> n` from the right.
- `edge_id` being the name of the lane segment. This can be matched to the `ego_vehicle.edge_id` which is a shorthand for - `ego_vehicle.lane_id` without the postfix lane id (i.e. `"east-west"` vs `"east-west_1"`.)
- `required_speed` which contrary to the name is just a suggestion.

These points are only suggestions that show up in the observations. An agent is given the choice whether to react to them or not.

**Comment by Dikshuy** [comment]
thanks @Gamenot, 
I got it. I am closing this issue.:)
