### ISSUE TITLE
Display episode/scenario info on envision output

### ISSUE THREAD

**Issue by JenishPatel99** [huawei-noah/SMARTS#877]
**Is your feature request related to a problem? Please describe.**
Running an ULTRA experiment (Headless is False) we can visually observe the agent and its behavior (speed, heading, position) through Envision. However, when we view the agent on Envision we are not sure about which episode index ("episode number") the agent is on.

**Describe the solution you'd like**
Is there is an Envision API that allows us to display the episode index and/or scenario information that the agent is currently training/testing on? 

![image](https://user-images.githubusercontent.com/55423380/119575339-246e5a80-bd74-11eb-88ae-9939a84d47da.png)

The above image is something what we were thinking about

**Comment by Gamenot** [comment]
This is a useful visualisation, we can add it to the next version I believe.

**Comment by JenishPatel99** [comment]
> This is a useful visualisation, we can add it to the next version I believe.

@Gamenot Sweet, thank you Tucker. 

Sorry for being a bit greedy 😄 but is there a way to patch the agent details (speed, heading, episode #) onto the frames of the generated MP4 file, If not it is all good.
