### ISSUE TITLE
using PPO from ultra into SMARTS

### ISSUE THREAD

**Issue by Dikshuy** [huawei-noah/SMARTS#879]
** High-Level Description**
[I want my ego agents to take action using PPO policy from ultra]

**Desired SMARTS version**
[e.g. 0.4.12]

**Operating System**
[ubuntu 18.04]

**Problems**
[I want my ego agents to take actions using ppo algorithm which returns actions in form of steering, action, and throttle. I want my ego agents in `single_agent.py` to take these actions while maneuvering,

**Comment by Gamenot** [comment]
@christianjans Would you be able to take up answering this question?

**Comment by christianjans** [comment]
Sure, we have been working with @Dikshuy privately as well. I will work on an implementation hopefully soon.

**Comment by christianjans** [comment]
Hi @Dikshuy, see https://github.com/huawei-noah/SMARTS/tree/smarts_use_ultra_ppo_agent for a working example of how to use the ULTRA PPO agent in SMARTS.

I had to add the ULTRA directory to my PYTHONPATH:
```sh
(.venv) SMARTS $ export PYTHONPATH=$PYTHONPATH:<path_to_SMARTS>/ultra/
```
And then I was able to run it using:
```sh
(.venv) SMARTS $ python examples/single_agent.py scenarios/zoo_intersection/
```
Or of course, feel free to edit the `supervisord.conf` file and then run it using the `supervisord` command.

Note that ULTRA has a lot of restrictions on its baseline agents. For one, the ULTRA baseline agents expect the agent to have a [`PositionalGoal`](https://github.com/huawei-noah/SMARTS/blob/master/smarts/core/scenario.py#L71-L97), not an [`EndlessGoal`](https://github.com/huawei-noah/SMARTS/blob/master/smarts/core/scenario.py#L66-L68), so some scenarios (those that have EndlessGoals for the ego vehicle) will not work (e.g. scenarios/intersections/2lane/).

Finally, the ULTRA PPO's observation adaptation and reward function are highly customized. We are working on refactoring the adaptation in ULTRA to make the observation adaptation and reward function more readable/user-friendly.

Let me know if this is something like what you are looking for, or feel free to comment any issues or other questions you encounter.

**Comment by christianjans** [comment]
Hi @Dikshuy, okay you must be using a different version of ULTRA. See https://github.com/huawei-noah/SMARTS/tree/smarts_use_ultra_ppo_agent_from_develop for the changes needed to get the ULTRA PPO baseline running in SMARTS. Let me know if you run into any more problems.

**Comment by Dikshuy** [comment]
it worked perfectly for me.  thanks, @christianjans. I am closing this issue now.
