### ISSUE TITLE
Enable benchmark metrics.

### ISSUE THREAD

**Issue by valaxkong** [huawei-noah/SMARTS#882]
**Is your feature request related to a problem? Please describe.**
I always believe that the metrics you proposed, namely behavior metric, performance metric and game metric, are of great significance to the algorithms progressing. However, at present, I found that in the latest version, the relevant functions are not enabled. Will you continue this the work?

**Describe the solution you'd like**
I want SMARTS metrics can be enabled.

**Describe alternatives you've considered**
ULTRA may has its own metric, but it's better to be the same as SMARTS

**Additional context**
Not yet.

**Comment by Adaickalavan** [comment]
Standard metrics and scoring formula is now available in SMARTS benchmarks.
