### ISSUE TITLE
maddpg

### ISSUE THREAD

**Issue by Meta-YZ** [huawei-noah/SMARTS#889]
**High Level Description**
[Describe what your goal is]

**Desired SMARTS version**
[ 0.4.16]

**Operating System**
[ ubuntu 18.04]

**Problems**
When I use maddpg in the benchmark, the following errors occured. Could you please help me?
![image](https://user-images.githubusercontent.com/68255669/119987757-5c9fb400-bf93-11eb-988a-d0c99ca1cbd8.png)
![image](https://user-images.githubusercontent.com/68255669/119987882-835dea80-bf93-11eb-94bd-a2452cf18c70.png)
![image](https://user-images.githubusercontent.com/68255669/119987936-8eb11600-bf93-11eb-99b2-9d0a111eabaa.png)
![image](https://user-images.githubusercontent.com/68255669/119988005-a12b4f80-bf93-11eb-8a56-2b0e3e90eef9.png)
![image](https://user-images.githubusercontent.com/68255669/119988096-c0c27800-bf93-11eb-8af6-a623b0cfd011.png)
![image](https://user-images.githubusercontent.com/68255669/119988157-d2a41b00-bf93-11eb-981f-b5911f01e8b7.png)

**Comment by hz3014** [comment]
Hi, I am having same problem, did you manage to solve it?
