### ISSUE TITLE
RemoteAgent uses `async`

### ISSUE THREAD

**Issue by davidrusu** [huawei-noah/SMARTS#89]
Currently we separate out `act` over two methods in the RemoteAgent: `send_obs()` and `recv_act()`. We can simplify this if we use `async`.

```python
class RemoteAgent():
    async def act(obs):
        # ...
        return act
```

Also add a new helper to `AgentSpec`: `build_remote_agent()` that will create an instance of `RemoteAgent`.

**Comment by Adaickalavan** [comment]
Used `concurrent.futures` to combine synchronous `send_observation()` and `recv_action()` methods into one asynchronous task `act()` which returns a `concurrent.futures.Future` object.

This issue is addressed by pull reqeust #138 .
