### ISSUE TITLE
ResourceWarning: Enable tracemalloc to get the object allocation traceback

### ISSUE THREAD

**Issue by Dikshuy** [huawei-noah/SMARTS#898]
**High-Level Description**
When I try to use ultra it throws me this resource warning: ResourceWarning: Enable tracemalloc to get the object allocation traceback

**Desired SMARTS version**
 0.4.16

**Operating System**
ubuntu 18.04

**Problems**
I tried running following command:
```
$ python ultra/evaluate.py --task 1 --level easy --models logs/<timestamped_experiment_name>/models/ --episodes 5 --policy ppo
```
and it throws me this warning everytime:
> ResourceWarning:  Enable tracemalloc to get the object allocation traceback

**Comment by JenishPatel99** [comment]
Hello @Dikshuy, thank you for submitting the issue. I would like ask a couple of questions before troubleshooting
- What version of ULTRA have you been using?
- Has this warning prevented you from successfully running the evaluate (or train) script?

We have encountered the `ResourceWarning: Enable tracemalloc to get the object allocation traceback` when we execute our train and evaluate scripts. Although, the warning is pretty naïve, it has bloated the output. We have investigated this warning in the past and found that the warning originates from a resource leak in a ray module. Ray is a distributed computing framework which we use to scale ULTRA's training and evaluation processes.

A similar issue regarding the resource warning was created on Ray's GitHub repository ([https://github.com/ray-project/ray/issues/9546](url))

**Comment by Dikshuy** [comment]
I am using the latest version of ultra. There were some other errors along with it, which I feel was there because of improper interfacing as it is not able to generate scenarios earlier. I have tried running this command: `$ python ultra/ultra/scenarios/interface.py generate --task 1 --level easy` and now this error came when I tried using this command `python ultra/ultra/train.py --task 1 --level easy --episodes 10 --eval-episodes 5 --eval-rate 100 --policy ppo`:
```
Traceback (most recent call last):
  File "/usr/share/sumo/tools/sumolib/net/__init__.py", line 814, in readNet
    parse(gzip.open(filename), netreader)
  File "/usr/lib/python3.7/xml/sax/__init__.py", line 33, in parse
    parser.parse(source)
  File "/usr/lib/python3.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.7/xml/sax/xmlreader.py", line 123, in parse
    buffer = file.read(self._bufsize)
  File "/usr/lib/python3.7/gzip.py", line 287, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.7/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.7/gzip.py", line 474, in read
    if not self._read_gzip_header():
  File "/usr/lib/python3.7/gzip.py", line 422, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'<?')
```

**Comment by Dikshuy** [comment]
thanks @JenishPatel99 , 
able to resolve it. closing this issue now.
