### ISSUE TITLE
map.glb files missing while using ultra

### ISSUE THREAD

**Issue by Dikshuy** [huawei-noah/SMARTS#899]
**High-Level Description**
Unable to generate "easy level" scenario for task 1 in ultra

**Desired SMARTS version**
0.4.16

**Operating System**
ubuntu 18.04

**Problems**
```
$ python ultra/scenarios/interface.py generate --task 1 --level easy
```
When I ran this command, it throws me these types of multiple errors.
```
Generating Scenario ...
ultra/ultra/scenarios/task1/config.yaml
>> train 2lane_curvy_t count:4000 generated: 0.4 real: 0.4
Process Process-10:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dikshant/github/SMARTS/ultra/ultra/scenarios/generate_scenarios.py", line 458, in scenario_worker
    intersection_name=intersection_type,
  File "/home/dikshant/github/SMARTS/ultra/ultra/scenarios/generate_scenarios.py", line 243, in generate_left_turn_missions
    copy_map_files(scenario, map_dir, speed)
  File "/home/dikshant/github/SMARTS/ultra/ultra/scenarios/generate_scenarios.py", line 103, in copy_map_files
    copyfile(map_dir + f"/{speed}/map.glb", scenario + "/map.glb")
  File "/usr/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/dikshant/github/SMARTS/ultra/ultra/scenarios/pool/2lane_curvy_t/100kmh/map.glb'
```
`.glb` files are missing for all scenarios

**Comment by JenishPatel99** [comment]
Hello @Dikshuy, thank you for submitting the issue. Have you tried generating the maps using the `scl` command line interface tool? Here is the command for that ⬇️ 

`scl scenario build-all ultra/scenarios/pool` 

The above command will generate the maps needed for ULTRA scenarios as `.glb` files. Maps are descriptions of the roads used in the ULTRA scenarios and only need to be compiled once. They only need to be compiled again if they have been modified.

If this issue persists or have any other questions, please feel free to let us know

**Comment by Dikshuy** [comment]
thanks @JenishPatel99 ,
it worked but I have to do `scl scenario build-all ultra/ultra/scenarios/pool` instead of `scl scenario build-all ultra/scenarios/pool`. I have to do few more changes in some codes to accommodate this ultra/ultra thing.  i am closing this issue :)
