### ISSUE TITLE
Add "time to pass through intersection" metric in ULTRA?

### ISSUE THREAD

**Issue by christianjans** [huawei-noah/SMARTS#912]
On a successful episode (when the agent reaches its goal), record the number of time steps it took the ego vehicle to pass through the intersection.

Questions:
- What is recorded on unsuccessful episodes (when the ego vehicle does not reach the intersection, or does not pass through the intersection)?
- In ULTRA, will we ever run into a case where the scenario does not have an intersection?

**Comment by Adaickalavan** [comment]
A standard set of metrics is now included in SMARTS.
