### ISSUE TITLE
Implement frame stacking through SMARTS simulator rather than environment wrappers?

### ISSUE THREAD

**Issue by christianjans** [huawei-noah/SMARTS#921]
**Is your feature request related to a problem? Please describe.**
I have seen #916 and the [frame stack wrapper](https://github.com/huawei-noah/SMARTS/blob/6cb8ffda74e235c25d63b74313623b2e03e402f7/benchmark/wrappers/rllib/frame_stack.py) used in the RLlib benchmarks, but was wondering if frame stacking could be implemented without the use of an environment wrapper. That is, it would be done internally in SMARTS, allowing for frame stacking to be specified for stackable elements (such as images, lidar, etc.) of each agent's observation.

**Describe the solution you'd like**
Say, for example, a user wants their agent to have their RGB observation be the current RGB image plus the previous three RGB images (for a total of four images in the stack). They could define their AgentSpec like:
```python
my_agent_spec = AgentSpec(
  interface=AgentInterface(
    rgb=RGB(width=64, height=64, stack_size=4, resolution=(50 / 64)),
    # ... other parts of the agent interface ...
  ),
  # ... other parts of the agent spec ...
}
```
And then when `step` is called on an environment like "hiway-v0" (without a wrapper), SMARTS would return the agent's observation with a stacked `TopDownRGB` of some form. I am unsure of exactly what form this part of the observation should take. Whether `observation.top_down_rgb` should be a `Sequence` of `TopDownRGB` instances, or perhaps `TopDownRGB`'s attributes, `metadata` and `data`, should be `Sequence`s?

**Describe alternatives you've considered**
Alternatives would be similar to the Gym wrapper in #916 and the RLlib wrapper used in the SMARTS' benchmarking. Perhaps a concern with these wrapper methods however is that not every agent may need, or expect, a stacked observation. For example, in #916 it seems like an environment that is wrapped by `FrameStack` will return an agent's observation in the form of a `Sequence` type (a `Deque`). Modifications to the agents' observation adapters may be required to handle this change.

Additionally, if not every agent requires a stacked observation, the returned observations from SMARTS will be considerably larger than needed as the environment will stack _all_ of the agent's observations.

Finally, these wrappers don't provide the same "control" over the observation as this proposed method would when it comes to stacking. For example, with the environment wrappers, if one agent wants a stacked observation, then all other agents must have a stacked observation. And if an agent just wants the images in their observation to be stacked, the environment wrappers would actually stack everything in the agent's observation.

**Additional context**
Not sure if this would be feasible without any breaking changes. But I am curious if this was ever a potential solution, or why this may not be possible.

**Comment by Adaickalavan** [comment]
**Issue 1**
> That is, it would be done internally in SMARTS, allowing for frame stacking to be specified for stackable elements (such as images, lidar, etc.) of each agent's observation.

> Perhaps a concern with these wrapper methods however is that not every agent may need, or expect, a stacked observation.

> Additionally, if not every agent requires a stacked observation, the returned observations from SMARTS will be considerably larger than needed as the environment will stack all of the agent's observations.

> For example, with the environment wrappers, if one agent wants a stacked observation, then all other agents must have a stacked observation.

> Not sure if this would be feasible without any breaking changes.

These point to a lack of highly individualised observation stacking options for each agent. I think, now it is just a balance between (i) writing simple repeatable use code and (ii) writing classes with many parameters returning observation with mixed single/stacked observation attributes.

It is possible to implement the above individualised stacking options, but not without interface-breaking changes.

**Issue 2**
> Whether observation.top_down_rgb should be a Sequence of TopDownRGB instances, or perhaps TopDownRGB's attributes, metadata and data, should be Sequences?

Difficulty at the moment:
- Observation attributes are complex
- Observation attributes are not in friendly numpy format
- No clear guide to stack some of the observation attributes

Hence, the current best solution would be to return a `Sequence` when stacking. 

**Issue 3**
> Modifications to the agents' observation adapters may be required to handle this change.

> And if an agent just wants the images in their observation to be stacked, the environment wrappers would actually stack everything in the agent's observation.

No. The data flow is as follows: 
`original environment -> observation adapter -> frame_stack wrapper`

Here, `frame_stack` wrapper simply stacks the output of the observation adapter over several time points.
