### ISSUE TITLE
Save checkpoint directories in terms of episode index

### ISSUE THREAD

**Issue by JenishPatel99** [huawei-noah/SMARTS#928]
Previously, we were saving the checkpoint directories as the agent's iteration (total number of steps taken). However, in recent times we have moved over to episodic training and evaluation, which means that it should be appropriate to start saving the checkpoint directories as the agent's episode index.

Let me know your thoughts on this @christianjans @AlexLewandowski

**Comment by christianjans** [comment]
I think this would be a fine change. If we go this route however, would it make sense to move all other step-based values to be episode-based? Such as the data that is collected during training/evaluation.

**Comment by JenishPatel99** [comment]
> I think this would be a fine change. If we go this route however, would it make sense to move all other step-based values to be episode-based? Such as the data that is collected during training/evaluation.

Absolutely, I had been collecting data episodically for both training and evaluation for the curriculum learning branches. I forgot that those changes were not implemented inside of ultra-develop. Those changes can be found here: #932
