### ISSUE TITLE
grpcio version error

### ISSUE THREAD

**Issue by Dikshuy** [huawei-noah/SMARTS#936]
## **BUG REPORT**
**High Level Description**
`pip install -e .[train]` throws error due to compatibility issue 

**SMARTS version**
0.4.16

**Steps to reproduce the bug**
`pip install -e .[train]`

**Resulting and expected behavior**
all the dependencies should be installed properly

**Error logs and screenshots**
```
ERROR: Could not find a version that satisfies the requirement grpcio==1.37.0 (from smarts[train])
ERROR: No matching distribution found for grpcio==1.37.0
```
 
**System information**
 
- Operating system & Environment: installation on compute canada platform
- Python version: 3.7.9
- Python packages: grpcio
- Date when bug occurred: June 14, 2021
 
**Impact [If known]**
unable to complete the library installation process

**Way out to remove this error**
edit `setup.py` and change line no. 61 to:
`"grpcio==1.38.0"`
this worked perfectly for me and I am able to complete the installation process. 

please incorporate this change. :)

**Comment by Dikshuy** [comment]
Just to clarify, I encountered this error while setting up SMARTS on compute canada

**Comment by Adaickalavan** [comment]
The existing commands appear to install SMARTS without any issues:
```
$ git checkout master
$ python3.7 -m venv .venv
$ source .venv/bin/activate
$ pip install --upgrade pip
$ pip install --no-cache-dir -r requirements.txt 
$ pip install --no-cache-dir -e .[train,test,dev]
```

**Comment by Dikshuy** [comment]
Yeah, it seems to work perfectly in my local setup, but I was trying to install it on compute Canada, and there I got this error.

**Comment by Adaickalavan** [comment]
Are you using Singularity for deployment in Compute Canada?

**Comment by Dikshuy** [comment]
earlier I was not but currently, I am trying to use singularity for deployment on CC. There are some version issues when I try to do it by directly cloning the GitHub repo and then doing `make sanity-test`. I have opened this issue as well: https://github.com/huawei-noah/SMARTS/issues/939 and explained the further complications while setting up directly.

**Comment by Adaickalavan** [comment]
1. Singularity support is now provided via pull request #1016.
2. Consider using Singularity on ComputeCanada instead of directly setting up.
3. For issues on using ComputeCanada, see and dicuss in thread #963.
4. No updates to grpc since it is not causing any errors currently.
