### ISSUE TITLE
Ultra: Ego agent initially white but suddenly turns red after some time

### ISSUE THREAD

**Issue by Leoluo0320** [huawei-noah/SMARTS#938]
**High Level Description**
When I am training the agent under the ultra directory using the documentation provided. When observing the training process and evaluation process, I found that the color of the ego agent initially was white and after some time it suddenly turns red and there is a green path shown. Is that normal?

**Desired SMARTS version**
0.4.16

**Operating System**
Ubuntu 16.04

**Problems**
None

**Comment by christianjans** [comment]
Hi @Leoluo0320, yes I believe I know what you mean.

In ULTRA, we allow the ego vehicle to "hijack" social vehicles. So initially, a social vehicle is spawned, and when it gets closer to the intersection, the SMARTS simulator tells the ego agent that it can take control of this social vehicle. If the ego agent decides to take over that social vehicle, the vehicle's colour will change to red to indicate that it is under the ego agent's control.

I believe this was a choice by the original developers of ULTRA to allow for the ego vehicle to spawn closer to the intersection and experience more traffic.
