### ISSUE TITLE
Ultra: Generate Map Error

### ISSUE THREAD

**Issue by Leoluo0320** [huawei-noah/SMARTS#942]
**High Level Description**
Under ultra-develop branch, when generating the map using command **_scl scenario build-all ultra/scenarios/pool_**, an exception raised for Thread-72 because there is no directory _**ultra/scenarios/pool/experiment_pool/behavior_race/70kmh/map.net.xml**_

**Desired SMARTS version**
0.4.16

**Operating System**
ubuntu 16.04

**Problems**
None

**Comment by Leoluo0320** [comment]
Also I check the ultra-develop branch, the exception raised is No such directory "**_ultra/scenarios/pool/2lane_curvy_t/70kmh/map.net.xml_**".

**Comment by christianjans** [comment]
Documentation is updated in #944.

**Comment by Leoluo0320** [comment]
It works thank you for your reply.
