### ISSUE TITLE
Visualization in ULTRA

### ISSUE THREAD

**Issue by Dikshuy** [huawei-noah/SMARTS#949]
**High-Level Description**
I want to visualize how the agents are loading up and taking actions in ULTRA using envision.

**Desired SMARTS version**
0.4.16

**Operating System**
ubuntu 18.04

**Problems**
For the initial part of training, I want to visualize using envision, but I cannot do so. The training is still going on, but the local host is not loading up. Also, it shows the following error:
```
 ERROR:Client:Connection to Envision terminated with: [Errno 111] Connection refused
(pid=20137) ERROR:websocket:error from callback <function Client._connect.<locals>.on_close at 0x7f2cf087db00>: on_close() takes 1 positional argument but 3 were given
(pid=20137) *** Aborted at 1623909023 (unix time) try "date -d @1623909023" if you are using GNU date ***
(pid=20137) PC: @                0x0 (unknown)
(pid=20137) *** SIGSEGV (@0x7f2e38ff8c60) received by PID 20335 (TID 0x7f2e5ec88740) from PID 956271712; stack trace: ***
(pid=20137) argv[0]=
(pid=20137)     @     0x7f2e5e89d980 (unknown)
(pid=20137)     @     0x7f2e5c7c4afb pollset_shutdown()
(pid=20137)     @     0x7f2e5c7a1188 cq_shutdown_next()
(pid=20137)     @     0x7f2e5c7a159f grpc_completion_queue_shutdown
(pid=20137)     @     0x7f2e5c35a91c ray::gcs::ServiceBasedGcsClient::~ServiceBasedGcsClient()
(pid=20137)     @     0x7f2e5c35ab51 ray::gcs::ServiceBasedGcsClient::~ServiceBasedGcsClient()
(pid=20137)     @     0x7f2e5c26227b ray::gcs::GlobalStateAccessor::~GlobalStateAccessor()
(pid=20137)     @     0x7f2e5c1cb581 __pyx_tp_dealloc_3ray_7_raylet_GlobalStateAccessor()
(pid=20137)     @     0x5622e85f6e91 (unknown)
(pid=20137)     @     0x5622e84fdeb0 _PyObjectDict_SetItem
(pid=20137)     @     0x5622e85f9f11 _PyObject_GenericSetAttrWithDict
(pid=20137)     @     0x5622e850b123 PyObject_SetAttr
(pid=20137)     @     0x5622e854ab4e _PyEval_EvalFrameDefault
(pid=20137)     @     0x5622e84dc30a _PyFunction_FastCallKeywords
(pid=20137)     @     0x5622e854a60e _PyEval_EvalFrameDefault
(pid=20137)     @     0x5622e85494ae _PyEval_EvalCodeWithName
(pid=20137)     @     0x5622e84dc3ea _PyFunction_FastCallKeywords
(pid=20137)     @     0x5622e854a3b5 _PyEval_EvalFrameDefault
(pid=20137)     @     0x5622e85494ae _PyEval_EvalCodeWithName
(pid=20137)     @     0x5622e841beb1 _PyFunction_FastCallDict
(pid=20137)     @     0x5622e85b4512 PyErr_CheckSignals
(pid=20137)     @     0x5622e84ac449 (unknown)
(pid=20137)     @     0x5622e84daafd _PyMethodDef_RawFastCallKeywords
(pid=20137)     @     0x5622e84daa50 _PyCFunction_FastCallKeywords
(pid=20137)     @     0x5622e854ebe0 _PyEval_EvalFrameDefault
(pid=20137)     @     0x5622e85497ad _PyEval_EvalCodeWithName
(pid=20137)     @     0x5622e84dc3ea _PyFunction_FastCallKeywords
(pid=20137)     @     0x5622e854a3b5 _PyEval_EvalFrameDefault
(pid=20137)     @     0x5622e85497ad _PyEval_EvalCodeWithName
(pid=20137)     @     0x5622e84dca81 _PyObject_Call_Prepend
(pid=20137)     @     0x5622e84dcea1 PyObject_Call
```

**Comment by Adaickalavan** [comment]
The issue of `ERROR:websocket:error from callback <function Client._connect.<locals>.on_close at 0x7f2cf087db00>: on_close() takes 1 positional argument but 3 were given` appears to be fixed in the `develop` branch by pull request #906 which is yet to be merged into the `master` branch.

**Comment by Dikshuy** [comment]
Thanks, @Adaickalavan,
I am not sure but is this error stopping me from visualizing on envision? I also came across this error earlier when I was working with SMARTS, but at that time, I was still able to visualize it on localhost. This time I tried to visualize in ULTRA. I used this command:
` python ultra/train.py --task 1 --level easy --episodes 50 --eval-episodes 10 --eval-rate 100 --policy ppo`.
Since I haven't used the `--headless` argument, envision should start to work. But it's throwing me the above-mentioned error.
Please correct me if I am wrong.

**Comment by Dikshuy** [comment]
I have to start ULTRA's envision with the command `./ultra/env/envision_base.sh` before running the training. I just missed that step.
![image](https://user-images.githubusercontent.com/40022959/122400599-7e3ffa00-cf99-11eb-9001-04ed138d555b.png)
 thanks @Adaickalavan for your feedback. Closing this issue now,
