### ISSUE TITLE
Ultra: Acceleration for trainning

### ISSUE THREAD

**Issue by Leoluo0320** [huawei-noah/SMARTS#950]
**High Level Description**
By checking the source code of "train.py" under the ultra directory, it seems that the training process only use 1 cpu core and does not use cuda acceleration, which makes the training process slow. I saw there is a variable "num_gpus" checking if the training device has a gpu. But by checking the usage of the variable it seems that it is not used anywhere. Is it just a varaible for future improvement of cuda acceleration? 

**Desired SMARTS version**
0.4.16

**Operating System**
ubuntu 16.04

**Problems**
None

**Comment by christianjans** [comment]
Hi @Leoluo0320, yes despite what `train.py` seems to depict, the GPUs should be used for inference and learning of the baseline policies' neural networks. For example, in the DQN policy, it will use the GPU if it is available: https://github.com/huawei-noah/SMARTS/blob/c5a16088152e840dbaa9afe302e8bb9338bc6a93/ultra/ultra/baselines/dqn/dqn/policy.py#L71 You can perhaps check that a GPU is being used by running the command `nvidia-smi` before training and seeing how much GPU memory your GPU uses when idle. Then, run something like:
```bash
nohup python -u ultra/train.py --task 1 --level easy --policy bdqn --eval-rate 200 --eval-episodes 2 --episodes 2 --headless True > log_test.txt &
```
To run a training process in the background (you can view the training output with `tail -f log_test.txt`). Then, once training has run for a while, run `nvidia-smi` again, and it should show that more memory is being used. For example, running `nvidia-smi` before training for me yielded:
```bash
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2080    Off  | 00000000:01:00.0 Off |                  N/A |
| 25%   26C    P8     6W / 215W |     72MiB /  7979MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```
And running `nvidia-smi` during training outputted:
```bash
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2080    Off  | 00000000:01:00.0 Off |                  N/A |
| 25%   38C    P2    34W / 215W |   1811MiB /  7979MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```
Notice that the "Memory-Usage" metric has increased. Is this along the lines of what you were thinking?

**Comment by Leoluo0320** [comment]
Yes it is what I am thinking. I used to check the nvidia-smi but since it is something like 1990Mib / 7959 Mib I thought it did not use the cuda acceleration. I thought it will take more memory than this.

Also, may I asked around how many episodes will be sufficient to train a reasonable agent? Let just say task is 1 and level is easy using dqn. I saw the default episodes is 1,000,000 which seems to be too many.

**Comment by christianjans** [comment]
Yeah great question. We have so far been unable to get our DQN baseline to perform well in ULTRA's task 1, level easy. Perhaps try using one of the other baselines (BDQN, PPO, SAC, or TD3). The other baselines all learn to drive fairly well after maybe around 5000-8000 episodes.

One thing that all baselines seem to currently struggle with is collisions with other social vehicles. We have found that our baselines, even after training for 8000 episodes, still have trouble stopping for other social vehicles.

**Comment by Leoluo0320** [comment]
Oh got it. Thank you for your reply. May I assume it is because of the continuous action space since DQN is normally used to train discrete action space?

**Comment by christianjans** [comment]
Great point, however, our DQN actually does discretize the continuous action space. You can see this here: https://github.com/huawei-noah/SMARTS/blob/c5a16088152e840dbaa9afe302e8bb9338bc6a93/ultra/ultra/baselines/dqn/dqn/policy.py#L50-L55 The array `np.asarray([-0.25, 0.0, 0.5, 0.75, 1.0])` discretizes the throttle (and brake), and the array `np.asarray([-1.0, -0.75, -0.5, -0.25, -0.1, 0.0, 0.1, 0.25, 0.5, 0.75, 1.0])` discretizes the steering.

So currently, we are unsure exactly why the DQN has so much trouble learning. It is definitely something to look into. On the other hand, the BDQN ("Behavioural" DQN) baseline uses the [`ActionSpaceType.Lane`](https://github.com/huawei-noah/SMARTS/blob/master/smarts/core/controllers/__init__.py#L43) and actually trims its actions to be just "keep_lane" or "slow_down". We have found that this performs much better than the DQN baseline, however, like the other baselines, it struggles with collisions.

**Comment by Leoluo0320** [comment]
Oh OK it is wired. I am trying another policy now and according to the rewards get during the training process it does looks much better. However I always get some error during the training process, which interrupt the trainning. I used command "python ultra/train.py --task 1 --level easy --episodes 9000 --eval-episodes 200 --eval-rate 800 --policy sac --headless > sac_training.txt" and the error I got is "IOError: 14: failed to connect to all addresses". It says it is most likely because the local raylet has crashed, is there any reason that wil lead to the crash? Thank you ahead.

**Comment by christianjans** [comment]
Strange, I ran that command on our `ultra-develop` branch just now and it works fine for me. I am not sure what could be causing it. Feel free to submit another issue with more information if you have not figured it out yet.

**Comment by m485liuw** [comment]
Hi christian,
Related questions here. What would be good choices for eval-episodee and eval-rate? Did you use any sort of curriculum learning when you train the model to speed up the process? Or you simply train on 10000 scenarios for task 1 easy as in task1's config.yaml?

**Comment by christianjans** [comment]
Hi @m485liuw, good questions.

> What would be good choices for eval-episodee and eval-rate?

The `--eval-episode` argument should be equal to the number of testing scenarios you have for that task's level. So for example, in Task 1, Level easy, the `--eval-episodes` should be 200 since we have 200 testing scenarios: https://github.com/huawei-noah/SMARTS/blob/c5a16088152e840dbaa9afe302e8bb9338bc6a93/ultra/ultra/scenarios/task1/config.yaml#L77.
For the `--eval-rate` argument, it can be whatever you like it to be. It just specifies the rate at which evaluation is performed on your agent.

> Did you use any sort of curriculum learning when you train the model to speed up the process? Or you simply train on 10000 scenarios for task 1 easy as in task1's config.yaml?

We didn't do any curriculum learning for training, the scenarios were just presented to the agent in some random order.

**Comment by Leoluo0320** [comment]
> Strange, I ran that command on our `ultra-develop` branch just now and it works fine for me. I am not sure what could be causing it. Feel free to submit another issue with more information if you have not figured it out yet.

Hi @christianjans , yes the command works fine but the error occurs during the training process. Maybe like around 4000/9000 episodes.

**Comment by christianjans** [comment]
@Leoluo0320, hmm okay, perhaps submit a new issue with all the information. I am currently not sure what the issue could be just by that error.

You could also maybe try piping the output to a text file in the background while running Python with unbuffered binary output:
```bash
$ nohup python -u ultra/train.py ... > text_file.txt &
```
And then view the results with `tail -f text_file.txt`. I'm not sure if this will help or not though without more information.

**Comment by Leoluo0320** [comment]
OK thank you. I will try again today and if there is any issue I will open another issue.
