### ISSUE TITLE
Obtain solid ULTRA baseline(s) with visuals

### ISSUE THREAD

**Issue by christianjans** [huawei-noah/SMARTS#954]
- [ ] Get results for one, or multiple, well-performing baseline agents on Task ? Level ?
  - What observation space should the baseline agent use? What action space?
- [ ] Record evaluation episodes of successes and failures

**Comment by JenishPatel99** [comment]
@christianjans I have trained the BDQN on simple, easy, medium, hard level for task 1. I can continue training BDQN with image based observation on those 4 levels.

**Comment by christianjans** [comment]
Sure, there is some parameter configuration that needs to be done if we use images though. We can discuss today if you like.
