### ISSUE TITLE
Training loop terminates after few episodes

### ISSUE THREAD

**Issue by Dikshuy** [huawei-noah/SMARTS#970]
**High-Level Description**
Training loop termination in UTLRA

**Desired SMARTS version**
 0.4.16

**Operating System**
ubuntu 18.04

**Problems**
while training for multi-agents in ULTRA, sometimes the loop terminate after few episodes, giving the following error:
```
Exception ignored in: <function _ChannelCallState.__del__ at 0x7f0824052b00>
Traceback (most recent call last):
  File "/home/dikshant/github/SMARTS/ultra/.VENV/lib/python3.7/site-packages/grpc/_channel.py", line 1126, in __del__
AttributeError: 'NoneType' object has no attribute 'cancelled'
Exception ignored in: <function _ChannelCallState.__del__ at 0x7f0824052b00>
```
a somewhat related issue is mentioned on the official github repo of grpc as well: https://github.com/grpc/grpc/issues/23290

**Comment by christianjans** [comment]
Hi @Dikshuy, can you provide some steps to reproduce this error? Also, is this on Compute Canada?

**Comment by Dikshuy** [comment]
no, it's on my local setup! 
I have been adding few more elements to the state space after which I got this error. you may clone this: https://github.com/Dikshuy/SMARTS-lite, do the basic setup of ultra and try running the following command:
`python ultra/hammer_train.py --task 0-3agents --level easy --episodes 10 --eval-episodes 5 --eval-rate 100 --policy ppo,ppo,ppo --headless `

**Comment by christianjans** [comment]
Okay, yes when running this command it should terminate after 10 training episodes. Is this what you mean by a "few episodes"? The error that you get when the training finishes is benign (see #735 and #704).

**Comment by Dikshuy** [comment]
oh yeah, I just saw that it is due to only 10 training episodes and when they are over, it shows this error. Is there any way to remove this error (maybe it can be a later fix you want to do). 

thanks, @christianjans, closing this issue for time being but feel free to add more comments if you want to have sth in mind.

**Comment by christianjans** [comment]
This error is a result of the changes in #704 and occurs because the SMARTS version that we currently use in ULTRA has a GRPC version with this error. When ULTRA updates its SMARTS dependency to a newer version that has a newer GRPC dependency, this error will not appear anymore.
