### ISSUE TITLE
Customize action space

### ISSUE THREAD

**Issue by Leoluo0320** [huawei-noah/SMARTS#976]
**High Level Description**
I am currently planning to customize a lane following task which will follow the lane automatically and only control the speed of ego car, i.e. I only want longitudinal control (which will control the speed) instead of both longitudinal and lateral control. I did not find a currently existing action space that satisfy the requirement so I wonder is there any documentation that can help me custiomize my own action space? Thank you.

**Desired SMARTS version**
0.4.16

**Operating System**
ubuntu 16.04

**Problems**
Also in the documentation, I found that you mention ActionSpaceType.Lane will be changed to a tuple of integer for lange_change and a float for target_speed. Will it be helpful for my requirement? If so, about how soon will it be released? Thank you.

**Comment by christianjans** [comment]
Hi @Leoluo0320,

> I wonder is there any documentation that can help me customize my own action space?

As far as I am aware, SMARTS does not support this easily. Is this correct @Gamenot?

 > I found that you mention ActionSpaceType.Lane will be changed to a tuple of integer for lange_change and a float for target_speed.

I believe this has now been changed to its own action space type, specifically, the `ActionSpaceType.LaneWithContinuousSpeed`: https://github.com/huawei-noah/SMARTS/blob/c5a16088152e840dbaa9afe302e8bb9338bc6a93/smarts/core/controllers/__init__.py#L45 It allows the agent to set a target speed and a lane change direction: https://github.com/huawei-noah/SMARTS/blob/c5a16088152e840dbaa9afe302e8bb9338bc6a93/smarts/core/controllers/__init__.py#L89-L98

I believe that the `ActionSpaceType.LaneWithContinuousSpeed` could be helpful for your requirement. The action that an agent using this action space type would be in the form of `[target_speed, lane_change]`. So, if you make your agent only select a target speed, and always ensure that the lane change part of the action is `0`, then you will achieve purely longitudinal control.

**Comment by Leoluo0320** [comment]
Thank you for your reply. I also found this ActionSpaceType yesterday and am currently using it. It is still helpful to confirm it is the right thing to do, thank you!
